version: '3'
services:

  ora2pg:
    #build:
    #  context: .
    image: platformization/ora2pg
    #command: ora2pg --debug --namespace TASY --conf config/ora2pg.conf --type TABLE --allow 'TABLE[NICU.*]'
    command: ora2pg --debug --namespace COMERCIAL --conf config/ora2pg.conf --type SHOW_REPORT --estimate_cost --dump_as_html > report/migration_report.html
    container_name: ora2pg
    network_mode: "host"
    volumes:
      - ora2pg-data:/data
      - ./config:/config
      - ./report:/report
    environment:
      - CONFIG_LOCATION=config/ora2pg.conf

volumes:
  ora2pg-data:
