-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';


--###################################################################
CREATE OR REPLACE PROCEDURE gerar_pacote_autorizacao_pck.descobrar_mat_autorizado ( nr_seq_mat_autor_p bigint, qt_solicidata_p bigint, nr_seq_pacote_p bigint) AS $body$
DECLARE

nr_sequencia_w	bigint;


BEGIN

select	nextval('material_autorizado_seq')
into STRICT	nr_sequencia_w
;

insert into material_autorizado(nr_sequencia,
	nr_sequencia_autor,
	nr_atendimento,
	cd_material,
	qt_solicitada,
	qt_autorizada,
	ds_observacao,
	nm_usuario_aprov,
	dt_aprovacao,
	nm_usuario,
	dt_atualizacao,
	nm_usuario_nrec,
	dt_atualizacao_nrec,
	vl_unitario,
	cd_cgc_fabricante,
	nr_seq_fabricante,
	ds_mat_convenio,
	ie_valor_conta,
	nr_seq_opme,
	vl_cotado,
	nr_prescricao,
	nr_seq_prescricao)
SELECT	nr_sequencia_w,
	nr_sequencia_autor,
	nr_atendimento,
	cd_material,
	qt_solicidata_p,
	0,
	ds_observacao,
	nm_usuario_aprov,
	dt_aprovacao,
	current_setting('gerar_pacote_autorizacao_pck.nm_usuario_w')::varchar(15),
	clock_timestamp(),
	current_setting('gerar_pacote_autorizacao_pck.nm_usuario_w')::varchar(15),
	clock_timestamp(),
	vl_unitario,
	cd_cgc_fabricante,
	nr_seq_fabricante,
	ds_mat_convenio,
	ie_valor_conta,
	nr_seq_opme,
	vl_cotado,
	nr_prescricao,
	nr_seq_prescricao
from	material_autorizado
where	nr_sequencia = nr_seq_mat_autor_p;

if (nr_seq_pacote_p > 0) then

	insert	into material_autor_pacote(nr_sequencia,
		dt_atualizacao,
		nm_usuario,
		nr_seq_mat_autor,
		nr_seq_pacote_autor,
		qt_solicitada_pct,
		qt_solicitada_ant)
	values (nextval('material_autor_pacote_seq'),
		clock_timestamp(),
		current_setting('gerar_pacote_autorizacao_pck.nm_usuario_w')::varchar(15),
		nr_sequencia_w,
		nr_seq_pacote_p,
		0, --Gravo ambos com zero para saber que este item é gerado do desdobramento e identificar ao desfazer o pacote.
		0);
end if;


END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE gerar_pacote_autorizacao_pck.descobrar_mat_autorizado ( nr_seq_mat_autor_p bigint, qt_solicidata_p bigint, nr_seq_pacote_p bigint) FROM PUBLIC;
