-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';




CREATE OR REPLACE PROCEDURE smart_schedule_data_process.add_item_block (nr_seq_item_p bigint) AS $body$
DECLARE

	
  c01_w RECORD;

BEGIN
		SELECT b.nr_sequencia,
               b.nr_seq_proc_interno,
               ageint_obter_prior_apresent(b.nr_seq_agenda_int, b.nr_seq_proc_interno, current_setting('smart_schedule_data_process.cd_estabelecimento_ativo_w')::estabelecimento.cd_estabelecimento%TYPE, b.nr_seq_grupo_selec, b.nr_sequencia) nr_seq_ordem_apresent,
               ageint_obter_prioridade(b.nr_seq_agenda_int, b.nr_seq_proc_interno, current_setting('smart_schedule_data_process.cd_estabelecimento_ativo_w')::estabelecimento.cd_estabelecimento%TYPE, b.nr_seq_grupo_selec) nr_seq_ordem,
               b.nr_minuto_duracao,
               b.ie_tipo_item,
               b.ie_lado,
               b.ie_tipo_agendamento,
               b.cd_procedimento,
               b.ie_origem_proced,
               coalesce(b.ie_anestesia, 'N'),
               current_setting('smart_schedule_data_process.nr_seq_combo_padrao_w')::bigint,
               b.nr_seq_area_atuacao,
               b.cd_medico,
               b.nr_seq_grupo_selec,
               coalesce(b.ie_genero_prof, 'A'),
               b.nr_seq_agrup_setor,
               b.nr_seq_agrupamento,
               b.cd_especialidade,
               b.ie_classif_agenda,
               b.nr_seq_classif_agenda,
               b.nr_classificacao_agend,
               b.cd_anestesista,
               b.nr_seq_item_princ,
               ageint_obter_se_exame_princ(b.nr_seq_grupo_proc, b.nr_seq_proc_interno),
               b.nr_seq_agenda_cons,
               b.nr_seq_agenda_exame,
               ageint_obter_status_agenda(coalesce(b.nr_seq_agenda_cons, 0), coalesce(b.nr_seq_agenda_exame, 0)),
               substr(obter_item_grid_ageint(b.nr_seq_proc_interno, b.cd_medico, b.cd_especialidade, 1), 1, 255),
               coalesce(b.ie_rodizio_especialidade, 'N'),
               b.nr_seq_regra
          INTO STRICT agenda_block_w[nr_seq_item_p].nr_sequencia,
               agenda_block_w[nr_seq_item_p].nr_seq_proc_interno,
               agenda_block_w[nr_seq_item_p].nr_seq_ordem_apresent,
               agenda_block_w[nr_seq_item_p].nr_seq_ordem,
               agenda_block_w[nr_seq_item_p].nr_minuto_duracao,
               agenda_block_w[nr_seq_item_p].ie_tipo_item,
               agenda_block_w[nr_seq_item_p].ie_lado,
               agenda_block_w[nr_seq_item_p].ie_tipo_agendamento,
               agenda_block_w[nr_seq_item_p].cd_procedimento,
               agenda_block_w[nr_seq_item_p].ie_origem_proced,
               agenda_block_w[nr_seq_item_p].ie_anestesia,
               agenda_block_w[nr_seq_item_p].nr_seq_combo,
               agenda_block_w[nr_seq_item_p].nr_seq_area_atuacao,
               agenda_block_w[nr_seq_item_p].cd_medico,
               agenda_block_w[nr_seq_item_p].nr_seq_grupo_selec,
               agenda_block_w[nr_seq_item_p].ie_genero_prof,
               agenda_block_w[nr_seq_item_p].nr_seq_agrup_setor,
               agenda_block_w[nr_seq_item_p].nr_seq_agrupamento,
               agenda_block_w[nr_seq_item_p].cd_especialidade,
               agenda_block_w[nr_seq_item_p].ie_classif_agenda,
               agenda_block_w[nr_seq_item_p].nr_seq_classif_agenda,
               agenda_block_w[nr_seq_item_p].nr_classificacao_agend,
               agenda_block_w[nr_seq_item_p].cd_anestesista,
               agenda_block_w[nr_seq_item_p].nr_seq_item_princ,
               agenda_block_w[nr_seq_item_p].ie_exame_princ,
               agenda_block_w[nr_seq_item_p].nr_seq_agenda_cons,
               agenda_block_w[nr_seq_item_p].nr_seq_agenda_exame,
               agenda_block_w[nr_seq_item_p].ds_status_agendamento,
               agenda_block_w[nr_seq_item_p].ds_item_grid_ageint,
               agenda_block_w[nr_seq_item_p].ie_rodizio_especialidade,
               agenda_block_w[nr_seq_item_p].nr_seq_regra
          FROM agenda_integrada_item b
         WHERE b.nr_sequencia = nr_seq_item_p;
	end;
		
  begin

	FOR c01_w IN (SELECT nr_sequencia               
                    FROM agenda_integrada_item 
                    WHERE nr_seq_agenda_int = nr_seq_ageint_p
                     AND (current_setting('smart_schedule_data_process.ie_transferencia_w')::varchar(1) = 'N' AND ageint_obter_status_item(nr_seq_agenda_int, nr_sequencia, 'C') IN ('L', 'LF'))
                     AND ie_tipo_agendamento <> 'Q'
                     AND coalesce(nr_seq_item_princ::text, '') = '' 
                  ) LOOP
  
		if c01_w.nr_sequencia > 0 then
			if not(current_setting('smart_schedule_data_process.agenda_item_w')::agenda_item_table.exists(c01_w.nr_sequencia)) THEN
				CALL smart_schedule_data_process.add_item_block(c01_w.nr_sequencia);
				RETURN;
			END IF;
		end if;
	end loop;
  end;


$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE smart_schedule_data_process.add_item_block (nr_seq_item_p bigint) FROM PUBLIC;
