-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';

CREATE OR REPLACE VIEW eis_laudo_patologia_v (qt1, ds_exame, cd_setor_atendimento, ds_setor_atendimento, cd_pessoa_fisica, nm_paciente, cd_medico, nm_medico, cd_convenio, ds_convenio, ie_tipo_atendimento, ds_tipo_atendimento, ie_clinica, ds_clinica, cd_topografia, ds_topografia, cd_morfologia, ds_morfologia, dt_referencia, dt_entrada, nr_atendimento, nr_seq_exame, ds_exame_lab, nr_seq_morf_desc_adic) AS select  count(*) qt1,
	b.nr_exame ds_exame,
	a.cd_setor_atendimento cd_setor_atendimento,
	substr(obter_nome_setor(a.cd_setor_atendimento),1,255) ds_setor_atendimento,
	a.cd_pessoa_fisica cd_pessoa_fisica,
	substr(obter_nome_pf(a.cd_pessoa_fisica),1,255) nm_paciente,
	a.cd_medico,
	substr(obter_nome_pf(a.cd_medico),1,255) nm_medico,
	e.cd_convenio,
	substr(obter_nome_convenio(e.cd_convenio),1,255) ds_convenio,
	d.ie_tipo_atendimento,
	SUBSTR(OBTER_VALOR_DOMINIO(12, d.ie_tipo_atendimento),1,30) DS_TIPO_ATENDIMENTO,
	d.IE_CLINICA,
	SUBSTR(OBTER_VALOR_DOMINIO(17, d.ie_clinica),1, 30) DS_CLINICA,
	c.cd_topografia,
	SUBSTR(c.cd_topografia || CASE WHEN c.cd_topografia IS NULL THEN  null  ELSE ' - ' END  || OBTER_DESC_CIDO_TOPOGRAFIA(c.cd_topografia),1, 50) ds_topografia,
	c.cd_morfologia,
	SUBSTR(c.cd_morfologia || CASE WHEN c.cd_morfologia IS NULL THEN  null  ELSE ' - ' END  || OBTER_DESC_MORFOLOGIA(c.cd_morfologia,c.NR_SEQ_MORF_DESC_ADIC),1, 50) ds_morfologia,
	trunc(b.dt_entrada_unidade) dt_referencia,
	d.dt_entrada,
	d.nr_atendimento,
	e.nr_seq_exame,
	substr(obter_desc_exame(e.nr_seq_exame),1,60) ds_exame_lab,
  c.NR_SEQ_MORF_DESC_ADIC
FROM 	prescr_medica a,
	laudo_paciente b,
	prescr_proc_peca c,
	procedimento_paciente e,
	atendimento_paciente d
where	a.nr_prescricao		= b.nr_prescricao
and	a.nr_atendimento	= d.nr_atendimento
and	b.nr_seq_proc		= e.nr_sequencia
and	c.nr_seq_laudo		= b.nr_sequencia
group by c.cd_morfologia,
	b.nr_exame,
	a.cd_setor_atendimento,
	a.cd_pessoa_fisica,
	a.cd_medico, 
	e.cd_convenio, 
	d.ie_tipo_atendimento,
	d.ie_clinica,
	c.cd_topografia, 
	c.cd_morfologia, 
	trunc(b.dt_entrada_unidade),
	d.dt_entrada,
	d.nr_atendimento,
	e.nr_seq_exame,
	substr(obter_desc_exame(e.nr_seq_exame),1,60),
  c.NR_SEQ_MORF_DESC_ADIC,
  SUBSTR(c.cd_morfologia || CASE WHEN c.cd_morfologia IS NULL THEN  null  ELSE ' - ' END  || OBTER_DESC_MORFOLOGIA(c.cd_morfologia,c.NR_SEQ_MORF_DESC_ADIC),1, 50);

