-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';

CREATE OR REPLACE VIEW fis_tipo_relacion_cfdi_v (nr_folio, uuid, tipo_relacion, nr_sequencia) AS SELECT	c.nr_nota_fiscal nr_folio, c.nr_nfe_imp uuid, '07' tipo_relacion, a.nr_sequencia nr_sequencia
FROM	nota_fiscal a,
	operacao_nota b,
	nota_fiscal c
WHERE	a.cd_operacao_nf = b.cd_operacao_nf
AND	a.nr_sequencia_ref = c.nr_sequencia
AND	c.nr_nfe_imp is not null

UNION

SELECT	c.nr_nota_fiscal nr_folio, c.nr_nfe_imp uuid, '07' tipo_relacion, nr_seq_nf_Saida nr_sequencia
FROM 	titulo_receber a,
	titulo_receber_liq b,
	nota_fiscal c
WHERE	a.nr_titulo = b.nr_titulo
AND	c.nr_seq_adiantamento = b.nr_adiantamento
AND	c.nr_nfe_imp is not null
AND	EXISTS (SELECT *
		FROM	operacao_nota x
		WHERE	x.cd_operacao_nf = c.cd_operacao_nf
		AND	x.ie_nota_credito <> 'S')

UNION

SELECT	x.nr_nota_fiscal nr_folio, x.nr_nfe_imp uuid, '04' tipo_relacion, n.nr_sequencia
FROM	nota_fiscal x,
	nota_fiscal n
WHERE	x.nr_sequencia = nf_canc_origem_conta(n.nr_sequencia)
AND	NOT EXISTS (	SELECT	1
			FROM	nf_credito
			WHERE	nr_seq_nf_gerada = n.nr_sequencia
			
UNION

			SELECT	1
			FROM	nota_fiscal x,
				nota_fiscal a,
				conta_paciente_transf c
			WHERE	a.nr_sequencia = n.nr_sequencia
			and	x.nr_nfe_imp is not null
			and	obter_se_nota_entrada_saida(x.nr_sequencia,'N') = 'S'
			and	a.nr_interno_conta = c.nr_conta_atual
			and	x.nr_interno_conta = c.nr_seq_conta_origem
			and	x.ie_situacao <> '2')									   

union

select	(	select	x.nr_nota_fiscal
		from	nota_fiscal x
		where	nr_sequencia = (select	nr_seq_nf_ref
			from	nota_fiscal z
			where	z.nr_sequencia = a.nr_sequencia )) nr_folio,
(	select	nr_nfe_imp
		from	nota_fiscal x
		where	nr_sequencia = (select	nr_seq_nf_ref
			from	nota_fiscal z
			where	z.nr_sequencia = a.nr_sequencia )) uuid,
			'07' tipo_relacion,
			a.nr_sequencia nr_sequencia
from	nota_fiscal a
where	obter_se_nota_entrada_saida(a.nr_sequencia,'N') = 'S'
and	(select nr_nfe_imp
	from	nota_fiscal x
	where	nr_sequencia = (select	nr_seq_nf_ref
from	nota_fiscal z
where	z.nr_sequencia = a.nr_sequencia )) is not null

union
		
SELECT	x.nr_nota_fiscal nr_folio, x.nr_nfe_imp uuid, '04' tipo_relacion, n.nr_sequencia nr_sequencia
FROM	nota_fiscal x,
	nota_fiscal n,
	conta_paciente_transf c
WHERE	x.nr_nfe_imp is not null
and	obter_se_nota_entrada_saida(x.nr_sequencia,'N') = 'S'
and	n.nr_interno_conta = c.nr_conta_atual
and	x.nr_interno_conta = c.nr_seq_conta_origem
and	x.ie_situacao <> '2'
and	c.dt_atualizacao = (	select	min(c.dt_atualizacao) 
				from	conta_paciente_transf c,
					nota_fiscal x,
					nota_fiscal a
				WHERE	a.nr_sequencia = n.nr_sequencia
				and	x.nr_nfe_imp is not null
				and	obter_se_nota_entrada_saida(x.nr_sequencia,'N') = 'S'
				and	a.nr_interno_conta = c.nr_conta_atual
				and	x.nr_interno_conta = c.nr_seq_conta_origem
				and	x.ie_situacao <> '2')
AND	EXISTS (	SELECT *
			FROM	operacao_nota o
			WHERE	x.cd_operacao_nf = o.cd_operacao_nf
			AND	o.ie_nota_credito <> 'S')
AND	NOT EXISTS (	SELECT	1
			FROM	nf_credito
	WHERE	nr_seq_nf_gerada = n.nr_sequencia )

union

SELECT	x.nr_nota_fiscal nr_folio, x.nr_nfe_imp uuid, '04' tipo_relacion, n.nr_sequencia nr_sequencia
FROM	nota_fiscal x,
	nota_fiscal n
WHERE	x.nr_sequencia = nf_trans_origem_conta(n.nr_sequencia)
AND	NOT EXISTS (	SELECT 1
			FROM	titulo_receber a,
				titulo_receber_liq b,
				nota_fiscal c
			WHERE	nr_seq_nf_Saida = n.nr_sequencia
			AND	a.nr_titulo = b.nr_titulo
			AND	c.nr_seq_adiantamento = b.nr_adiantamento
			AND	EXISTS (SELECT * 
					FROM	operacao_nota x
					WHERE	x.cd_operacao_nf = c.cd_operacao_nf
					AND	x.ie_nota_credito <> 'S')
			
UNION

			select	1
			from	nota_fiscal a
			where	a.nr_sequencia = n.nr_sequencia
			and	obter_se_nota_entrada_saida(n.nr_sequencia,'N') = 'S'
			and	(	select	nr_nfe_imp
					from	nota_fiscal x
					where	nr_sequencia = (select	nr_seq_nf_ref
								from	nota_fiscal z
								where	z.nr_sequencia = n.nr_sequencia )) is not null
			
UNION

			select	1			
			from	uuid_nota_adiant_cred_v v
			where	v.seq = n.nr_sequencia )

union

select	obter_dados_nota_fiscal(v.seqOrigem,0) nr_folio, v.uuid uuid, '07' tipo_relacion, v.seq nr_sequencia
from	uuid_nota_adiant_cred_v v

union
	
select	n.nr_nota_fiscal nr_folio, n.nr_nfe_imp uuid, '04' tipo_relacion, f.nr_seq_nota nr_sequencia
from 	fis_tipo_relacao f,
		nota_fiscal n
where	n.nr_sequencia = f.nr_seq_nota_relacao
and		f.nr_seq_nota_relacao is not null
and		n.nr_nfe_imp is not null
and     f.cd_tipo_relacao = '04';

