-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';

CREATE OR REPLACE VIEW pfcs_icu_v (ds_unit, ds_unit_classification, cd_unit_classification, cd_department, pr_capacity, ds_census, qt_avail_beds, qt_blocked_beds, qt_admission_orders, qt_special_request, qt_avg_waiting, qt_transf_order, qt_delays, qt_dis_orders, qt_exp_discharges, qt_discharges, qt_trans_review, qt_pred_vent, qt_exp_transfers_in, qt_exp_transfers_out, qt_admissions, qt_exp_admissions, cd_estabelecimento, pr_capacity_color, qt_avail_beds_color, qt_blocked_beds_color, qt_admission_orders_color, qt_special_request_color, qt_avg_waiting_color, qt_transf_order_color, qt_delays_color, qt_dis_orders_color, qt_exp_discharges_color, qt_discharges_color, qt_exp_transfers_in_color, qt_exp_transfers_out_color, qt_exp_admissions_color, qt_admissions_color) AS select v.DS_UNIT,
    v.DS_UNIT_CLASSIFICATION,
    v.CD_UNIT_CLASSIFICATION,
    v.CD_DEPARTMENT,
    CASE WHEN v.PR_CAPACITY IS NULL THEN null  ELSE v.PR_CAPACITY||'%' END  PR_CAPACITY,
    v.DS_CENSUS,
    v.QT_AVAIL_BEDS,
    v.QT_BLOCKED_BEDS,
    v.QT_ADMISSION_ORDERS,
    v.QT_SPECIAL_REQUEST,
    get_time_by_minutes(v.QT_AVG_WAITING) QT_AVG_WAITING,
    v.QT_TRANSF_ORDER,
    v.QT_DELAYS,
    v.QT_DIS_ORDERS,
    v.QT_EXP_DISCHARGES,
    v.QT_DISCHARGES,
    v.QT_TRANS_REVIEW,
    null QT_PRED_VENT,
    QT_EXP_TRANSFERS_IN,
    QT_EXP_TRANSFERS_OUT,
    (QT_EXP_ADMISSIONS+QT_ADMISSION_ORDERS) QT_ADMISSIONS,
    QT_EXP_ADMISSIONS,
    v.CD_ESTABELECIMENTO,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 90 WHEN v.cd_unit_classification='3' THEN 263 WHEN v.cd_unit_classification='SD' THEN 251 END ,v.PR_CAPACITY,v.cd_estabelecimento,'COLOR') PR_CAPACITY_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 92 WHEN v.cd_unit_classification='3' THEN 255 WHEN v.cd_unit_classification='SD' THEN 243 END ,v.QT_AVAIL_BEDS,v.cd_estabelecimento,'COLOR') QT_AVAIL_BEDS_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 93 WHEN v.cd_unit_classification='3' THEN 256 WHEN v.cd_unit_classification='SD' THEN 244 END ,v.QT_BLOCKED_BEDS,v.cd_estabelecimento,'COLOR') QT_BLOCKED_BEDS_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 94 WHEN v.cd_unit_classification='3' THEN 258 WHEN v.cd_unit_classification='SD' THEN 246 END ,v.QT_ADMISSION_ORDERS,v.cd_estabelecimento,'COLOR') QT_ADMISSION_ORDERS_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 95 WHEN v.cd_unit_classification='3' THEN 259 WHEN v.cd_unit_classification='SD' THEN 247 END ,v.QT_SPECIAL_REQUEST,v.cd_estabelecimento,'COLOR') QT_SPECIAL_REQUEST_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 96 WHEN v.cd_unit_classification='3' THEN 260 WHEN v.cd_unit_classification='SD' THEN 248 END ,v.QT_AVG_WAITING,v.cd_estabelecimento,'COLOR') QT_AVG_WAITING_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 97 WHEN v.cd_unit_classification='3' THEN 261 WHEN v.cd_unit_classification='SD' THEN 249 END ,v.QT_TRANSF_ORDER,v.cd_estabelecimento,'COLOR') QT_TRANSF_ORDER_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 98 WHEN v.cd_unit_classification='3' THEN 262 WHEN v.cd_unit_classification='SD' THEN 250 END ,v.QT_DELAYS,v.cd_estabelecimento,'COLOR') QT_DELAYS_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 300 WHEN v.cd_unit_classification='3' THEN 270 WHEN v.cd_unit_classification='SD' THEN 279 END ,v.QT_DIS_ORDERS,v.cd_estabelecimento,'COLOR') QT_DIS_ORDERS_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 299 WHEN v.cd_unit_classification='3' THEN 269 WHEN v.cd_unit_classification='SD' THEN 278 END ,v.QT_EXP_DISCHARGES,v.cd_estabelecimento,'COLOR') QT_EXP_DISCHARGES_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 298 WHEN v.cd_unit_classification='3' THEN 268 WHEN v.cd_unit_classification='SD' THEN 277 END ,v.QT_DISCHARGES,v.cd_estabelecimento,'COLOR') QT_DISCHARGES_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 296 WHEN v.cd_unit_classification='3' THEN 271 WHEN v.cd_unit_classification='SD' THEN 275 END ,v.QT_EXP_TRANSFERS_IN,v.cd_estabelecimento,'COLOR') QT_EXP_TRANSFERS_IN_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 297 WHEN v.cd_unit_classification='3' THEN 272 WHEN v.cd_unit_classification='SD' THEN 276 END ,v.QT_EXP_TRANSFERS_OUT,v.cd_estabelecimento,'COLOR') QT_EXP_TRANSFERS_OUT_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 295 WHEN v.cd_unit_classification='3' THEN 266 WHEN v.cd_unit_classification='SD' THEN 274 END ,QT_EXP_ADMISSIONS,v.cd_estabelecimento,'COLOR') QT_EXP_ADMISSIONS_COLOR,
    pfcs_get_indicator_rule(CASE WHEN v.cd_unit_classification='4' THEN 294 WHEN v.cd_unit_classification='3' THEN 267 WHEN v.cd_unit_classification='SD' THEN 273 END ,(QT_EXP_ADMISSIONS+QT_ADMISSION_ORDERS),v.cd_estabelecimento,'COLOR') QT_ADMISSIONS_COLOR
FROM (
    SELECT distinct p.ds_reference_value DS_UNIT,
        pfcs_get_ds_unit_classif(p.cd_reference_aux, wheb_usuario_pck.get_nr_seq_idioma, 'S') DS_UNIT_CLASSIFICATION,
        p.cd_reference_aux CD_UNIT_CLASSIFICATION,
        p.cd_reference_value CD_DEPARTMENT,
        pfcs_get_percentage_value(SUM(CASE WHEN p.nr_seq_indicator=100 THEN p.vl_indicator_help END ), SUM(CASE WHEN p.nr_seq_indicator=100 THEN p.vl_indicator END )) PR_CAPACITY,
        (SUM(CASE WHEN p.nr_seq_indicator=100 THEN p.vl_indicator_help END ) || '/' || SUM(CASE WHEN p.nr_seq_indicator=100 THEN p.vl_indicator END )) DS_CENSUS,
        SUM(CASE WHEN p.nr_seq_indicator=102 THEN p.vl_indicator  ELSE 0 END ) QT_AVAIL_BEDS,
        SUM(CASE WHEN p.nr_seq_indicator=111 THEN p.vl_indicator  ELSE 0 END ) QT_BLOCKED_BEDS,
        pfcs_pck_census.get_special_requests(
            p.nr_seq_operational_level,
            p.cd_reference_value) QT_SPECIAL_REQUEST,
        pfcs_get_avg_request_time(94,p.nr_seq_operational_level,p.cd_reference_value) QT_AVG_WAITING,
        SUM(CASE WHEN p.nr_seq_indicator=97 THEN p.vl_indicator  ELSE 0 END ) QT_TRANSF_ORDER,
        SUM(CASE WHEN p.nr_seq_indicator=98 THEN p.vl_indicator  ELSE 0 END ) QT_DELAYS,
        pfcs_pck_bed_requests.get_transfer_in(
            p.nr_seq_operational_level,
            null,
            cd_reference_value,
            'P') QT_EXP_TRANSFERS_IN,
        pfcs_pck_bed_requests.get_transfer_out(
            p.nr_seq_operational_level,
            null,
            cd_reference_value,
            'P') QT_EXP_TRANSFERS_OUT,
        SUM(CASE WHEN p.nr_seq_indicator=112 THEN p.vl_indicator  ELSE 0 END ) QT_DIS_ORDERS,
        pfcs_pck_discharge_manager.get_anticipated_discharges(
            p.nr_seq_operational_level,
            p.cd_reference_value,
            null,
            LOCALTIMESTAMP) QT_EXP_DISCHARGES,
        (SUM(CASE WHEN p.nr_seq_indicator=112 THEN p.vl_indicator  ELSE 0 END )
            + pfcs_pck_discharge_manager.get_anticipated_discharges(
                p.nr_seq_operational_level,
                p.cd_reference_value,
                null,
                LOCALTIMESTAMP,
                'N')
        ) QT_DISCHARGES,
        pfcs_pck_bed_requests.get_admission_orders(
            p.nr_seq_operational_level,
            null,
            p.cd_reference_value) QT_ADMISSION_ORDERS,
        pfcs_pck_bed_requests.get_expected_admissions(
            p.nr_seq_operational_level,
            null,
            p.cd_reference_value) QT_EXP_ADMISSIONS,
        null QT_TRANS_REVIEW,
        p.nr_seq_operational_level CD_ESTABELECIMENTO
    FROM pfcs_panel p
    WHERE p.nr_seq_indicator IN (100, 102, 111, 97, 98, 112)
        AND p.cd_reference_aux in ('3','4','SD')
    GROUP BY p.ds_reference_value, p.cd_reference_value, p.cd_reference_aux, p.nr_seq_operational_level
) v;

