-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';

CREATE OR REPLACE VIEW san_hcf_status_sangue_v (ie_situacao, nr_sangue, ds_derivado, ie_tipo_sangue, ie_fator_rh, ds_convenio, nr_guia, nr_atendimento, nm_paciente, ie_tratamento, nr_seq_reserva, nr_seq_derivado, nr_sequencia, nr_seq_emp_ent, nr_seq_emp_saida, nr_seq_inutil, nr_seq_transfusao, dt_movimento, dt_transfusao, dt_saida_estoque, dt_emprestimo) AS select	distinct
	a.IE_SITUACAO,a.NR_SANGUE,a.DS_DERIVADO,a.IE_TIPO_SANGUE,a.IE_FATOR_RH,a.DS_CONVENIO,a.NR_GUIA,a.NR_ATENDIMENTO,a.NM_PACIENTE,a.IE_TRATAMENTO,a.NR_SEQ_RESERVA,a.NR_SEQ_DERIVADO,a.NR_SEQUENCIA,a.NR_SEQ_EMP_ENT,a.NR_SEQ_EMP_SAIDA,a.NR_SEQ_INUTIL,a.NR_SEQ_TRANSFUSAO,a.DT_MOVIMENTO,a.DT_TRANSFUSAO,a.DT_SAIDA_ESTOQUE,a.DT_EMPRESTIMO 
FROM ( 
	select	'Transfundido' ie_situacao, 
    	a.nr_sangue, 
	    OBTER_DESC_SAN_DERIVADO(a.nr_seq_derivado) ds_derivado, 
	    a.ie_tipo_sangue, 
	    a.ie_fator_rh, 
	    obter_nome_convenio(obter_convenio_atendimento(b.nr_atendimento)) ds_convenio, 
	    null nr_guia, 
		b.nr_atendimento, 
		substr(obter_nome_pessoa_fisica(b.cd_pessoa_fisica,''),1,255) nm_paciente, 
		CASE WHEN a.ie_irradiado='S' THEN 'I'  ELSE '' END ||CASE WHEN a.ie_lavado='S' THEN 'L'  ELSE '' END  
		||CASE WHEN a.ie_filtrado='S' THEN 'F'  ELSE '' END ||CASE WHEN a.ie_aliquotado='S' THEN 'A'  ELSE '' END  ie_tratamento, 
		a.nr_seq_reserva, 
		a.nr_seq_derivado, 
		a.nr_sequencia, 
		a.nr_seq_emp_ent, 
		a.nr_seq_emp_saida, 
		a.nr_seq_inutil, 
		a.nr_seq_transfusao, 
		b.dt_transfusao dt_movimento, 
		b.dt_transfusao, 
		trunc(san_obter_data_saida_estoque(a.nr_sequencia, a.nr_seq_transfusao, null, null)) dt_saida_estoque, 
		c.dt_emprestimo 
	from	san_emprestimo c, 
		san_transfusao b, 
		san_producao a 
	where	nr_seq_transfusao 	= b.nr_sequencia 
	and	a.nr_seq_emp_ent	= c.nr_sequencia 
	
union
 
	select	'Inutilizado', 
		a.nr_sangue, 
		OBTER_DESC_SAN_DERIVADO(a.nr_seq_derivado) ds_derivado, 
		a.ie_tipo_sangue, 
		a.ie_fator_rh, 
		'', 
		'', 
		0, 
		'', 
		CASE WHEN a.ie_irradiado='S' THEN 'I'  ELSE '' END ||CASE WHEN a.ie_lavado='S' THEN 'L'  ELSE '' END  
		||CASE WHEN a.ie_filtrado='S' THEN 'F'  ELSE '' END ||CASE WHEN a.ie_aliquotado='S' THEN 'A'  ELSE '' END  ie_tratamento, 
		a.nr_seq_reserva, 
		a.nr_seq_derivado, 
		a.nr_sequencia, 
		a.nr_seq_emp_ent, 
		a.nr_seq_emp_saida, 
		a.nr_seq_inutil, 
		a.nr_seq_transfusao, 
		b.dt_inutilizacao dt_movimento, 
		b.dt_inutilizacao dt_transfusao, 
		trunc(san_obter_data_saida_estoque(a.nr_sequencia, a.nr_seq_transfusao, a.nr_seq_emp_saida, a.nr_seq_inutil)) dt_saida_estoque, 
		x.dt_emprestimo dt_emprestimo 
	from	san_emprestimo x, 
		san_motivo_inutil c, 
		san_inutilizacao b, 
		san_producao a 
	where	a.nr_seq_inutil 	= b.nr_sequencia 
	and	b.nr_seq_motivo_inutil 	= c.nr_sequencia 
	and	x.nr_sequencia		= a.nr_seq_emp_ent 
	
union
 
	select	'Emprestado', 
		a.nr_sangue, 
		OBTER_DESC_SAN_DERIVADO(a.nr_seq_derivado) ds_derivado, 
		a.ie_tipo_sangue, 
		a.ie_fator_rh, 
		'', 
		'', 
		0, 
		'', 
		CASE WHEN a.ie_irradiado='S' THEN 'I'  ELSE '' END ||CASE WHEN a.ie_lavado='S' THEN 'L'  ELSE '' END  
		||CASE WHEN a.ie_filtrado='S' THEN 'F'  ELSE '' END ||CASE WHEN a.ie_aliquotado='S' THEN 'A'  ELSE '' END  ie_tratamento, 
		a.nr_seq_reserva, 
		a.nr_seq_derivado, 
		a.nr_sequencia, 
		a.nr_seq_emp_ent, 
		a.nr_seq_emp_saida, 
		a.nr_seq_inutil, 
		a.nr_seq_transfusao, 
		b.dt_emprestimo dt_movimento, 
		null dt_transfusao, 
		trunc(san_obter_data_saida_estoque(a.nr_sequencia, a.nr_seq_transfusao, a.nr_seq_emp_saida, a.nr_seq_inutil)) dt_saida_estoque, 
		null dt_emprestimo 
	from	san_entidade c, 
		san_emprestimo b, 
		san_producao a 
	where	a.nr_seq_emp_saida 	= b.nr_sequencia 
	and	b.nr_seq_entidade 	= c.nr_sequencia 
			  ) a;

