-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';


--Removes all non-searchable characters (like $@) from a string, replaces it by white space.
CREATE OR REPLACE FUNCTION tasyautocomplete.removespecialcharacters (text text) RETURNS varchar AS $body$
BEGIN
RETURN regexp_replace(text, '[^[:alnum:].'']', ' ');
END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 IMMUTABLE;
-- REVOKE ALL ON FUNCTION tasyautocomplete.removespecialcharacters (text text) FROM PUBLIC;
