-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE ageint_remover_turnos_medico (NR_SEQ_MEDICO_REGRA_P bigint, CD_AGENDA_P bigint, CD_MEDICO_P text) AS $body$
BEGIN

delete
from	ageint_turno_medico
where	cd_pessoa_fisica = cd_medico_p
and (nr_seq_medico_regra = nr_seq_medico_regra_p or coalesce(nr_seq_medico_regra::text, '') = '')
and (cd_agenda = cd_agenda_p or coalesce(cd_agenda::text, '') = '')
and (cd_estabelecimento = wheb_usuario_pck.get_cd_estabelecimento or coalesce(cd_estabelecimento::text, '') = '');

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE ageint_remover_turnos_medico (NR_SEQ_MEDICO_REGRA_P bigint, CD_AGENDA_P bigint, CD_MEDICO_P text) FROM PUBLIC;

