-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE ajustar_data_entrega_maior (nr_prescricao_p bigint, nm_usuario_p text) AS $body$
DECLARE


dt_entrega_w			timestamp;
dt_entrega_old_w		timestamp;
nr_seq_forma_laudo_w		bigint;
qt_hora_adicional_w		bigint;
qt_hora_adicional_fer_w 	bigint;
cd_estabelecimento_w		smallint;
nr_atendimento_w		bigint;
ie_regra_ajuste_data_w		varchar(1);
nr_sequencia_w			bigint;
nr_sequencia_old_w		bigint;
ie_novo_dia_regra_se_feriado_W	varchar(1);
rownum_w			bigint;
dt_prescricao_w			timestamp;
ie_dia_semana_entrega_w		regra_ajuste_data_entrega.ie_dia_semana%type;


BEGIN
--select 	max(nvl(dt_resultadoado,dt_prev_execucao))
select 	coalesce(max(nr_seq_forma_laudo),0),
	coalesce(max(cd_estabelecimento),0),
	coalesce(max(nr_atendimento),0),
	max(dt_prescricao)
into STRICT	nr_seq_forma_laudo_w,
	cd_estabelecimento_w,
	nr_atendimento_w,
	dt_prescricao_w
from	prescr_medica
where	nr_prescricao = nr_prescricao_p;

if (cd_estabelecimento_w = 0) and (nr_atendimento_w > 0) then
	select 	max(coalesce(cd_estabelecimento,0))
	into STRICT	cd_estabelecimento_w
	from 	atendimento_paciente
	where 	nr_atendimento = nr_atendimento_w;
end if;

select	max(dt_resultado)
into STRICT	dt_entrega_w
from	prescr_procedimento
where	nr_prescricao = nr_prescricao_p;

ie_novo_dia_regra_se_feriado_w := 'S';

dt_entrega_old_w 	:= dt_entrega_w;

ie_regra_ajuste_data_w 	:= 'S';
nr_sequencia_old_w	:= 0;
rownum_w			:= 0;
while(ie_regra_ajuste_data_w = 'S') loop

	rownum_w := rownum_w + 1;
	
	ie_dia_semana_entrega_w := obter_cod_dia_semana(dt_entrega_w);

	select 	max(qt_hora_adicional),
		max(coalesce(qt_hora_adicional_feriado,0)),
		max(nr_sequencia)
	into STRICT	qt_hora_adicional_w,
		qt_hora_adicional_fer_w,
		nr_sequencia_w
	from	regra_ajuste_data_entrega
	where	nr_seq_forma_entrega = nr_seq_forma_laudo_w
	and	(((ie_dia_semana = 9) and (ie_dia_semana_entrega_w not in (7,1))) or (ie_dia_semana = ie_dia_semana_entrega_w));

	If (nr_sequencia_w IS NOT NULL AND nr_sequencia_w::text <> '') and (nr_sequencia_w <> nr_sequencia_old_w) then
	
		If (qt_hora_adicional_w IS NOT NULL AND qt_hora_adicional_w::text <> '') Or
			((qt_hora_adicional_fer_w > 0) and (obter_se_feriado(cd_estabelecimento_w,dt_entrega_w) = 1)) then
			
			If (qt_hora_adicional_w IS NOT NULL AND qt_hora_adicional_w::text <> '') then
				dt_entrega_w := dt_entrega_w + qt_hora_adicional_w / 24;
			End if;

			If (qt_hora_adicional_fer_w > 0) and (obter_se_feriado(cd_estabelecimento_w, dt_entrega_w) = 1) then
				dt_entrega_w := dt_entrega_w + qt_hora_adicional_fer_w / 24;
			End if;
			
			If (obter_cod_dia_semana(dt_entrega_w) <> coalesce(obter_cod_dia_semana(dt_entrega_old_w),0)) And
				((ie_novo_dia_regra_se_feriado_w = 'N') or
				((ie_novo_dia_regra_se_feriado_w = 'S') and (obter_se_dia_util(ESTABLISHMENT_TIMEZONE_UTILS.startOfDay(dt_entrega_w),cd_estabelecimento_w) = 'N')))  then
				dt_entrega_old_w   := dt_entrega_w;
				nr_sequencia_old_w := nr_sequencia_w;
			Else						
				ie_regra_ajuste_data_w := 'N';
			End if;
		Else	
			ie_regra_ajuste_data_w := 'N';
		End if;
	Else
		ie_regra_ajuste_data_w := 'N';
	End if;
	
	if (rownum_w = 10) then
		exit;
	end if;
	
End loop;

if (dt_entrega_w IS NOT NULL AND dt_entrega_w::text <> '')and (dt_entrega_w >= dt_prescricao_w)then
	update 	prescr_medica
	set	dt_entrega = dt_entrega_w
	where	nr_prescricao = nr_prescricao_p;	
end if;

if (coalesce(wheb_usuario_pck.get_ie_commit, 'S') = 'S') then
	commit;
end if;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE ajustar_data_entrega_maior (nr_prescricao_p bigint, nm_usuario_p text) FROM PUBLIC;

