-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE atualizar_pontuacao_sepse ( nr_atendimento_p bigint, nr_seq_escala_p bigint, nr_seq_atributo_p bigint, nm_usuario_p text, ie_tipo_sepse_p text default 'A') AS $body$
DECLARE


qt_pontuacao_w			bigint := 0;
qt_reg_w				bigint;
qt_valor_w				double precision;
ie_atributo_w			varchar(60) := '';
ie_regra_w				varchar(1);
ie_nivel_consciencia_w	varchar(15);
qt_pont_w				bigint;
cd_setor_atendimento_w  integer;
cd_classif_setor_w		varchar(2);
qt_regra_HP_w			bigint;
qt_regra_FC_w			bigint;
qt_regra_discrasia_w		bigint;
qt_regra_edema_w		bigint;
ie_versao_sepse_w   varchar(10);
qt_saturacao_o2_w	bigint;
qt_hora_sv_w		smallint;
ie_alteracao_manual_w	varchar(1);
qt_nivel_cons_w			bigint := 0;



BEGIN

SELECT * FROM obter_dados_escala_sepse(nr_atendimento_p, nr_seq_atributo_p, nm_usuario_p, ie_tipo_sepse_p) INTO STRICT qt_valor_w, ie_regra_w, qt_pont_w, ie_atributo_w;

select	count(*)
into STRICT	qt_reg_w
from	sepse_atributo_cliente
where	nr_seq_atributo = nr_seq_atributo_p;	

if (qt_reg_w > 0) and (ie_regra_w = 'S') then

	select	max(qt_pontuacao)
	into STRICT	qt_pontuacao_w
	from	sepse_atributo_cliente b
	where	b.nr_seq_atributo = nr_seq_atributo_p
	and		qt_valor_w between coalesce(qt_valor_min,0) and coalesce(qt_valor_max,99999);
end if;

select coalesce(max(ie_versao_sepse),'1')
into STRICT   ie_versao_sepse_w
from   parametro_medico
where  cd_estabelecimento = coalesce(obter_dados_atendimento(nr_atendimento_p,'EST'), obter_estabelecimento_ativo);


if	((ie_tipo_sepse_p = 'P') and (nr_seq_atributo_p in (83,84,85,87,89,90,80))) or
	((ie_versao_sepse_w = '1') and (nr_seq_atributo_p in (4,5,6,7,8,11,17,18,19,30,31,32,33))) or (ie_versao_sepse_w = '2' and (nr_seq_atributo_p in (47,48,49,50,51,59,60,61,41,42,95))) then

	Select 	Obter_Setor_Atendimento(nr_atendimento_p)
	into STRICT	cd_setor_atendimento_w
	;
	
	if (coalesce(cd_setor_atendimento_w,0) > 0 ) then
	
		Select  max(cd_classif_setor)
		into STRICT	cd_classif_setor_w
		from	SETOR_ATENDIMENTO
		where	cd_setor_atendimento = cd_setor_atendimento_w;
		
		if ( coalesce(cd_classif_setor_w,'0') = '2') then
			qt_pont_w := 0;
			if (ie_tipo_sepse_p = 'P') then
				qt_valor_w := null;
			else
				qt_valor_w := 0;
			end if;					
		
		end if;
	
	end if;

end if;
if (ie_tipo_sepse_p = 'P') then
	
	if (nr_seq_atributo_p = 87) then --Mudanca aguda do estado neurologico
		begin
		select coalesce(max(qt_hora_sv),24)
		into STRICT qt_hora_sv_w
		from SEPSE_ATRIBUTO_REGRA
		where NR_SEQ_ATRIBUTO = nr_seq_atributo_p;

		select 	count(*)
		into STRICT 	qt_nivel_cons_w
		from	atendimento_sinal_vital
		where	nr_atendimento = nr_atendimento_p
		and 	(IE_NIVEL_CONSCIENCIA_PED IS NOT NULL AND IE_NIVEL_CONSCIENCIA_PED::text <> '')
		and 	ie_situacao = 'A'
		and 	(dt_atualizacao + (qt_hora_sv_w/24)) >= clock_timestamp();
		
		if (qt_nivel_cons_w = 0) then
			ie_atributo_w := null;
			qt_valor_w := null;
		else
			select 	max(substr(obter_valor_dominio(8921,ie_nivel),1,60)),
					(max(ie_nivel))::numeric 
			into STRICT  	ie_atributo_w,
					qt_valor_w
			from 	(	SELECT IE_NIVEL_CONSCIENCIA_PED ie_nivel
						from	atendimento_sinal_vital
						where	nr_atendimento = nr_atendimento_p
						and 	ie_situacao = 'A'
						and (IE_NIVEL_CONSCIENCIA_PED IS NOT NULL AND IE_NIVEL_CONSCIENCIA_PED::text <> '')
						and 	(dt_atualizacao + (qt_hora_sv_w/24)) >= clock_timestamp()
						order by NR_SEQUENCIA desc) alias9 where 
			group by ie_nivel LIMIT 1;
		end if;
		end;
	end if;
	
	select ie_alteracao_manual
	into STRICT ie_alteracao_manual_w
	from escala_sepse_infantil
	where nr_sequencia = nr_seq_escala_p;

	if (ie_alteracao_manual_w <> 'S' or coalesce(ie_alteracao_manual_w::text, '') = '') then
		update	escala_sepse_infantil_item
		set	qt_pontuacao = coalesce(qt_pont_w,coalesce(qt_pontuacao_w,0)),
			vl_atributo = qt_valor_w,
			ie_atributo = ie_atributo_w,
			ie_resultado = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END ,
			ie_resultado_orig = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END
		where	nr_seq_escala = nr_seq_escala_p
		and	nr_seq_atributo = nr_seq_atributo_p;		
	end if;
	
else
	if (nr_seq_atributo_p in (8,51)) then

		if (coalesce(ie_atributo_w::text, '') = '') or (ie_atributo_w = '') then
			select	max(substr(obter_valor_dominio(3342,ie_nivel_consciencia),1,60)),
					max(ie_nivel_consciencia)
			into STRICT	ie_atributo_w,
					ie_nivel_consciencia_w
			from	atendimento_sinal_vital
			where	nr_atendimento = nr_atendimento_p;
		end if;
		
		update	escala_sepse_item
		set		qt_pontuacao = coalesce(qt_pont_w,coalesce(qt_pontuacao_w,0)),
				ie_atributo = ie_atributo_w,
				vl_atributo = (ie_nivel_consciencia_w)::numeric ,
				ie_resultado = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END ,
				ie_resultado_orig = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END
		where	nr_seq_escala = nr_seq_escala_p
		and		nr_seq_atributo = nr_seq_atributo_p;
	
--elsif	(nr_seq_atributo_p in (9,22,26)) thena
	else

		if (nr_seq_atributo_p in (17,30,31,32, 59,41,42))then
			
				update	escala_sepse_item
				set	qt_pontuacao = coalesce(qt_pont_w,coalesce(qt_pontuacao_w,0)),
					vl_atributo = qt_valor_w,
					ie_resultado = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END ,
					ie_resultado_orig = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END
				where	nr_seq_escala = nr_seq_escala_p
				and	nr_seq_atributo = nr_seq_atributo_p;

		elsif (nr_seq_atributo_p in (6,33,49))then
		
			Select  coalesce(sum(qt_pontuacao),0)
			into STRICT	qt_regra_FC_w
			from	escala_sepse_item
			where	nr_seq_escala = nr_seq_escala_p
			and	nr_seq_atributo in (6,33);
			
			if ( qt_regra_FC_w = 0) then
			
				update	escala_sepse_item
				set	qt_pontuacao = coalesce(qt_pont_w,coalesce(qt_pontuacao_w,0)),
					vl_atributo = qt_valor_w,
					ie_resultado = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END ,
					ie_resultado_orig = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END
				where	nr_seq_escala = nr_seq_escala_p
				and	nr_seq_atributo = nr_seq_atributo_p;
			
			end if;
			
		elsif (nr_seq_atributo_p in (21,34))then
		
			Select  coalesce(sum(qt_pontuacao),0)
			into STRICT	qt_regra_discrasia_w
			from	escala_sepse_item
			where	nr_seq_escala = nr_seq_escala_p
			and	nr_seq_atributo in (21,34);
			
			if ( qt_regra_discrasia_w = 0) then
			
				update	escala_sepse_item
				set	qt_pontuacao = coalesce(qt_pont_w,coalesce(qt_pontuacao_w,0)),
					vl_atributo = qt_valor_w,
					ie_resultado = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END ,
					ie_resultado_orig = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END
				where	nr_seq_escala = nr_seq_escala_p
				and	nr_seq_atributo = nr_seq_atributo_p;
			
			end if;
			
		elsif (nr_seq_atributo_p in (9,35))then
		
			Select  coalesce(sum(qt_pontuacao),0)
			into STRICT	qt_regra_edema_w
			from	escala_sepse_item
			where	nr_seq_escala = nr_seq_escala_p
			and	nr_seq_atributo in (9,35);
			
			if ( qt_regra_edema_w = 0) then
			
				update	escala_sepse_item
				set	qt_pontuacao = coalesce(qt_pont_w,coalesce(qt_pontuacao_w,0)),
					vl_atributo = qt_valor_w,
					ie_resultado = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END ,
					ie_resultado_orig = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END
				where	nr_seq_escala = nr_seq_escala_p
				and	nr_seq_atributo = nr_seq_atributo_p;
			
			end if;		
	
		else
		
			update	escala_sepse_item
			set	qt_pontuacao = coalesce(qt_pont_w,coalesce(qt_pontuacao_w,0)),
				vl_atributo = qt_valor_w,
				ie_resultado = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END ,
				ie_resultado_orig = CASE WHEN coalesce(qt_pont_w,0)=0 THEN 'N'  ELSE 'S' END
			where	nr_seq_escala = nr_seq_escala_p
			and	nr_seq_atributo = nr_seq_atributo_p;
		end if;
	end if;

end if;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE atualizar_pontuacao_sepse ( nr_atendimento_p bigint, nr_seq_escala_p bigint, nr_seq_atributo_p bigint, nm_usuario_p text, ie_tipo_sepse_p text default 'A') FROM PUBLIC;

