-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE atualizar_repasse_cheque_venc ( cd_estabelecimento_p bigint, nm_usuario_p text) AS $body$
DECLARE


nr_interno_conta_w	bigint;
vl_saldo_titulo_w		double precision;
dt_vencimento_w		timestamp;

c01 CURSOR FOR
SELECT	b.nr_interno_conta,
	c.vl_saldo_titulo,
	trunc(coalesce(e.dt_vencimento_atual, e.dt_vencimento),'dd')
from	convenio d,
	procedimento_paciente b,
	procedimento_repasse a,
	titulo_receber c,
	cheque_cr e
where	coalesce(a.nr_repasse_terceiro::text, '') = ''
and	a.nr_seq_procedimento			= b.nr_sequencia
and	coalesce(b.cd_motivo_exc_conta::text, '') = ''
and	b.nr_interno_conta				= c.nr_interno_conta
and	b.cd_convenio				= d.cd_convenio
and	d.ie_tipo_convenio				= 1
and	c.cd_estabelecimento			= cd_estabelecimento_p
and	c.nr_titulo				= e.nr_titulo
and	a.ie_status				in ('A','U','D')
and	coalesce(e.dt_devolucao::text, '') = ''
and	coalesce(e.dt_seg_devolucao::text, '') = ''
and	(coalesce(e.dt_vencimento_atual, e.dt_vencimento) IS NOT NULL AND (coalesce(e.dt_vencimento_atual, e.dt_vencimento))::text <> '')

union

select	b.nr_interno_conta,
	c.vl_saldo_titulo,
	trunc(coalesce(e.dt_vencimento_atual, e.dt_vencimento),'dd')
from	convenio d,
	material_atend_paciente b,
	material_repasse a,
	titulo_receber c,
	cheque_cr e
where	coalesce(a.nr_repasse_terceiro::text, '') = ''
and	a.nr_seq_material				= b.nr_sequencia
and	coalesce(b.cd_motivo_exc_conta::text, '') = ''
and	b.nr_interno_conta				= c.nr_interno_conta
and	b.cd_convenio				= d.cd_convenio
and	d.ie_tipo_convenio				= 1
and	c.cd_estabelecimento			= cd_estabelecimento_p
and	c.nr_titulo				= e.nr_titulo
and	a.ie_status				in ('A','U','D')
and	coalesce(e.dt_devolucao::text, '') = ''
and	coalesce(e.dt_seg_devolucao::text, '') = ''
and	(coalesce(e.dt_vencimento_atual, e.dt_vencimento) IS NOT NULL AND (coalesce(e.dt_vencimento_atual, e.dt_vencimento))::text <> '');


BEGIN

open c01;
loop
fetch c01 into
	nr_interno_conta_w,
	vl_saldo_titulo_w,
	dt_vencimento_w;
EXIT WHEN NOT FOUND; /* apply on c01 */

	if (dt_vencimento_w < clock_timestamp()) then
		CALL Atualizar_Repasse_Conta(nr_interno_conta_w, vl_saldo_titulo_w, nm_usuario_p);
	end if;

end loop;
close c01;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE atualizar_repasse_cheque_venc ( cd_estabelecimento_p bigint, nm_usuario_p text) FROM PUBLIC;

