-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE atualiza_lista_espera_atrib ( NR_SEQ_ATRIB_ELEM_P bigint, NR_SEQUENCIA_P bigint) AS $body$
BEGIN
UPDATE	LISTA_ESPERA_ATRIBUTO
SET	NR_SEQ_ATRIB_ELEM = NR_SEQ_ATRIB_ELEM_P
WHERE	coalesce(NR_SEQ_ATRIB_ELEM::text, '') = ''
AND	NR_SEQUENCIA = NR_SEQUENCIA_P;

COMMIT;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE atualiza_lista_espera_atrib ( NR_SEQ_ATRIB_ELEM_P bigint, NR_SEQUENCIA_P bigint) FROM PUBLIC;

