-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE baixar_lote_prescr_pend_venc ( dt_parametro_p timestamp, qt_dias_prescr_p bigint default 5) AS $body$
BEGIN

update	ap_lote a
set	a.ie_status_lote		= 'C',
	a.dt_cancelamento		= clock_timestamp(),
	a.nm_usuario_cancelamento 	= 'JOB_BLPV_J'
where	a.ie_status_lote		= 'G'
and exists (	SELECT	1
		from	prescr_medica b
		where	b.nr_prescricao = a.nr_prescricao
		and	dt_prescricao > dt_parametro_p - qt_dias_prescr_p
		and	dt_validade_prescr < dt_parametro_p);

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE baixar_lote_prescr_pend_venc ( dt_parametro_p timestamp, qt_dias_prescr_p bigint default 5) FROM PUBLIC;

