-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE consistir_sessao_agenda ( nr_seq_agenda_p bigint, ds_msg_p INOUT text) AS $body$
DECLARE


qt_total_secao_w		smallint;
nr_secao_w		smallint;
nm_pessoa_fisica_w	pessoa_fisica.nm_pessoa_fisica%type;
ds_procedimento_w		procedimento.ds_procedimento%type;


BEGIN

if ((nr_seq_agenda_p IS NOT NULL AND nr_seq_agenda_p::text <> '') and
	nr_seq_agenda_p <> 0) then
	begin
	select	max(qt_total_secao),
		max(nr_secao)
	into STRICT	qt_total_secao_w,
		nr_secao_w
	from	agenda_consulta
	where	nr_sequencia	= nr_seq_agenda_p;

	if ((qt_total_secao_w IS NOT NULL AND qt_total_secao_w::text <> '') and
		(nr_secao_w IS NOT NULL AND nr_secao_w::text <> '') and
		qt_total_secao_w = nr_secao_w) then
		begin
		select	substr(obter_nome_pf(cd_pessoa_fisica), 1,60),
			substr(coalesce(obter_desc_proc_interno(nr_seq_proc_interno), obter_descricao_procedimento(cd_procedimento, ie_origem_proced)), 1,255)
		into STRICT	nm_pessoa_fisica_w,
			ds_procedimento_w
		from	agenda_consulta
		where	nr_sequencia	= nr_seq_agenda_p;

		ds_msg_p	:= substr(obter_texto_tasy(1056258, wheb_usuario_pck.get_nr_seq_idioma),1,255);
		ds_msg_p	:= replace_macro(ds_msg_p, '@NM_PACIENTE', nm_pessoa_fisica_w);
		ds_msg_p	:= replace_macro(ds_msg_p, '@DS_PROCEDIMENTO', ds_procedimento_w);

		end;
	end if;
	end;
end if;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE consistir_sessao_agenda ( nr_seq_agenda_p bigint, ds_msg_p INOUT text) FROM PUBLIC;

