-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE cpoe_vincular_agenda ( nr_seq_lista_p agenda_lista_espera.nr_sequencia%type, nr_seq_agenda_p agenda_paciente.nr_sequencia%type) AS $body$
DECLARE


nr_seq_cpoe_w		cpoe_procedimento.nr_sequencia%type;
nr_prescricao_w		prescr_medica.nr_prescricao%type;


BEGIN

	select	max(nr_sequencia)
	into STRICT	nr_seq_cpoe_w
	from	cpoe_procedimento
	where	nr_seq_lista_espera = nr_seq_lista_p;

	if (nr_seq_cpoe_w IS NOT NULL AND nr_seq_cpoe_w::text <> '') then
		update	cpoe_procedimento
		set	nr_seq_agenda	= nr_seq_agenda_p
		where	nr_sequencia	= nr_seq_cpoe_w;

		select	max(nr_prescricao)
		into STRICT	nr_prescricao_w
		from	prescr_procedimento
		where	nr_seq_proc_cpoe = nr_seq_cpoe_w;

		if (nr_prescricao_w IS NOT NULL AND nr_prescricao_w::text <> '') then
			update	prescr_procedimento
			set	nr_seq_agenda	= nr_seq_agenda_p
			where	nr_seq_proc_cpoe = nr_seq_cpoe_w;

			update	prescr_medica
			set	nr_seq_agenda	= nr_seq_agenda_p
			where	nr_prescricao = nr_prescricao_w;

		end if;
	end if;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE cpoe_vincular_agenda ( nr_seq_lista_p agenda_lista_espera.nr_sequencia%type, nr_seq_agenda_p agenda_paciente.nr_sequencia%type) FROM PUBLIC;

