-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE define_care_plan_interv_plans ( nr_seq_pe_prescr_p bigint, nm_usuario_p text ) AS $body$
DECLARE

nr_seq_interv_adicionada PATIENT_CP_INTERVENTION.NR_SEQUENCIA%type;
nr_seq_interv_plan_adicionada PATIENT_CP_INTERVENTION.NR_SEQ_PAT_CP_INTERV_PLAN%type;

ds_seq_interv_plan varchar(4000) := null;
ds_seq_interv_plan_to_add varchar(4000) := null;
  care_plan_row RECORD;
  intervention_row RECORD;
  interv_plans_orig_row RECORD;
  interv_plan_row RECORD;

BEGIN
      for care_plan_row in (SELECT a.* from PATIENT_CARE_PLAN a where NR_SEQ_PRESCR = nr_seq_pe_prescr_p) loop

        ds_seq_interv_plan := null;
        for intervention_row in (
                SELECT NR_SEQ_INTERVENTION from (
                  SELECT NR_SEQ_INTERVENTION, count(1) from CP_INTERV_PLAN_ASSOC
                  where NR_SEQ_INTERV_PLAN in (
                                  select NR_SEQ_INTERV_PLAN 
                                  from PATIENT_CP_INTERV_PLAN 
                                  where NR_SEQ_PAT_CARE_PLAN = (care_plan_row.NR_SEQUENCIA)
                              ) and IE_SITUACAO = 'A' 
                              group by NR_SEQ_INTERVENTION having count(1) > 1
                ) alias4
        ) loop
          NR_SEQ_INTERV_ADICIONADA := null;
          NR_SEQ_INTERV_PLAN_ADICIONADA := null;
          DS_SEQ_INTERV_PLAN := null;
          DS_SEQ_INTERV_PLAN_TO_ADD := null;

          select NR_SEQUENCIA, NR_SEQ_PAT_CP_INTERV_PLAN
          into STRICT nr_seq_interv_adicionada, nr_seq_interv_plan_adicionada
          from PATIENT_CP_INTERVENTION 
          where NR_SEQ_PAT_CARE_PLAN = (care_plan_row.NR_SEQUENCIA) and NR_SEQ_CP_INTERVENTION = (intervention_row.NR_SEQ_INTERVENTION);

          for interv_plans_orig_row in ( 
                SELECT distinct NR_SEQ_INTERV_PLAN
                from CP_INTERV_PLAN_ASSOC 
                where NR_SEQ_INTERV_PLAN in (
                                SELECT NR_SEQ_INTERV_PLAN 
                                from PATIENT_CP_INTERV_PLAN 
                                where NR_SEQ_PAT_CARE_PLAN = (care_plan_row.NR_SEQUENCIA)
                            ) and IE_SITUACAO = 'A' and NR_SEQ_INTERVENTION = (intervention_row.NR_SEQ_INTERVENTION) 
          ) loop
                      
                      ds_seq_interv_plan := ds_seq_interv_plan || interv_plans_orig_row.NR_SEQ_INTERV_PLAN || ',';
          end loop;

          if (ds_seq_interv_plan IS NOT NULL AND ds_seq_interv_plan::text <> '') then
            for interv_plan_row in (
                          SELECT NR_SEQUENCIA, NR_SEQ_INTERV_PLAN 
                          from PATIENT_CP_INTERV_PLAN 
                          where NR_SEQ_PAT_CARE_PLAN = (care_plan_row.NR_SEQUENCIA) 
                          and DS_SEQ_INTERV_PLAN like '%'||NR_SEQ_INTERV_PLAN||',%') loop
              --IGNORANDO o proprio registro em si que ja foi inserido (do plano de intervencao)
              if (interv_plan_row.NR_SEQUENCIA <> NR_SEQ_INTERV_PLAN_ADICIONADA) then
                ds_seq_interv_plan_to_add := ds_seq_interv_plan_to_add || interv_plan_row.NR_SEQUENCIA || ',';
              end if;
            end loop;

            SELECT SUBSTR(ds_seq_interv_plan_to_add, 0, LENGTH(ds_seq_interv_plan_to_add) - 1)
            into STRICT ds_seq_interv_plan_to_add
;

            if (ds_seq_interv_plan_to_add IS NOT NULL AND ds_seq_interv_plan_to_add::text <> '') then
              update PE_PRESCR_PROC set NRS_PLANOS_PAI = ds_seq_interv_plan_to_add where NR_SEQ_PAT_CP_INTERV = NR_SEQ_INTERV_ADICIONADA;
            end if;
          end if;
        end loop;

    end loop;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE define_care_plan_interv_plans ( nr_seq_pe_prescr_p bigint, nm_usuario_p text ) FROM PUBLIC;

