-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE deletar_doadores_inaptos_hemot () AS $body$
DECLARE


C01 CURSOR FOR
	SELECT	nr_sequencia
	from	san_doador_inapto a
	where	coalesce(a.cd_pessoa_fisica::text, '') = ''
	and	not exists (	SELECT	1
				from	san_exame_lote b,
					san_exame_realizado c
				where	b.nr_seq_doador_inapto	= a.nr_sequencia
				and	c.nr_seq_exame_lote	= b.nr_sequencia
				and	(c.dt_liberacao IS NOT NULL AND c.dt_liberacao::text <> ''));

nr_seq_doador_inapto_w	bigint;


BEGIN

open C01;
loop
fetch C01 into
	nr_seq_doador_inapto_w;
EXIT WHEN NOT FOUND; /* apply on C01 */
	begin
	delete	from san_exame_lote
	where	nr_seq_doador_inapto	= nr_seq_doador_inapto_w;

	delete	FROM san_doador_inapto a
	where	nr_sequencia	= nr_seq_doador_inapto_w;

	end;
end loop;
close C01;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE deletar_doadores_inaptos_hemot () FROM PUBLIC;

