-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE excluir_relatorio_perfil (cd_perfil_p bigint, nr_seq_relatorio_p text, nm_usuario_p text) AS $body$
DECLARE


nr_seq_perfil_relat_w   bigint;


BEGIN

select nr_sequencia
into STRICT nr_seq_perfil_relat_w
from relatorio_perfil
where nr_seq_relatorio = nr_seq_relatorio_p
and cd_perfil = cd_perfil_p;

delete from relatorio_perfil_param where nr_seq_perfil_relat = nr_seq_perfil_relat_w;
commit;
delete from relatorio_perfil where nr_sequencia = nr_seq_perfil_relat_w;
commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE excluir_relatorio_perfil (cd_perfil_p bigint, nr_seq_relatorio_p text, nm_usuario_p text) FROM PUBLIC;

