-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE far_gerar_vendedores_meta ( nr_seq_meta_p bigint, nm_usuario_p text) AS $body$
DECLARE


nr_sequencia_w          bigint;
nr_seq_vendedor_w       bigint;

c01 CURSOR FOR
SELECT  nr_sequencia
from    far_vendedor a
where   trunc(clock_timestamp()) between trunc(dt_inicio) and trunc(dt_final)
and     not exists (
                SELECT  1
                from    far_meta_vendedor x
                where   x.nr_seq_meta = nr_seq_meta_p
                and     x.nr_seq_vendedor = a.nr_sequencia);


BEGIN

open c01;
loop
fetch c01 into
        nr_seq_vendedor_w;
EXIT WHEN NOT FOUND; /* apply on c01 */
        begin

        select  nextval('far_meta_vendedor_seq')
        into STRICT    nr_sequencia_w
;

        insert into far_meta_vendedor(
                nr_sequencia,
                dt_atualizacao,
                nm_usuario,
                dt_atualizacao_nrec,
                nm_usuario_nrec,
                nr_seq_meta,
                nr_seq_vendedor) values (
                        nr_sequencia_w,
                        clock_timestamp(),
                        nm_usuario_p,
                        clock_timestamp(),
                        nm_usuario_p,
                        nr_seq_meta_p,
                        nr_seq_vendedor_w);

        end;
end loop;
close c01;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE far_gerar_vendedores_meta ( nr_seq_meta_p bigint, nm_usuario_p text) FROM PUBLIC;

