-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE gerar_comunic_subs_cih ( cd_profissional_p text, nr_seq_tipo_p bigint, nr_prescricao_p bigint, nr_seq_prescricao_p bigint, nm_usuario_p text) AS $body$
DECLARE


ds_comunicado_w varchar(4000);


BEGIN

ds_comunicado_w := substr(obter_sug_subst_cih(nr_prescricao_p, nr_seq_prescricao_p, nm_usuario_p),1,4000);

	commit;

	insert into 	prescr_mat_comunic_cih(dt_registro,
			cd_profissional,
			nr_seq_tipo,
			ds_comunicado,
			nm_usuario,
			nm_usuario_nrec,
			dt_atualizacao,
			dt_atualizacao_nrec,
			nr_sequencia,
			nr_prescricao,
			nr_seq_prescricao)
	values (clock_timestamp(),
			cd_profissional_p,
			nr_seq_tipo_p,
			ds_comunicado_w,
			nm_usuario_p,
			nm_usuario_p,
			clock_timestamp(),
			clock_timestamp(),
			nextval('prescr_mat_comunic_cih_seq'),
			nr_prescricao_p,
			nr_seq_prescricao_p);

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE gerar_comunic_subs_cih ( cd_profissional_p text, nr_seq_tipo_p bigint, nr_prescricao_p bigint, nr_seq_prescricao_p bigint, nm_usuario_p text) FROM PUBLIC;

