-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE gerar_resumo_avaliacao_oft ( nr_sequencia_p bigint, nm_usuario_p text, ds_resumo_p INOUT text) AS $body$
DECLARE

 
nr_seq_item_w		bigint;
ds_item_w		varchar(32000);
ds_resultado_w		varchar(32000);			
ds_conteudo_w		varchar(32000);		
ie_resultado_w		varchar(10);
nr_atendimento_w		bigint;
cd_pessoa_fisica_w	varchar(10);
cd_medico_w		varchar(10);
dt_avaliacao_w		timestamp;
cd_evolucao_w		bigint;
ds_evolucao_w		varchar(32000);
ie_gerar_resumo_w		varchar(10);
ds_fonte_w		varchar(100);
ds_tam_fonte_w		varchar(10);
nr_tam_fonte_w		integer;
ds_cabecalho_w		varchar(32000);
ds_rodape_w		 varchar(32000);
ie_sem_resposta_w		varchar(1);
										
C01 CURSOR FOR 
SELECT	c.nr_sequencia, 
	coalesce(ds_label_relat,c.ds_item) ds_item, 
	c.IE_RESULTADO, 
	coalesce((SELECT d.ds_resultado from med_item_avaliar_res d where d.nr_seq_item = c.nr_sequencia and obter_somente_numero(Aval(a.nr_sequencia,c.nr_sequencia)) = d.nr_Seq_res and coalesce(c.cd_dominio::text, '') = ''),substr(Aval(a.nr_sequencia,c.nr_sequencia),1,4000)) ds_resultado 
from	med_Avaliacao_paciente a, 
	med_tipo_avaliacao b, 
	med_item_avaliar c 
where	b.nr_sequencia = c.nr_seq_tipo 
and	a.nr_seq_tipo_avaliacao = b.nr_sequencia 
and	(coalesce((select d.ds_resultado from med_item_avaliar_res d where d.nr_seq_item = c.nr_sequencia and obter_somente_numero(Aval(a.nr_sequencia,c.nr_sequencia)) = d.nr_Seq_res and coalesce(c.cd_dominio::text, '') = ''),substr(Aval(a.nr_sequencia,c.nr_sequencia),1,4000)) is not null) 
and	(coalesce((select d.ds_resultado from med_item_avaliar_res d where d.nr_seq_item = c.nr_sequencia and obter_somente_numero(Aval(a.nr_sequencia,c.nr_sequencia)) = d.nr_Seq_res and coalesce(c.cd_dominio::text, '') = ''),substr(Aval(a.nr_sequencia,c.nr_sequencia),1,4000)) <> 'N') 
and	a.nr_sequencia = nr_sequencia_p 
order by c.nr_seq_apresent;									
 

BEGIN 
 
select max(cd_pessoa_fisica), 
	max(nr_atendimento), 
	max(cd_medico), 
	max(dt_avaliacao), 
	max(ie_resumo_oftalmo) 
into STRICT cd_pessoa_fisica_w, 
	nr_atendimento_w, 
	cd_medico_w, 
	dt_avaliacao_w, 
	ie_gerar_resumo_w 
from	med_Avaliacao_paciente a, 
	med_tipo_avaliacao b 
where	b.nr_sequencia = a.nr_seq_tipo_avaliacao 
and	a.nr_sequencia = nr_sequencia_p;
 
 
if (ie_gerar_resumo_w	= 'S') then 
	ds_fonte_w := Obter_Param_Usuario(281, 5, obter_perfil_ativo, nm_usuario_p, wheb_usuario_pck.get_cd_estabelecimento, ds_fonte_w);
	ds_tam_fonte_w := Obter_Param_Usuario(281, 6, obter_perfil_ativo, nm_usuario_p, wheb_usuario_pck.get_cd_estabelecimento, ds_tam_fonte_w);
	nr_tam_fonte_w	:= somente_numero(ds_tam_fonte_w)*2;
	 
	open C01;
	loop 
	fetch C01 into	 
		nr_seq_item_w, 
		ds_item_w, 
		ie_resultado_w, 
		ds_resultado_w;
	EXIT WHEN NOT FOUND; /* apply on C01 */
		begin 
		if (ie_resultado_w in ('X','T')) then 
			ds_conteudo_w	:= ds_conteudo_w||chr(13)||ds_item_w||chr(13)||chr(13);
		elsif (ie_resultado_w = 'B') then 
			if (ds_resultado_w	= 'S') or (ds_resultado_w	= '1') then 
				ds_resultado_w	:= wheb_mensagem_pck.get_texto(94754); -- Sim 
			else
				ds_resultado_w:= wheb_mensagem_pck.get_texto(94755); -- Não 
			end if;
				 
			ds_conteudo_w := ds_conteudo_w ||' '||ds_item_w||' : '||ds_resultado_w||chr(13);
		else 
			ds_conteudo_w := ds_conteudo_w ||' '||ds_item_w||' : '||ds_resultado_w||chr(13);
		end if;
		end;
	end loop;
	close C01;
	ds_resumo_p	:= ds_conteudo_w;
	 
end if;
 
commit;
 
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE gerar_resumo_avaliacao_oft ( nr_sequencia_p bigint, nm_usuario_p text, ds_resumo_p INOUT text) FROM PUBLIC;

