-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE gerar_relatorio_validacao_hist ( nr_seq_relatorio_p bigint, ds_versao_p text, nm_usuario_p text) AS $body$
DECLARE

qt_similaridade_w		varchar(255);
qt_distancia_w		varchar(255);
qt_similaridade_image_w	varchar(255);
qt_distancia_image_w	varchar(255);
qt_similaridade_jprxml_w	varchar(255);
qt_distancia_jprxml_w	varchar(255);
nr_seq_relatorio_validacao_w	bigint;
ie_status_comparacao_w		varchar(1);


BEGIN

select		nr_sequencia,
		a.qt_similaridade,
		a.qt_distancia,
		a.qt_similaridade_image,
		a.qt_distancia_image,
		a.qt_similaridade_jprxml,
		a.qt_distancia_jprxml,
		a.ie_status_comparacao
into STRICT		nr_seq_relatorio_validacao_w,
			qt_similaridade_w,
		qt_distancia_w,
		qt_similaridade_image_w,
		qt_distancia_image_w,
		qt_similaridade_jprxml_w,
		qt_distancia_jprxml_w,
		ie_status_comparacao_w
from		relatorio_validacao a
where		a.nr_seq_relatorio = nr_seq_relatorio_p;


insert into	relatorio_validacao_hist(
		nr_sequencia,
		dt_atualizacao,
		nm_usuario,
		dt_atualizacao_nrec,
		nm_usuario_nrec,
		qt_similaridade,
		qt_distancia,
		qt_similaridade_image,
		qt_distancia_image,
		qt_similaridade_jprxml,
		qt_distancia_jprxml,
		nr_seq_relatorio_validacao,
		ds_versao,
		ie_status_comparacao)
values (	nextval('relatorio_validacao_hist_seq'),
		clock_timestamp(),
		nm_usuario_p,
		clock_timestamp(),
		nm_usuario_p,
		qt_similaridade_w,
		qt_distancia_w,
		qt_similaridade_image_w,
		qt_distancia_image_w,
		qt_similaridade_jprxml_w,
		qt_distancia_jprxml_w,
		nr_seq_relatorio_validacao_w,
		ds_versao_p,
		ie_status_comparacao_w);

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE gerar_relatorio_validacao_hist ( nr_seq_relatorio_p bigint, ds_versao_p text, nm_usuario_p text) FROM PUBLIC;

