-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE gerar_alteracao_item_prescr ( cd_estabelecimento_p bigint, nr_atendimento_p bigint, ie_tipo_item_p text, cd_item_p text, cd_intervalo_p text, qt_item_p bigint, qt_hora_prescricao_p bigint, nr_prescricoes_p text, ie_laboratorio_p text, ie_alteracao_p bigint, nr_seq_motivo_p bigint, nr_seq_motivo_susp_p bigint, ds_justificativa_p text, nm_usuario_p text, nr_seq_proc_interno_p bigint, cd_funcao_p bigint, nr_seq_item_p bigint, nr_prescricao_p bigint, nr_seq_assinatura_p bigint default null, ie_acm_sn_p text default 'N', cd_unidade_medida_p text DEFAULT NULL, cd_medico_solic_p text default null) AS $body$
DECLARE


nr_prescricao_w			bigint;
nr_seq_item_w			bigint;
nr_seq_horario_w			bigint;
nr_seq_alteracao_w		bigint;
dt_atualizacao_w		timestamp := clock_timestamp();
ie_data_proc_w			varchar(15);
ie_tipo_item_w			varchar(255);
ie_gerar_evento_w		varchar(15);
ie_inconsistencia_w		varchar(20);
ie_suspender_medic_adm_w varchar(2);
ds_inconsistentes_w		varchar(20);
dt_primeiro_horario_w	timestamp;
qt_dose_w				double precision;
ie_acm_w				varchar(2);
ie_se_necessario_w		varchar(2);
ie_exibe_suspenso_w		varchar(2);
ie_data_lib_prescr_w	varchar(15);
ie_horarios_dietas_orais_w varchar(1);
nr_horas_validade_w		integer;
nr_seq_dieta_hor_w		bigint;
cd_dieta_w				integer;
cd_refeicao_w			varchar(20);
ie_cursor_c01_w			varchar(1)	:= 'N';
ie_desagrupa_proced_w	varchar(1);
ie_acm_sn_w				varchar(1);
ie_proc_w				varchar(1);
ds_mensagem_w			varchar(255);
nr_prescr_orig_w		bigint;
nr_seq_orig_w			bigint;
cont_w				bigint;
ie_paciente_isolado_w		varchar(1) := 'N';
ie_procedimento_isolado_w	varchar(1) := 'N';
nr_seq_precaucao_w		bigint;
ie_suspende_isolamento_w	varchar(1)  := 'N';
nr_seq_prot_glic_w		bigint;
cd_evolucao_w			bigint;
ie_tipo_dieta_cpoe_w		varchar(10);
nr_prescr_fut_w			bigint;
nr_seq_item_fut_w		bigint;
nr_seq_item_cpoe_w		cpoe_material.nr_sequencia%type;
ds_msg_w				varchar(255);
nr_seq_processo_w 		prescr_mat_hor.nr_seq_processo%type;
qt_processo_w     		integer;
ie_agrupador_w			prescr_material.ie_agrupador%type;

/* obter item x atendimento x alteracao */

c01 CURSOR FOR
SELECT	a.nr_prescricao nr_prescricao, /* suplementos orais */
	b.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	b.nr_sequencia_anterior,
	0
from	prescr_material b,
	prescr_medica a
where	b.nr_prescricao = a.nr_prescricao
--and	a.dt_liberacao is not null
and	obter_se_prescr_lib_adep(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	b.ie_agrupador in (12)
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	b.cd_material = cd_item_p
and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
--and	nvl(b.qt_dose,1) = nvl(qt_item_p,1)
and	coalesce(b.qt_dose,1) = coalesce(qt_item_p,coalesce(b.qt_dose,1))
and	((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'S'

union

SELECT	a.nr_prescricao nr_prescricao, /* medicamentos */
	b.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	b.nr_sequencia_anterior,
	0
from	prescr_material b,
		prescr_medica a
where	b.nr_prescricao = a.nr_prescricao
--and		a.dt_liberacao is not null
and		obter_se_prescr_lib_adep(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w) = 'S'
and		coalesce(a.ie_adep,'S') = 'S'
and		b.ie_agrupador in (1)
and		a.nr_atendimento = nr_atendimento_p
and		obter_se_acm_sn(b.ie_acm, b.ie_se_necessario) = coalesce(ie_acm_sn_p,'N')
and		obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and		a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and		b.cd_material = cd_item_p
and		coalesce(cd_unidade_medida_p,'XPTO') in ('XPTO', b.cd_unidade_medida_dose)
and		coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
--and		nvl(b.qt_dose,1) = nvl(qt_item_p,1)
and		CASE WHEN cd_funcao_p=8030 THEN round((vipe_obter_dose_composto(a.nr_prescricao, b.nr_sequencia, b.nr_agrupamento))::numeric,2)  ELSE coalesce(b.qt_dose,1) END  = coalesce(qt_item_p,CASE WHEN cd_funcao_p=8030 THEN round((vipe_obter_dose_composto(a.nr_prescricao, b.nr_sequencia, b.nr_agrupamento))::numeric,2)  ELSE coalesce(b.qt_dose,1) END )
and		((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and		ie_tipo_item_p in ('M', 'IAH')
and		not exists (	select	1
					from	prescr_mat_hor c
					where	c.nr_prescricao = b.nr_prescricao
					and		c.cd_material 	= b.cd_material
					and		c.ie_agrupador	= 1
					and		(c.dt_fim_horario IS NOT NULL AND c.dt_fim_horario::text <> '')
					and		coalesce(ie_suspender_medic_adm_w,'N')	= 'N'
					and		Obter_se_horario_liberado(c.dt_lib_horario, c.dt_horario) = 'S')

union

select	a.nr_prescricao nr_prescricao, /* materiais */
	b.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	b.nr_sequencia_anterior,
	0
from	prescr_material b,
	prescr_medica a
where	b.nr_prescricao = a.nr_prescricao
--and	a.dt_liberacao is not null
and	obter_se_prescr_lib_adep(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	b.ie_agrupador in (2)
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	b.cd_material = cd_item_p
and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
--and	nvl(b.qt_dose,1) = nvl(qt_item_p,1)
and	coalesce(b.qt_dose,1) = coalesce(qt_item_p,coalesce(b.qt_dose,1))
and	((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'MAT'

union

select	a.nr_prescricao nr_prescricao, /* procedimentos e controles de glicemia */
	b.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	b.nr_seq_anterior,
	b.nr_seq_prot_glic
from	prescr_procedimento b,
	prescr_medica a
where	b.nr_prescricao = a.nr_prescricao
--and	obter_data_lib_proc_adep(a.dt_liberacao, a.dt_liberacao_medico, ie_data_proc_w) is not null
and	(((b.nr_sequencia	= nr_Seq_item_p) and (b.nr_prescricao	= nr_prescricao_p) and (ie_desagrupa_proced_w = 'S')) or (ie_desagrupa_proced_w  = 'N'))
and	obter_se_exibir_adep_suspensos(b.dt_suspensao, ie_exibe_suspenso_w) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	b.cd_procedimento = cd_item_p
and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
and	coalesce(b.qt_procedimento,1) = coalesce(qt_item_p,coalesce(b.qt_procedimento,1))
and	((coalesce(b.nr_seq_exame::text, '') = '' and ie_laboratorio_p = 'N') or ((b.nr_seq_exame IS NOT NULL AND b.nr_seq_exame::text <> '') and ie_laboratorio_p = 'S'))
and	((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p in ('P','G','C','I','HM')
and     coalesce(b.nr_seq_proc_interno, 1) = coalesce(nr_seq_proc_interno_p, coalesce(b.nr_seq_proc_interno,1))

union

select	a.nr_prescricao nr_prescricao, /* recomendacoes */
	b.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	b.nr_seq_anterior,
	0
from	prescr_recomendacao b,
	prescr_medica a
where	b.nr_prescricao = a.nr_prescricao
--and	a.dt_liberacao is not null
and	obter_se_prescr_lib_adep(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	coalesce(to_char(b.cd_recomendacao),coalesce(b.ds_recomendacao,' ')) = cd_item_p
and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
--and	nvl(b.qt_recomendacao,1) = nvl(qt_item_p,1)
and	coalesce(b.qt_recomendacao,1) = coalesce(qt_item_p,coalesce(b.qt_recomendacao,1))
and	((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'R'

union

select	a.nr_sequencia nr_prescricao, /* sae */
	b.nr_sequencia nr_seq_item,
	0,
	0,
	0
from	pe_prescr_proc b,
	pe_prescricao a
where	b.nr_seq_prescr = a.nr_sequencia
and	(a.dt_liberacao IS NOT NULL AND a.dt_liberacao::text <> '')
and	coalesce(b.ie_adep,'N') = 'S'
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_contido(a.nr_sequencia, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	b.nr_seq_proc = cd_item_p
and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
and	((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'E'

union

select	c.nr_prescricao,    /*Dietas*/
	d.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	d.nr_seq_anterior,
	0
from	prescr_dieta d,
	prescr_dieta_hor c,
	prescr_medica a
where	d.nr_prescricao = c.nr_prescricao
and	d.nr_prescricao = a.nr_prescricao
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_prescr_lib_vipe(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w, c.dt_lib_horario) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	ie_horarios_dietas_orais_w = 'S'
and	((c.cd_refeicao = cd_item_p) or
	 ((to_char(d.cd_dieta) = cd_item_p) and (c.cd_refeicao IS NOT NULL AND c.cd_refeicao::text <> '')))
--and	nvl(d.cd_intervalo,'XPTO') = nvl(cd_intervalo_p,'XPTO') 	OS 470787 do testes
and	((ie_alteracao_p = 1 and coalesce(d.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(d.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'D'

union

select	c.nr_prescricao,
	d.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	d.nr_seq_anterior,
	0
from	prescr_dieta d,
	prescr_dieta_hor c,
	prescr_medica a
where	d.nr_prescricao = c.nr_prescricao
and	d.nr_prescricao = a.nr_prescricao
and	c.nr_seq_dieta	= d.nr_sequencia
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_prescr_lib_vipe(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w, c.dt_lib_horario) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	ie_horarios_dietas_orais_w = 'S'
and	coalesce(c.cd_refeicao::text, '') = ''
and	to_char(d.cd_dieta) = cd_item_p
--and	nvl(d.cd_intervalo,'XPTO') = nvl(cd_intervalo_p,'XPTO') 	OS 470787 do testes
and	((ie_alteracao_p = 1 and coalesce(d.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(d.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'D'

union

select	c.nr_prescricao,
	d.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	d.nr_seq_anterior,
	0
from	prescr_dieta d,
	prescr_dieta_hor c,
	prescr_medica a
where	d.nr_prescricao = c.nr_prescricao
and	d.nr_prescricao = a.nr_prescricao
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_prescr_lib_vipe(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w, c.dt_lib_horario) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	to_char(d.cd_dieta) = cd_item_p
and	ie_horarios_dietas_orais_w = 'N'
--and	nvl(d.cd_intervalo,'XPTO') = nvl(cd_intervalo_p,'XPTO') 	OS 470787 do testes
and	((ie_alteracao_p = 1 and coalesce(d.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(d.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'D'

union

select	a.nr_prescricao,
	d.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	d.nr_seq_anterior,
	0
from	prescr_dieta d,
	prescr_medica a
where	d.nr_prescricao	= a.nr_prescricao
and	a.nr_atendimento = nr_atendimento_p
and	((a.dt_liberacao_medico IS NOT NULL AND a.dt_liberacao_medico::text <> '') or (a.dt_liberacao IS NOT NULL AND a.dt_liberacao::text <> ''))
and	coalesce(a.ie_adep,'S') = 'S'
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	((to_char(d.cd_dieta) = cd_item_p) and (ie_horarios_dietas_orais_w = 'N'))
--and	nvl(d.cd_intervalo,'XPTO') = nvl(cd_intervalo_p,'XPTO') 	OS 470787 do testes
and	((ie_alteracao_p = 1 and coalesce(d.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(d.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'D'
and	not exists (
		select	1
		from	prescr_dieta_hor c
		where	c.nr_prescricao = d.nr_prescricao
		and	c.nr_prescricao = a.nr_prescricao
		and	((ie_data_lib_prescr_w = 'M') or (Obter_se_horario_liberado(c.dt_lib_horario, c.dt_horario) = 'S')))

union

select	a.nr_prescricao nr_prescricao, /* Gasoterapia */
	b.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	b.nr_seq_anterior,
	0
from	prescr_gasoterapia b,
	prescr_medica a
where	b.nr_prescricao = a.nr_prescricao
--and	a.dt_liberacao is not null
and	obter_se_prescr_lib_adep(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	to_char(b.nr_seq_gas) = cd_item_p
and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
--and	nvl(b.qt_recomendacao,1) = nvl(qt_item_p,1)
and	coalesce(b.qt_gasoterapia,1) = coalesce(qt_item_p,coalesce(b.qt_gasoterapia,1))
and	((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'O'

union

select	a.nr_prescricao nr_prescricao, /* NPT Adulta protocolo */
	b.nr_sequencia nr_seq_item,
	a.nr_prescricao_anterior,
	b.nr_sequencia_anterior,
	0
from	nut_pac b,
	prescr_medica a
where	b.nr_prescricao = a.nr_prescricao
and	obter_se_prescr_lib_adep(a.dt_liberacao_medico, a.dt_liberacao, a.dt_liberacao_farmacia, ie_data_lib_prescr_w) = 'S'
and	coalesce(a.ie_adep,'S') = 'S'
and	a.nr_atendimento = nr_atendimento_p
and	obter_se_contido(a.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
and	a.dt_validade_prescr > clock_timestamp() - qt_hora_prescricao_p / 24
and	((to_char(coalesce(b.nr_seq_protocolo,b.nr_sequencia)) = cd_item_p) or (exists (	select	1
			from	nut_pac c,
				prescr_medica d
			where	c.nr_prescricao	= d.nr_prescricao
			and	a.nr_atendimento = d.nr_atendimento
			and	b.nr_sequencia_anterior = c.nr_sequencia
			and	b.nr_sequencia_anterior = (cd_item_p)::numeric
			and	coalesce(b.nr_seq_protocolo::text, '') = ''
			and	coalesce(c.nr_seq_protocolo::text, '') = ''
			and	obter_se_contido(d.nr_prescricao, '(' || nr_prescricoes_p || ')') = 'S'
			and	coalesce(b.ie_forma,'X')	= coalesce(c.ie_forma,'X'))))
and	((ie_alteracao_p = 1 and coalesce(b.ie_suspenso,'N') = 'N') or (ie_alteracao_p = 2 and coalesce(b.ie_suspenso,'N') = 'S'))
and	ie_tipo_item_p = 'NAN';

c02 CURSOR FOR
SELECT	a.nr_sequencia,
	coalesce(a.cd_refeicao,b.cd_dieta),
	b.cd_dieta
from	prescr_dieta b,
	prescr_dieta_hor a
where	a.nr_prescricao = b.nr_prescricao
and	a.nr_seq_dieta = b.nr_sequencia
and	((ie_alteracao_p = 1 and coalesce(a.dt_suspensao::text, '') = '') or (ie_alteracao_p = 2 and (a.dt_suspensao IS NOT NULL AND a.dt_suspensao::text <> '')))
and	a.nr_prescricao	= nr_prescricao_w
and	a.nr_seq_dieta	= nr_seq_item_w
and	Obter_se_horario_liberado(a.dt_lib_horario, a.dt_horario) = 'S';

c03 CURSOR FOR
SELECT nr_seq_processo
FROM   prescr_mat_hor
WHERE  nr_prescricao   = nr_prescricao_W
and    nr_seq_material = nr_seq_item_w;


BEGIN


if (cd_funcao_p = 924) then
	ie_suspender_medic_adm_w := obter_param_usuario(924, 222, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_suspender_medic_adm_w);
else
	ie_suspender_medic_adm_w := obter_param_usuario(1113, 352, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_suspender_medic_adm_w);
end if;

ie_data_proc_w := obter_param_usuario(924, 223, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_data_proc_w);
ie_suspende_isolamento_w := obter_param_usuario(924, 1093, Obter_perfil_Ativo, nm_usuario_p, cd_estabelecimento_p, ie_suspende_isolamento_w);
if (cd_funcao_p = 8030) then
	ie_data_lib_prescr_w := obter_param_usuario(8030, 16, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_data_lib_prescr_w);
	ie_horarios_dietas_orais_w := Obter_Param_Usuario(8030, 21, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_horarios_dietas_orais_w);
else
	ie_data_lib_prescr_w := obter_param_usuario(1113, 115, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_data_lib_prescr_w);
	ie_horarios_dietas_orais_w := Obter_Param_Usuario(1113, 148, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_horarios_dietas_orais_w);
	--ie_horarios_dietas_orais_w := 'N';
end if;
ie_exibe_suspenso_w := obter_param_usuario(1113, 117, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_exibe_suspenso_w);
ie_desagrupa_proced_w := obter_param_usuario(1113, 463, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p, ie_desagrupa_proced_w);

if (nr_atendimento_p IS NOT NULL AND nr_atendimento_p::text <> '') and (ie_tipo_item_p IS NOT NULL AND ie_tipo_item_p::text <> '') and (cd_item_p IS NOT NULL AND cd_item_p::text <> '') and (qt_hora_prescricao_p IS NOT NULL AND qt_hora_prescricao_p::text <> '') and (ie_laboratorio_p IS NOT NULL AND ie_laboratorio_p::text <> '') and (ie_alteracao_p IS NOT NULL AND ie_alteracao_p::text <> '') and (nm_usuario_p IS NOT NULL AND nm_usuario_p::text <> '') then

	/* gerar alteracao conforme tipo item */

	open c01;
	loop
	fetch c01 into
		nr_prescricao_w,
		nr_seq_item_w,
		nr_prescr_orig_w,
		nr_seq_orig_w,
		nr_seq_prot_glic_w;
	EXIT WHEN NOT FOUND; /* apply on c01 */
		begin



		if (ie_tipo_item_p in ('S','M', 'IAH', 'MAT')) then /* suplementos orais e medicamentos */
			if (ie_alteracao_p = 1) then
				select 	coalesce(ie_acm, 'N'),
					coalesce(ie_se_necessario, 'N'),
					coalesce(qt_dose,0)
				into STRICT	ie_acm_w,
					ie_se_necessario_w,
					qt_dose_w
				from	prescr_material
				where	nr_prescricao = nr_prescricao_w
				and	nr_sequencia = nr_seq_item_w;

				if (ie_acm_w = 'S') or (ie_se_necessario_w = 'S') then

					select	coalesce(dt_inicio_prescr, clock_timestamp())
					into STRICT	dt_primeiro_horario_w
					from	prescr_medica
					where	nr_prescricao = nr_prescricao_w;


					SELECT * FROM aprazar_item_prescr(
					'N', cd_estabelecimento_p, nr_atendimento_p, 'M', 0, cd_item_p, cd_intervalo_p, qt_dose_w, dt_primeiro_horario_w, to_char(nr_prescricao_w), nr_prescricao_w, nr_seq_item_w, 'N', null, null, nm_usuario_p, ie_inconsistencia_w, ds_inconsistentes_w, null, null, 'N', null, null, 'N', null, null, null, null, '', null, null) INTO STRICT ie_inconsistencia_w, ds_inconsistentes_w;

				end if;

				ie_gerar_evento_w	:= 'N';

				CALL Suspender_item_Prescricao(nr_prescricao_w, nr_seq_item_w, nr_seq_motivo_susp_p, ds_justificativa_p, 'PRESCR_MATERIAL', nm_usuario_p,ie_gerar_evento_w,924);



				if (nr_seq_orig_w  > 0 )	 and (coalesce(cd_funcao_p,1113) 	= 8030)   and (coalesce(ds_justificativa_p, obter_desc_expressao(298989)) <> obter_desc_expressao(343083)) then




					select	count(b.nr_prescricao)
					into STRICT	cont_w
					from	prescr_material b,
							prescr_medica a
					where	b.nr_prescricao = nr_prescr_orig_w
					and	a.nr_prescricao = b.nr_prescricao
					and	b.nr_sequencia  = nr_seq_orig_w
					and	b.cd_material   = cd_item_p
					and	coalesce(cd_unidade_medida_p,'XPTO') in ('XPTO', b.cd_unidade_medida_dose)
					and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
					and	coalesce(b.qt_dose,1) = coalesce(qt_item_p,1)
					and	obter_se_acm_sn(b.ie_acm, b.ie_se_necessario) = coalesce(ie_acm_sn_p,'N')
					and	b.ie_agrupador = 1;


					if (cont_w > 0) then


						CALL gerar_alteracao_item_prescr(	cd_estabelecimento_p,
										nr_atendimento_p,
										ie_tipo_item_p,
										cd_item_p,
										cd_intervalo_p,
										qt_item_p,
										qt_hora_prescricao_p,
										nr_prescr_orig_w,
										ie_laboratorio_p,
										ie_alteracao_p,
										nr_seq_motivo_p,
										nr_seq_motivo_susp_p,
										obter_desc_expressao(343083),
										nm_usuario_p,
										nr_seq_proc_interno_p,
										cd_funcao_p,
										nr_seq_orig_w,
										nr_prescr_orig_w,
										nr_seq_assinatura_p,
										coalesce(ie_acm_sn_p,'N'),
										cd_unidade_medida_p);
					end if;
				end if;

				if (coalesce(cd_funcao_p,1113) 	= 8030)   and (coalesce(ds_justificativa_p,obter_desc_expressao(298989)) <> obter_desc_expressao(343083)) then

					select	min(coalesce(b.nr_prescricao,0)), min(coalesce(b.nr_sequencia,0))
					into STRICT	nr_prescr_fut_w,
							nr_seq_item_fut_w
					from	prescr_material b,
							prescr_medica a
					where	b.nr_prescricao_anterior = nr_prescricao_w
					and		a.nr_atendimento = nr_atendimento_p
					and	a.nr_prescricao = b.nr_prescricao
					and	b.nr_sequencia_anterior  = nr_seq_item_w
					and	b.cd_material   = cd_item_p
					and	coalesce(cd_unidade_medida_p,'XPTO') in ('XPTO', b.cd_unidade_medida_dose)
					and	coalesce(b.cd_intervalo,'XPTO') = coalesce(cd_intervalo_p,'XPTO')
					and	coalesce(b.qt_dose,1) = coalesce(qt_item_p,1)
					and	obter_se_acm_sn(b.ie_acm, b.ie_se_necessario) = coalesce(ie_acm_sn_p,'N')
					and	b.ie_agrupador = 1;



					if (nr_prescr_fut_w > 0) and (nr_seq_item_fut_w > 0) then

						CALL gerar_alteracao_item_prescr(	cd_estabelecimento_p,
										nr_atendimento_p,
										ie_tipo_item_p,
										cd_item_p,
										cd_intervalo_p,
										qt_item_p,
										qt_hora_prescricao_p,
										nr_prescr_fut_w,
										ie_laboratorio_p,
										ie_alteracao_p,
										nr_seq_motivo_p,
										nr_seq_motivo_susp_p,
										obter_desc_expressao(343083),
										nm_usuario_p,
										nr_seq_proc_interno_p,
										cd_funcao_p,
										nr_seq_item_fut_w,
										nr_prescr_fut_w,
										nr_seq_assinatura_p,
										coalesce(ie_acm_sn_p,'N'),
										cd_unidade_medida_p);
					end if;
				end if;

			else
				update	prescr_material
				set	ie_suspenso	= 'N',
					dt_suspensao	 = NULL,
					nm_usuario_susp	 = NULL
				where	nr_prescricao	= nr_prescricao_w
				and	nr_sequencia	= nr_seq_item_w;
			end if;

		elsif (ie_tipo_item_p in ('P','G','C','I','HM')) then /* procedimentos e controles de glicemia */
			if (ie_alteracao_p = 1) then

				update	prescr_procedimento
				set		ie_suspenso	= 'S',
						dt_suspensao	= clock_timestamp(),
						nm_usuario_susp	= nm_usuario_p
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w
				and		((coalesce(nr_seq_proc_interno::text, '') = '') or
						 ((nr_seq_proc_interno IS NOT NULL AND nr_seq_proc_interno::text <> '') and (nr_seq_proc_interno = coalesce(nr_seq_proc_interno_p, nr_seq_proc_interno))))
				and 	not exists (	SELECT 	1
												from	prescr_proc_hor
												where	nr_prescricao = nr_prescricao_w
												and		nr_seq_procedimento = nr_seq_item_w
												and		(dt_fim_horario IS NOT NULL AND dt_fim_horario::text <> ''));

				-- Check if there is CPOE record to suspend
				select	max(nr_seq_proc_cpoe)
				into STRICT	nr_seq_item_cpoe_w
				from	prescr_procedimento
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w
				and		((coalesce(nr_seq_proc_interno::text, '') = '') or
						 ((nr_seq_proc_interno IS NOT NULL AND nr_seq_proc_interno::text <> '') and (nr_seq_proc_interno = coalesce(nr_seq_proc_interno_p, nr_seq_proc_interno))));

				if (nr_seq_item_cpoe_w IS NOT NULL AND nr_seq_item_cpoe_w::text <> '') then

					select	max(coalesce('S','N'))
					into STRICT	ie_proc_w
					from	cpoe_procedimento
					where	nr_sequencia = nr_seq_item_cpoe_w;

					if (coalesce(ie_proc_w,'N') = 'S') then
						update	cpoe_procedimento
						set		dt_suspensao = clock_timestamp(),
								dt_lib_suspensao = clock_timestamp(),
								nm_usuario_susp = nm_usuario_p
						where	nr_sequencia = nr_seq_item_cpoe_w;
					else
						update	cpoe_anatomia_patologica
						set		dt_suspensao = clock_timestamp(),
								dt_lib_suspensao = clock_timestamp(),
								nm_usuario_susp = nm_usuario_p
						where	nr_sequencia = nr_seq_item_cpoe_w;
					end if;
				end if;

				if (ie_tipo_item_p = 'G') then
					update	atend_glicemia
					set		ie_status_glic 		= 'S'
					where	nr_prescricao		= nr_prescricao_w
					and		nr_seq_procedimento	= nr_seq_item_w;
				end if;

			else
				update	prescr_procedimento
				set		ie_suspenso	= 'N',
						dt_suspensao	 = NULL,
						nm_usuario_susp	 = NULL
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w
				and     coalesce(nr_seq_proc_interno,1)  = coalesce(nr_seq_proc_interno_p,coalesce(nr_seq_proc_interno,1));
			end if;

			ie_paciente_isolado_w	  	:= obter_se_pac_isolamento(nr_atendimento_p);
			ie_procedimento_isolado_w 	:= obter_se_proced_isolamento(nr_prescricao_w,nr_seq_item_w);

			if (coalesce(ie_paciente_isolado_w,'N') = 'S') and (coalesce(ie_procedimento_isolado_w,'N') = 'S') and (ie_suspende_isolamento_w = 'S') then

				nr_seq_precaucao_w	:= obter_atendimento_precaucao(nr_atendimento_p,'C');
				CALL atualizar_pac_isolamento(coalesce(nr_seq_precaucao_w,0),nr_atendimento_p,nm_usuario_p);

			end if;

		elsif (ie_tipo_item_p = 'R') then /* recomendacoes */
			if (ie_alteracao_p = 1) then
				update	prescr_recomendacao
				set		ie_suspenso	= 'S',
						dt_suspensao	= clock_timestamp(),
						nm_usuario_susp	= nm_usuario_p,
						nr_seq_motivo_susp = nr_seq_motivo_susp_p
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w;

				-- Check if there is CPOE record to suspend
				select	max(nr_seq_rec_cpoe)
				into STRICT	nr_seq_item_cpoe_w
				from	prescr_recomendacao
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w;

				if (nr_seq_item_cpoe_w IS NOT NULL AND nr_seq_item_cpoe_w::text <> '') then
					update	cpoe_recomendacao
					set		dt_suspensao = clock_timestamp(),
							dt_lib_suspensao = clock_timestamp(),
							nm_usuario_susp = nm_usuario_p
					where	nr_sequencia = nr_seq_item_cpoe_w;
				end if;
			else
				update	prescr_recomendacao
				set	ie_suspenso	= 'N',
					dt_suspensao	 = NULL,
					nm_usuario_susp	 = NULL
				where	nr_prescricao	= nr_prescricao_w
				and	nr_sequencia	= nr_seq_item_w;
			end if;
		elsif (ie_tipo_item_p = 'NAN') then /* NPT Adulta */
			if (ie_alteracao_p = 1) then
				update	nut_pac
				set	ie_suspenso	= 'S',
					dt_suspensao	= clock_timestamp(),
					nm_usuario_susp	= nm_usuario_p,
					ie_status	= 'S'
				where	nr_prescricao	= nr_prescricao_w
				and	nr_sequencia	= nr_seq_item_w;

					update	nut_paciente_hor
				set		dt_suspensao	= clock_timestamp(),
						nm_usuario_susp	= nm_usuario_p,
						ie_status = 'S'
				where	nr_seq_nut_protocolo = nr_seq_item_w
				and		coalesce(dt_suspensao::text, '') = ''
				and		coalesce(dt_fim_horario::text, '') = '';

				if (nr_seq_orig_w > 0 ) and (coalesce(cd_funcao_p,1113) = 8030) and (coalesce(ds_justificativa_p,obter_desc_expressao(298989)) <> obter_desc_expressao(343083)) then

					select	count(b.nr_prescricao)
					into STRICT	cont_w
					from	nut_pac b,
							prescr_medica a
					where	b.nr_prescricao = a.nr_prescricao
					and	b.nr_prescricao = nr_prescr_orig_w
					and	b.nr_sequencia 	= nr_seq_orig_w
					and	((to_char(coalesce(b.nr_seq_protocolo,b.nr_sequencia)) = cd_item_p) or (coalesce(b.nr_seq_protocolo::text, '') = ''));


					if (cont_w > 0) then
						CALL gerar_alteracao_item_prescr(	cd_estabelecimento_p,
										nr_atendimento_p,
										ie_tipo_item_p,
										cd_item_p,
										cd_intervalo_p,
										qt_item_p,
										qt_hora_prescricao_p,
										nr_prescr_orig_w,
										ie_laboratorio_p,
										ie_alteracao_p,
										nr_seq_motivo_p,
										nr_seq_motivo_susp_p,
										obter_desc_expressao(343083),
										nm_usuario_p,
										nr_seq_proc_interno_p,
										cd_funcao_p,
										nr_seq_orig_w,
										nr_prescr_orig_w,
										coalesce(nr_seq_assinatura_p,null),
										coalesce(ie_acm_sn_p,'N'),
										coalesce(cd_unidade_medida_p,'XPTO'));
					end if;

				end if;

				if (coalesce(cd_funcao_p,1113) 	= 8030)   and (coalesce(ds_justificativa_p,obter_desc_expressao(298989)) <> obter_desc_expressao(343083)) then

					select	min(coalesce(b.nr_prescricao,0)), min(coalesce(b.nr_sequencia,0))
					into STRICT	nr_prescr_fut_w,
							nr_seq_item_fut_w
					from	nut_pac b,
							prescr_medica a
					where	b.nr_prescricao = a.nr_prescricao
					and	b.nr_prescricao_original = nr_prescricao_w
					and	b.nr_sequencia_anterior = nr_seq_item_w
					and	((to_char(coalesce(b.nr_seq_protocolo,b.nr_sequencia)) = cd_item_p) or (coalesce(b.nr_seq_protocolo::text, '') = ''));

					if (nr_prescr_fut_w > 0) and (nr_seq_item_fut_w > 0) then

						CALL gerar_alteracao_item_prescr(	cd_estabelecimento_p,
										nr_atendimento_p,
										ie_tipo_item_p,
										cd_item_p,
										cd_intervalo_p,
										qt_item_p,
										qt_hora_prescricao_p,
										nr_prescr_fut_w,
										ie_laboratorio_p,
										ie_alteracao_p,
										nr_seq_motivo_p,
										nr_seq_motivo_susp_p,
										obter_desc_expressao(343083),
										nm_usuario_p,
										nr_seq_proc_interno_p,
										cd_funcao_p,
										nr_seq_item_fut_w,
										nr_prescr_fut_w,
										coalesce(nr_seq_assinatura_p,null),
										coalesce(ie_acm_sn_p,'N'),
										coalesce(cd_unidade_medida_p,'XPTO'));

					end if;
				end if;

			end if;
		elsif (ie_tipo_item_p = 'E') then /* sae */
			if (ie_alteracao_p = 1) then
				update	pe_prescr_proc
				set	ie_suspenso	= 'S',
					dt_suspensao	= clock_timestamp(),
					nm_usuario_susp	= nm_usuario_p
				where	nr_seq_prescr	= nr_prescricao_w
				and	nr_sequencia	= nr_seq_item_w;
			else
				update	pe_prescr_proc
				set	ie_suspenso	= 'N',
					dt_suspensao	 = NULL,
					nm_usuario_susp	 = NULL
				where	nr_seq_prescr	= nr_prescricao_w
				and	nr_sequencia	= nr_seq_item_w;
			end if;

		elsif (ie_tipo_item_p = 'O') then /* Gasoterapia */
			if (ie_alteracao_p = 1) then
				update	prescr_gasoterapia
				set		ie_suspenso	= 'S',
						dt_atualizacao	= clock_timestamp(),
						nm_usuario	= nm_usuario_p
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w;

				-- Check if there is CPOE record to suspend
				select	max(nr_seq_gas_cpoe)
				into STRICT	nr_seq_item_cpoe_w
				from	prescr_gasoterapia
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w;

				if (nr_seq_item_cpoe_w IS NOT NULL AND nr_seq_item_cpoe_w::text <> '') then
					update	cpoe_gasoterapia
					set		dt_suspensao = clock_timestamp(),
							dt_lib_suspensao = clock_timestamp(),
							nm_usuario_susp = nm_usuario_p
					where	nr_sequencia = nr_seq_item_cpoe_w;
				end if;
			else
				update	prescr_gasoterapia
				set		ie_suspenso	= 'N',
						dt_atualizacao	= clock_timestamp(),
						nm_usuario	= nm_usuario_p
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w;
			end if;

		elsif (ie_tipo_item_p = 'D') then /* dietas */
			if (ie_alteracao_p = 1) then

				update	prescr_dieta
				set		ie_suspenso	= 'S',
						nm_usuario	= nm_usuario_p,
						dt_atualizacao	= clock_timestamp(),
						dt_suspensao	= clock_timestamp(),
						nm_usuario_susp	= nm_usuario_p,
						nr_seq_motivo_susp = nr_seq_motivo_susp_p
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w;

				-- Check if there is CPOE record to suspend
				select	max(nr_seq_dieta_cpoe)
				into STRICT	nr_seq_item_cpoe_w
				from	prescr_dieta
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia	= nr_seq_item_w;

				if (nr_seq_item_cpoe_w IS NOT NULL AND nr_seq_item_cpoe_w::text <> '') then
					update	cpoe_dieta
					set		dt_suspensao = clock_timestamp(),
							dt_lib_suspensao = clock_timestamp(),
							nm_usuario_susp = nm_usuario_p
					where	nr_sequencia = nr_seq_item_cpoe_w;
				end if;

				update	prescr_material
				set		ie_suspenso	= 'S',
						nm_usuario	= nm_usuario_p,
						dt_atualizacao	= clock_timestamp(),
						dt_suspensao	= clock_timestamp(),
						nm_usuario_susp	= nm_usuario_p
				where	nr_prescricao	= nr_prescricao_w
				and		nr_sequencia_dieta = nr_seq_item_w;

				update	prescr_dieta_hor
				set		nm_usuario		= nm_usuario_p,
						dt_atualizacao	= clock_timestamp(),
						dt_suspensao	= clock_timestamp(),
						nm_usuario_susp	= nm_usuario_p
				where	nr_prescricao	= nr_prescricao_w
				and		nr_seq_dieta	= nr_seq_item_w;

				select	max(nr_horas_validade)
				into STRICT	nr_horas_validade_w
				from	prescr_medica
				where	nr_prescricao	= nr_prescricao_w;

				open c02;
				loop
				fetch c02 into
					nr_seq_dieta_hor_w,
					cd_refeicao_w,
					cd_dieta_w;
				EXIT WHEN NOT FOUND; /* apply on c02 */
					if (ie_horarios_dietas_orais_w = 'S') then
						begin
						SELECT * FROM gerar_alteracao_horario_prescr(cd_estabelecimento_p, nr_atendimento_p, 'D', cd_refeicao_w, null, null, nr_horas_validade_w, null, nr_seq_dieta_hor_w, null, nr_prescricao_w, nr_prescricao_w, null, 'N', 5, null, null, null, null, null, null, nm_usuario_p, 'N', null, null, nr_seq_motivo_susp_p, 'N', null, 'N', null, 'N', obter_perfil_ativo, cd_funcao_p, 'N', null, null, null, null, null, 'N', null, null, null, null, '', '', cd_evolucao_w, null, null, ds_msg_w) INTO STRICT cd_evolucao_w, ds_msg_w;
						end;
					else
						begin
						SELECT * FROM gerar_alteracao_horario_prescr(cd_estabelecimento_p, nr_atendimento_p, 'DS', cd_dieta_w, null, null, nr_horas_validade_w, null, nr_seq_dieta_hor_w, null, nr_prescricao_w, nr_prescricao_w, null, 'N', 5, null, null, null, null, null, null, nm_usuario_p, 'N', null, null, nr_seq_motivo_susp_p, 'N', null, 'N', null, 'N', obter_perfil_ativo, cd_funcao_p, 'N', null, null, null, null, null, 'N', null, null, null, null, '', '', cd_evolucao_w, null, null, ds_msg_w) INTO STRICT cd_evolucao_w, ds_msg_w;
						end;
					end if;

				end loop;
				close c02;
			else
				update	prescr_dieta
				set	ie_suspenso	= 'N',
					nm_usuario	= nm_usuario_p,
					dt_atualizacao	= clock_timestamp(),
					dt_suspensao	 = NULL,
					nm_usuario_susp	 = NULL
				where	nr_prescricao	= nr_prescricao_w
				and	nr_sequencia	= nr_seq_item_w;

				update	prescr_material
				set	ie_suspenso	= 'N',
					nm_usuario	= nm_usuario_p,
					dt_atualizacao	= clock_timestamp(),
					dt_suspensao	 = NULL,
					nm_usuario_susp	 = NULL
				where	nr_prescricao	= nr_prescricao_w
				and	nr_sequencia_dieta = nr_seq_item_w;

				select	nr_horas_validade
				into STRICT	nr_horas_validade_w
				from	prescr_medica
				where	nr_prescricao	= nr_prescricao_w;

				open c02;
				loop
				fetch c02 into
					nr_seq_dieta_hor_w,
					cd_refeicao_w,
					cd_dieta_w;
				EXIT WHEN NOT FOUND; /* apply on c02 */
					if (ie_horarios_dietas_orais_w = 'S') then
						begin
						SELECT * FROM gerar_alteracao_horario_prescr(cd_estabelecimento_p, nr_atendimento_p, 'D', cd_refeicao_w, null, null, nr_horas_validade_w, null, nr_seq_dieta_hor_w, null, nr_prescricao_w, nr_prescricao_w, null, 'N', 6, null, null, null, null, null, null, nm_usuario_p, 'N', null, null, null, 'N', null, 'N', null, 'N', obter_perfil_ativo, cd_funcao_p, 'N', null, null, null, null, null, 'N', null, null, null, null, '', '', cd_evolucao_w, null, null, ds_msg_w) INTO STRICT cd_evolucao_w, ds_msg_w;
						end;
					else
						begin
						SELECT * FROM gerar_alteracao_horario_prescr(cd_estabelecimento_p, nr_atendimento_p, 'DS', cd_dieta_w, null, null, nr_horas_validade_w, null, nr_seq_dieta_hor_w, null, nr_prescricao_w, nr_prescricao_w, null, 'N', 6, null, null, null, null, null, null, nm_usuario_p, 'N', null, null, null, 'N', null, 'N', null, 'N', obter_perfil_ativo, cd_funcao_p, 'N', null, null, null, null, null, 'N', null, null, null, null, '', '', cd_evolucao_w, null, null, ds_msg_w) INTO STRICT cd_evolucao_w, ds_msg_w;
						end;
					end if;

				end loop;
				close c02;
			end if;
		end if;

		/* gerar evento alteracao conforme tipo item */

		if (ie_tipo_item_p in ('S','M', 'IAH', 'MAT')) then /* suplementos orais e medicamentos */
			select	max(obter_se_acm_sn(ie_acm, ie_se_necessario))
			into STRICT	ie_acm_sn_w
			from	prescr_material
			where	nr_prescricao 	= nr_prescricao_w
			and		nr_sequencia	= nr_seq_item_w;

			select	nextval('prescr_mat_alteracao_seq')
			into STRICT	nr_seq_alteracao_w
			;

			insert into prescr_mat_alteracao(
								nr_sequencia,
								dt_atualizacao,
								nm_usuario,
								dt_atualizacao_nrec,
								nm_usuario_nrec,
								nr_prescricao,
								nr_seq_prescricao,
								dt_alteracao,
								cd_pessoa_fisica,
								ie_alteracao,
								nr_seq_motivo,
								ds_justificativa,
								ie_tipo_item,
								nr_atendimento,
								cd_item,
								nr_seq_motivo_susp,
								qt_dose_original,
								nr_seq_assinatura,
								ie_acm_sn,
								cd_medico_solic
								)
							values (
								nr_seq_alteracao_w,
								dt_atualizacao_w,
								nm_usuario_p,
								dt_atualizacao_w,
								nm_usuario_p,
								nr_prescricao_w,
								nr_seq_item_w,
								dt_atualizacao_w,
								obter_dados_usuario_opcao(nm_usuario_p,'C'),
								ie_alteracao_p,
								nr_seq_motivo_p,
								ds_justificativa_p,
								ie_tipo_item_p,
								nr_atendimento_p,
								cd_item_p,
								nr_seq_motivo_susp_p,
								qt_item_p,
								nr_seq_assinatura_p,
								ie_acm_sn_w,
								cd_medico_solic_p
								);

			if (ie_tipo_item_p in ('M', 'IAH')) and (ie_alteracao_p in (1,2)) then
				if (ie_alteracao_p = 1) then
					CALL gerar_susp_adep_processo_item(nr_prescricao_w, nr_seq_item_w, '3', nm_usuario_p);
				else
					CALL gerar_susp_adep_processo_item(nr_prescricao_w, nr_seq_item_w, '4', nm_usuario_p);
				end if;
			end if;

		elsif (ie_tipo_item_p in ('P','G','C','I')) then /* procedimentos e controles de glicemia */
			select	nextval('prescr_mat_alteracao_seq')
			into STRICT	nr_seq_alteracao_w
			;

			insert into prescr_mat_alteracao(
								nr_sequencia,
								dt_atualizacao,
								nm_usuario,
								dt_atualizacao_nrec,
								nm_usuario_nrec,
								nr_prescricao,
								nr_seq_procedimento,
								dt_alteracao,
								cd_pessoa_fisica,
								ie_alteracao,
								nr_seq_motivo,
								ds_justificativa,
								ie_tipo_item,
								nr_atendimento,
								cd_item,
								nr_seq_proc_interno,
								nr_seq_motivo_susp,
								nr_seq_assinatura,
								nr_seq_prot_glic
								)
							values (
								nr_seq_alteracao_w,
								dt_atualizacao_w,
								nm_usuario_p,
								dt_atualizacao_w,
								nm_usuario_p,
								nr_prescricao_w,
								nr_seq_item_w,
								dt_atualizacao_w,
								obter_dados_usuario_opcao(nm_usuario_p,'C'),
								ie_alteracao_p,
								nr_seq_motivo_p,
								ds_justificativa_p,
								ie_tipo_item_p,
								nr_atendimento_p,
								cd_item_p,
								nr_seq_proc_interno_p,
								nr_seq_motivo_susp_p,
								nr_seq_assinatura_p,
								nr_seq_prot_glic_w
								);

		elsif (ie_tipo_item_p = 'R') then /* recomendacoes */
			select	nextval('prescr_mat_alteracao_seq')
			into STRICT	nr_seq_alteracao_w
			;

			insert into prescr_mat_alteracao(
								nr_sequencia,
								dt_atualizacao,
								nm_usuario,
								dt_atualizacao_nrec,
								nm_usuario_nrec,
								nr_prescricao,
								nr_seq_recomendacao,
								dt_alteracao,
								cd_pessoa_fisica,
								ie_alteracao,
								nr_seq_motivo,
								ds_justificativa,
								ie_tipo_item,
								nr_atendimento,
								cd_item,
								nr_seq_motivo_susp,
								nr_seq_assinatura
								)
							values (
								nr_seq_alteracao_w,
								dt_atualizacao_w,
								nm_usuario_p,
								dt_atualizacao_w,
								nm_usuario_p,
								nr_prescricao_w,
								nr_seq_item_w,
								dt_atualizacao_w,
								obter_dados_usuario_opcao(nm_usuario_p,'C'),
								ie_alteracao_p,
								nr_seq_motivo_p,
								ds_justificativa_p,
								ie_tipo_item_p,
								nr_atendimento_p,
								cd_item_p,
								nr_seq_motivo_susp_p,
								nr_seq_assinatura_p
								);

		elsif (ie_tipo_item_p = 'E') then /* sae */
			select	nextval('prescr_mat_alteracao_seq')
			into STRICT	nr_seq_alteracao_w
			;

			insert into prescr_mat_alteracao(
								nr_sequencia,
								dt_atualizacao,
								nm_usuario,
								dt_atualizacao_nrec,
								nm_usuario_nrec,
								nr_prescricao,
								nr_seq_item_sae,
								dt_alteracao,
								cd_pessoa_fisica,
								ie_alteracao,
								nr_seq_motivo,
								ds_justificativa,
								ie_tipo_item,
								nr_atendimento,
								cd_item,
								nr_seq_assinatura
								)
							values (
								nr_seq_alteracao_w,
								dt_atualizacao_w,
								nm_usuario_p,
								dt_atualizacao_w,
								nm_usuario_p,
								nr_prescricao_w,
								nr_seq_item_w,
								dt_atualizacao_w,
								obter_dados_usuario_opcao(nm_usuario_p,'C'),
								ie_alteracao_p,
								nr_seq_motivo_p,
								ds_justificativa_p,
								ie_tipo_item_p,
								nr_atendimento_p,
								cd_item_p,
								nr_seq_assinatura_p
								);

		elsif (ie_tipo_item_p = 'O') then /* Gasoterapia */
			if (ie_alteracao_p = 1) then
				ds_mensagem_w := Gerar_Alteracao_Gasoterapia(nr_seq_item_w, 'S', null, null, dt_atualizacao_w, nr_prescricao_w, null, null, nm_usuario_p, null, null, null, null, ds_mensagem_w);
			else
				ds_mensagem_w := Gerar_Alteracao_Gasoterapia(nr_seq_item_w, 'RV', null, null, dt_atualizacao_w, nr_prescricao_w, null, null, nm_usuario_p, null, null, null, null, ds_mensagem_w);
			end if;

		elsif (ie_tipo_item_p	= 'NAN') and (ie_alteracao_p = 1) then /*NPT adulta, a principio criado evento apenas para a suspensao*/
			select	nextval('prescr_solucao_evento_seq')
			into STRICT	nr_seq_alteracao_w
			;

			insert into prescr_solucao_evento(
								nr_sequencia,
								dt_atualizacao,
								nm_usuario,
								dt_atualizacao_nrec,
								nm_usuario_nrec,
								nr_prescricao,
								nr_seq_solucao,
								nr_seq_material,
								nr_seq_procedimento,
								nr_seq_nut,
								nr_seq_nut_neo,
								ie_tipo_dosagem,
								qt_dosagem,
								qt_vol_infundido,
								qt_vol_desprezado,
								cd_pessoa_fisica,
								ie_alteracao,
								dt_alteracao,
								ie_evento_valido,
								nr_seq_motivo,
								ds_observacao,
								ds_justificativa,
								ie_tipo_solucao,
								nr_seq_assinatura
								)
							values (
								nr_seq_alteracao_w,
								clock_timestamp(),
								nm_usuario_p,
								clock_timestamp(),
								nm_usuario_p,
								nr_prescricao_w,
								null,
								null,
								null,
								null,
								nr_seq_item_w,
								null,
								null,
								null,
								null,
								obter_dados_usuario_opcao(nm_usuario_p, 'C'),
								7,	--7 Eh a alteracao equivalente a suspensao, caso for colocar outro evento, tem que mudar o numero da alteracao
								clock_timestamp(),
								'S',
								null,
								null,
								ds_justificativa_p,
								6,
								nr_seq_assinatura_p
								);
		elsif (ie_tipo_item_p = 'HM') and (ie_alteracao_p = 1) then

			select  nextval('prescr_solucao_evento_seq')
			into STRICT    nr_seq_alteracao_w
			;

			insert into prescr_solucao_evento(
								nr_sequencia,
								dt_atualizacao,
								nm_usuario,
								dt_atualizacao_nrec,
								nm_usuario_nrec,
								nr_prescricao,
								nr_seq_solucao,
								nr_seq_material,
								nr_seq_procedimento,
								nr_seq_nut,
								nr_seq_nut_neo,
								cd_pessoa_fisica,
								ie_alteracao,
								dt_alteracao,
								ie_evento_valido,
								ie_tipo_solucao,
								nr_seq_assinatura
								)
						values (
								nr_seq_alteracao_w,
								clock_timestamp(),
								nm_usuario_p,
								clock_timestamp(),
								nm_usuario_p,
								nr_prescricao_w,
								null,
								null,
								nr_seq_item_w,
								null,
								null,
								obter_dados_usuario_opcao(nm_usuario_p, 'C'),
								7,      --7 Eh a alteracao equivalente a suspensao
								clock_timestamp(),
								'S',
								3,
								nr_seq_assinatura_p
								);
		-- OS 1536865 Evento de suspender Dieta;
		elsif (ie_tipo_item_p = 'D') and (ie_alteracao_p = 1) then

			select  nextval('prescr_mat_alteracao_seq')
			into STRICT    nr_seq_alteracao_w
			;

			insert	into	prescr_mat_alteracao(
						nr_sequencia,
						dt_atualizacao,
						nm_usuario,
						nm_usuario_nrec,
						dt_atualizacao_nrec,
						nr_prescricao,
						dt_alteracao,
						cd_pessoa_fisica,
						ie_alteracao,
						nr_seq_motivo,
						ds_justificativa,
						ie_tipo_item,
						nr_atendimento,
						cd_item,
						nr_seq_assinatura
						)
					values (
						nr_seq_alteracao_w,
						dt_atualizacao_w,
						nm_usuario_p,
						nm_usuario_p,
						dt_atualizacao_w,
						nr_prescricao_w,
						dt_atualizacao_w,
						obter_dados_usuario_opcao(nm_usuario_p,'C'),
						ie_alteracao_p,
						nr_seq_motivo_p,
						ds_justificativa_p,
						ie_tipo_item_p,
						nr_atendimento_p,
						cd_item_p,
						nr_seq_assinatura_p
						);
		end if;

		/* definir setor execucao adep */

		CALL definir_setor_exec_adep(nr_atendimento_p,ie_tipo_item_p,nr_prescricao_w,nr_seq_item_w,null,null);
		end;

		ie_cursor_c01_w := 'S';

    select	max(a.ie_agrupador)
    into STRICT	  ie_agrupador_w
    from	  prescr_material a
    where	a.nr_prescricao = nr_prescricao_w
    and   a.nr_sequencia = nr_seq_item_w;

    if (ie_agrupador_w in (1,2,8,12,16)) then
      open C03;
      loop
      fetch C03 into
        nr_seq_processo_w;
      EXIT WHEN NOT FOUND; /* apply on C03 */
        begin
          select coalesce(count(*), 0)
          into STRICT   qt_processo_w
          from   prescr_mat_hor
          where  nr_seq_processo = nr_seq_processo_w
          and    coalesce(dt_suspensao::text, '') = '';

          if (qt_processo_w = 0) then
            update	adep_processo
            set		ie_inconsistencia = 'S',
                    dt_cancelamento = clock_timestamp(),
                    nm_usuario_cancelamento = nm_usuario_p,
                    dt_suspensao = clock_timestamp(),
                    nm_usuario_susp = nm_usuario_p
            where	nr_sequencia = nr_seq_processo_w;
          end if;
        end;
      end loop;
      close C03;
    end if;
	end loop;
	close c01;

	if (ie_cursor_c01_w	= 'N') and (ie_tipo_item_p		in ('M', 'IAH')) and (ie_suspender_medic_adm_w = 'N') and (cd_funcao_p <> 8030) then
		-- Voce nao tem permissao para suspender o item ja administrado. Parametro [352].
		CALL Wheb_mensagem_pck.exibir_mensagem_abort(194077);
	end if;
end if;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE gerar_alteracao_item_prescr ( cd_estabelecimento_p bigint, nr_atendimento_p bigint, ie_tipo_item_p text, cd_item_p text, cd_intervalo_p text, qt_item_p bigint, qt_hora_prescricao_p bigint, nr_prescricoes_p text, ie_laboratorio_p text, ie_alteracao_p bigint, nr_seq_motivo_p bigint, nr_seq_motivo_susp_p bigint, ds_justificativa_p text, nm_usuario_p text, nr_seq_proc_interno_p bigint, cd_funcao_p bigint, nr_seq_item_p bigint, nr_prescricao_p bigint, nr_seq_assinatura_p bigint default null, ie_acm_sn_p text default 'N', cd_unidade_medida_p text DEFAULT NULL, cd_medico_solic_p text default null) FROM PUBLIC;

