-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE gerar_hist_transcricao ( nr_sequencia_p bigint, ie_acao_p text, ds_justificativa_p text, nm_usuario_p text) AS $body$
BEGIN

insert	into	log_analise_prescr(
		nr_sequencia,
		dt_atualizacao,
		nm_usuario,
		nr_prescricao,
		ie_acao,
		dt_acao,
		nm_usuario_acao,
		ds_motivo_acao,
		nr_seq_transcricao)
values (nextval('log_analise_prescr_seq'),
		clock_timestamp(),
		nm_usuario_p,
		null,
		ie_acao_p,
		clock_timestamp(),
		nm_usuario_p,
		substr(ds_justificativa_p,1,255),
		nr_sequencia_p);

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE gerar_hist_transcricao ( nr_sequencia_p bigint, ie_acao_p text, ds_justificativa_p text, nm_usuario_p text) FROM PUBLIC;

