-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE gerar_inicio_higienizacao ( cd_setor_atendimento_p bigint, cd_unidade_basica_p text, cd_unidade_compl_p text, qt_tempo_prev_higien_p bigint, dt_higienizacao_p timestamp, cd_estabelecimento_p bigint, cd_perfil_p bigint, nm_usuario_p text) AS $body$
DECLARE


vl_parametro_w	varchar(255);


BEGIN

if (cd_setor_atendimento_p > 0) and (cd_unidade_basica_p IS NOT NULL AND cd_unidade_basica_p::text <> '') and (cd_unidade_compl_p IS NOT NULL AND cd_unidade_compl_p::text <> '') then
	begin
	vl_parametro_w := Obter_Param_Usuario(44, 53, cd_perfil_p, nm_usuario_p, cd_estabelecimento_p, vl_parametro_w);

	if (vl_parametro_w = 'S') then
		update	unidade_atendimento
		set     ie_status_unidade	=  'H',
			nm_usuario_higienizacao = nm_usuario_p,
			dt_inicio_higienizacao	= dt_higienizacao_p,
			qt_tempo_prev_higien	= qt_tempo_prev_higien_p,
			dt_higienizacao		 = NULL,
			nm_usuario		= nm_usuario_p,
			dt_atualizacao		= clock_timestamp()
		where	cd_unidade_basica	= cd_unidade_basica_p
		and	cd_unidade_compl	= cd_unidade_compl_p
		and	cd_setor_atendimento	= cd_setor_atendimento_p;
	else
		update	unidade_atendimento
		set     ie_status_unidade	=  'H',
			nm_usuario_higienizacao = nm_usuario_p,
			dt_inicio_higienizacao	= dt_higienizacao_p,
			dt_higienizacao		 = NULL,
			nm_usuario		= nm_usuario_p,
			dt_atualizacao		= clock_timestamp()
		where	cd_unidade_basica	= cd_unidade_basica_p
		and	cd_unidade_compl	= cd_unidade_compl_p
		and	cd_setor_atendimento	= cd_setor_atendimento_p;
	end if;
	end;
end if;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE gerar_inicio_higienizacao ( cd_setor_atendimento_p bigint, cd_unidade_basica_p text, cd_unidade_compl_p text, qt_tempo_prev_higien_p bigint, dt_higienizacao_p timestamp, cd_estabelecimento_p bigint, cd_perfil_p bigint, nm_usuario_p text) FROM PUBLIC;

