-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE grava_ajuste_preco_material ( cd_estabelecimento_p bigint, cd_tab_preco_origem_p bigint, cd_tab_preco_destino_p bigint, cd_material_p bigint, dt_vigencia_origem_p timestamp, dt_vigencia_destino_p timestamp, ie_indice_p bigint, nm_usuario_p text, cd_grupo_material_p bigint, cd_subgrupo_material_p bigint, cd_classe_material_p bigint, ie_arredondamento_p text, qt_casas_decimais_p bigint) AS $body$
DECLARE


cd_material_w			integer;
vl_preco_venda_w		double precision;
cd_moeda_w			smallint;
ie_copiar_outros_estab_w	varchar(1);

c01 CURSOR FOR
SELECT	a.cd_material,
	a.vl_preco_venda,
	a.cd_moeda
from	preco_material a,
	estrutura_material_v b
where	a.cd_material = b.cd_material
and	a.cd_estabelecimento = cd_estabelecimento_p
and	a.cd_tab_preco_mat   = cd_tab_preco_origem_p
and	to_char(a.dt_inicio_vigencia, 'dd/mm/yyyy hh24:mi:ss') = to_char(dt_vigencia_origem_p, 'dd/mm/yyyy hh24:mi:ss')
and (a.cd_material = cd_material_p or cd_material_p = 0)
and	cd_grupo_material = coalesce(cd_grupo_material_p,cd_grupo_material)
and	cd_subgrupo_material = coalesce(cd_subgrupo_material_p,cd_subgrupo_material)
and	cd_classe_material	= coalesce(cd_classe_material_p,cd_classe_material)
and	not exists (	select x.cd_material
		 	from preco_material x
		  	where x.cd_material = a.cd_material
		    	and x.cd_estabelecimento = cd_estabelecimento_p
		    	and x.cd_tab_preco_mat = cd_tab_preco_destino_p
		    	and x.dt_inicio_vigencia = dt_vigencia_destino_p);


BEGIN

ie_copiar_outros_estab_w := coalesce(Obter_valor_param_usuario(3110, 38, obter_perfil_ativo, nm_usuario_p, cd_estabelecimento_p),'N');

open c01;
loop
fetch c01 into
	cd_material_w,
	vl_preco_venda_w,
	cd_moeda_w;
EXIT WHEN NOT FOUND; /* apply on c01 */

begin

if (ie_arredondamento_p = 'N') or (qt_casas_decimais_p = 0) then
    vl_preco_venda_w := vl_preco_venda_w * ie_indice_p;
elsif (ie_arredondamento_p = 'D') then
    vl_preco_venda_w := trunc(vl_preco_venda_w * ie_indice_p,qt_casas_decimais_p);
elsif (ie_arredondamento_p = 'P') then
    vl_preco_venda_w := round(vl_preco_venda_w * ie_indice_p,qt_casas_decimais_p);
end if;

insert into preco_material(
	cd_estabelecimento,
	cd_tab_preco_mat,
	cd_material,
	dt_inicio_vigencia,
	vl_preco_venda,
	cd_moeda,
	ie_brasindice,
	ie_situacao,
	nm_usuario,
	dt_atualizacao)
values (	cd_estabelecimento_p,
	cd_tab_preco_destino_p,
	cd_material_w,
	dt_vigencia_destino_p,
	vl_preco_venda_w,
	cd_moeda_w,
	'N',
	'A',
	nm_usuario_p,
	clock_timestamp());

if (ie_copiar_outros_estab_w = 'R') then
	copiar_mat_tabela_estab(cd_tab_preco_destino_p, cd_estabelecimento_p, cd_material_w, dt_vigencia_destino_p, nm_usuario_p);
end if;

end;
end loop;
close c01;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE grava_ajuste_preco_material ( cd_estabelecimento_p bigint, cd_tab_preco_origem_p bigint, cd_tab_preco_destino_p bigint, cd_material_p bigint, dt_vigencia_origem_p timestamp, dt_vigencia_destino_p timestamp, ie_indice_p bigint, nm_usuario_p text, cd_grupo_material_p bigint, cd_subgrupo_material_p bigint, cd_classe_material_p bigint, ie_arredondamento_p text, qt_casas_decimais_p bigint) FROM PUBLIC;

