-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE hsm_gerar_glasgow_tolife ( nr_atendimento_p bigint, nm_usuario_p text, ie_resposta_motora_p bigint, ie_resposta_verbal_p bigint, ie_abertura_ocular_p bigint, qt_pontuacao_p bigint) AS $body$
DECLARE


qt_idade_adulto_w 		bigint;
ie_classif_etaria_w		varchar(1);
qt_idade_paciente_w		bigint;
cd_pessoa_fisica_w		bigint;


BEGIN
	
	qt_idade_adulto_w := OBTER_PARAM_USUARIO_LOGADO(281,331);
	cd_pessoa_fisica_w := OBTER_PESSOA_ATENDIMENTO(nr_atendimento_p, 'C');
	qt_idade_paciente_w := OBTER_IDADE_PF(cd_pessoa_fisica_w, clock_timestamp(), 'A');

	if (qt_idade_paciente_w < 1) then
		ie_classif_etaria_w := 'N';
	elsif (qt_idade_paciente_w < qt_idade_adulto_w) then
		ie_classif_etaria_w := 'P';
	else
		ie_classif_etaria_w := 'A';
	end if;
	
	insert into ATEND_ESCALA_INDICE(	nr_sequencia,
								nr_atendimento,
								dt_atualizacao,
								nm_usuario,
								cd_pessoa_fisica,
								qt_glasgow,
								ie_resposta_motora,
								ie_resposta_verbal,
								ie_abertura_ocular,
								dt_avaliacao,
								dt_liberacao,
								ie_classif_etaria,
								ie_situacao)
					values (nextval('atend_escala_indice_seq'),
								nr_atendimento_p,
								clock_timestamp(),
								nm_usuario_p,
								cd_pessoa_fisica_w,
								qt_pontuacao_p,
								ie_resposta_motora_p,
								ie_resposta_verbal_p,
								ie_abertura_ocular_p,
								clock_timestamp(),
								clock_timestamp(),
								ie_classif_etaria_w,
								'A');
	commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE hsm_gerar_glasgow_tolife ( nr_atendimento_p bigint, nm_usuario_p text, ie_resposta_motora_p bigint, ie_resposta_verbal_p bigint, ie_abertura_ocular_p bigint, qt_pontuacao_p bigint) FROM PUBLIC;

