-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE inserir_medic_hemodialise ( nr_seq_solucao_p bigint, cd_protocolo_p bigint, nr_sequencia_p bigint, nm_usuario_p text, nr_seq_protocolo_p bigint) AS $body$
DECLARE


nr_agrupamento_w		bigint;
nr_seq_material_w		bigint;
cd_material_w		integer;
qt_volume_w		double precision;
cd_unidade_medida_w	varchar(255);
ds_observacao_w		varchar(4000);
ie_dose_peso_w		varchar(5);
ie_dispensacao_w		varchar(5);
ie_acm_w		varchar(5);


c01 CURSOR FOR
	SELECT	cd_material,
		qt_volume,
		cd_unidade_medida
	from	protocolo_npt_prod
	where	nr_seq_protocolo = nr_seq_protocolo_p
	and	(cd_unidade_medida IS NOT NULL AND cd_unidade_medida::text <> '');



BEGIN

select	coalesce(ie_acm,'N')
into STRICT	ie_acm_w
from	protocolo_npt
where	nr_sequencia = nr_seq_protocolo_p;

select	max(nr_seq_material)
into STRICT	nr_seq_material_w
From	protocolo_medic_Material
where	cd_protocolo = cd_protocolo_p
and	nr_sequencia = nr_sequencia_p;

select	coalesce(max(nr_agrupamento),0) + 1
into STRICT	nr_agrupamento_w
from	protocolo_medic_solucao
where	cd_protocolo = cd_protocolo_p
and		nr_sequencia = nr_sequencia_p;

update	protocolo_medic_solucao
set		ie_acm = ie_acm_w
where	cd_protocolo = cd_protocolo_p
and		nr_sequencia = nr_sequencia_p
and		nr_seq_solucao = nr_seq_solucao_p;

open C01;
loop
fetch C01 into
	cd_material_w,
	qt_volume_w,
	cd_unidade_medida_w;
EXIT WHEN NOT FOUND; /* apply on C01 */
	begin

	nr_seq_material_w:= coalesce(nr_seq_material_w,0)+1;

	insert into protocolo_medic_material(	nr_seq_material,
					nr_sequencia,
					cd_material,
					cd_protocolo,
					nr_seq_solucao,
					cd_unidade_medida,
					dt_atualizacao,
					ie_aplic_bolus,
					ie_aplic_lenta,
					ie_bomba_infusao,
					ie_urgencia,
					nm_usuario,
					nr_agrupamento,
					ie_agrupador,
					ie_acm)
				values (	nr_seq_material_w,
					nr_sequencia_p,
					cd_material_w,
					cd_protocolo_p,
					nr_seq_solucao_p,
					cd_unidade_medida_w,
					clock_timestamp(),
					'N',
					'N',
					'N',
					'N',
					nm_usuario_p,
					nr_agrupamento_w,
					13,
					ie_acm_w);
	end;
end loop;
close C01;


commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE inserir_medic_hemodialise ( nr_seq_solucao_p bigint, cd_protocolo_p bigint, nr_sequencia_p bigint, nm_usuario_p text, nr_seq_protocolo_p bigint) FROM PUBLIC;

