-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE obter_valor_dimencao_grafico ( cd_medico_p text, qt_vertical_p INOUT bigint, qt_horizontal_p INOUT bigint, qt_fonte_p INOUT bigint) AS $body$
DECLARE


qt_vertical_w	smallint;
qt_horizontal_w	smallint;
qt_fonte_w	smallint;

C01 CURSOR FOR
SELECT	qt_tamanho_vertical,
	qt_tamanho_horizontal,
	qt_tamanho_fonte
from	regra_dimensao_grafico
where	cd_pessoa_fisica = cd_medico_p
order by nr_sequencia;


BEGIN

qt_vertical_p	:= 50;
qt_horizontal_p	:= 800;
qt_fonte_p	:= 8;

open C01;
loop
fetch C01 into
	qt_vertical_w,
	qt_horizontal_w,
	qt_fonte_w;
EXIT WHEN NOT FOUND; /* apply on C01 */

	if (coalesce(qt_vertical_w,0) > 0) then
		qt_vertical_p	:= qt_vertical_w;
	end if;
	if (coalesce(qt_horizontal_w,0) > 0) then
		qt_horizontal_p	:= qt_horizontal_w;
	end if;
	if (coalesce(qt_fonte_w,0) > 0) then
		qt_fonte_p	:= qt_fonte_w;
	end if;

end loop;
close C01;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE obter_valor_dimencao_grafico ( cd_medico_p text, qt_vertical_p INOUT bigint, qt_horizontal_p INOUT bigint, qt_fonte_p INOUT bigint) FROM PUBLIC;

