-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE pls_gerar_glosa_ret_monitor ( nr_seq_guia_ret_p bigint, nr_seq_proc_ret_p bigint, nr_seq_monitor_ret_p bigint, cd_glosa_p text, nr_campo_arquivo_p text, nm_usuario_p text) AS $body$
BEGIN
 
CALL PLS_GERENCIA_ENVIO_ANS_PCK.GERAR_GLOSA_RET_MONITOR( 	nr_seq_guia_ret_p, 
							nr_seq_proc_ret_p, 
							nr_seq_monitor_ret_p, 
							cd_glosa_p, 
							nr_campo_arquivo_p,					 
							nm_usuario_p);
--commit; 
 
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE pls_gerar_glosa_ret_monitor ( nr_seq_guia_ret_p bigint, nr_seq_proc_ret_p bigint, nr_seq_monitor_ret_p bigint, cd_glosa_p text, nr_campo_arquivo_p text, nm_usuario_p text) FROM PUBLIC;

