-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE pls_atu_valor_servico ( nr_seq_fatura_p pls_fatura.nr_sequencia%type) AS $body$
DECLARE


/* ******************************************************************************************************************************

  Motivo: Rotina que realiza a validação dos registros sem valores no R504 e agrupa os valores do procedimento, honorário e filme

***********************************************************************************************************************************/

-- Busca os itens do lote que possuem procedimentos com valor zerado e com valor diferente de zero para unificar
c01 CURSOR FOR
	SELECT	pns.oid,
		pns.*,
		pnc.nr_seq_fatura,
		pf.nr_seq_pls_fatura
	from	ptu_nota_servico	pns,
		ptu_nota_cobranca	pnc,
		ptu_fatura		pf,
		pls_fatura		plf
	where	pnc.nr_sequencia	= pns.nr_seq_nota_cobr
	and	pf.nr_sequencia		= pnc.nr_seq_fatura
	and	plf.nr_sequencia	= pf.nr_seq_pls_fatura
	and	pns.vl_procedimento	> 0
	and	plf.nr_sequencia	= nr_seq_fatura_p
	and exists (SELECT 1
		from	ptu_nota_servico	pns_2,
			ptu_nota_cobranca	pnc_2,
			ptu_fatura		pf_2,
			pls_fatura		plf_2
		where	pnc_2.nr_sequencia	= pns_2.nr_seq_nota_cobr
		and	pf_2.nr_sequencia	= pnc_2.nr_seq_fatura
		and	plf_2.nr_sequencia	= pf_2.nr_seq_pls_fatura
		and	pns_2.vl_procedimento	= 0
		and	plf_2.nr_sequencia	= nr_seq_fatura_p
		and	pnc_2.nr_sequencia	= pns.nr_seq_nota_cobr
		and	pf_2.nr_sequencia	= pnc.nr_seq_fatura
		and	plf_2.nr_sequencia	= pf.nr_seq_pls_fatura
		and	pns.cd_procedimento	= pns_2.cd_procedimento
		and (pns.nr_seq_conta_proc	= pns_2.nr_seq_conta_proc or
			pns.nr_seq_conta_mat	= pns_2.nr_seq_conta_mat));

-- retorna os itens que serão unificados para ser excluidos
c02 CURSOR(	nr_seq_nota_cobr_pc	ptu_nota_cobranca.nr_sequencia%type,
		nr_seq_fatura_pc	pls_fatura.nr_sequencia%type,
		nr_seq_pls_fatura_pc	pls_fatura.nr_sequencia%type,
		cd_procedimento_pc	ptu_nota_servico.cd_procedimento%type,
		nr_seq_conta_proc_pc	ptu_nota_servico.nr_seq_conta_proc%type,
		nr_seq_conta_mat_pc	ptu_nota_servico.nr_seq_conta_mat%type) FOR
	SELECT	pns_2.oid,
		pns_2.*
	from	ptu_nota_servico  pns_2,
		ptu_nota_cobranca pnc_2,
		ptu_fatura        pf_2,
		pls_fatura        plf_2
	where	pnc_2.nr_sequencia	= pns_2.nr_seq_nota_cobr
	and	pf_2.nr_sequencia	= pnc_2.nr_seq_fatura
	and	plf_2.nr_sequencia	= pf_2.nr_seq_pls_fatura
	and	pns_2.vl_procedimento	= 0
	and	plf_2.nr_sequencia	= nr_seq_fatura_p
	and	pnc_2.nr_sequencia	= nr_seq_nota_cobr_pc
	and	pf_2.nr_sequencia	= nr_seq_fatura_pc
	and	plf_2.nr_sequencia	= nr_seq_pls_fatura_pc
	and	cd_procedimento_pc	= pns_2.cd_procedimento
	and	((nr_seq_conta_proc_pc	= pns_2.nr_seq_conta_proc) or (nr_seq_conta_mat_pc	= pns_2.nr_seq_conta_mat));

BEGIN

for r_c01_w in c01 loop

	for r_c02_w in c02(r_c01_w.nr_seq_nota_cobr,
			r_c01_w.nr_seq_fatura,
			r_c01_w.nr_seq_pls_fatura,
			r_c01_w.cd_procedimento,
			r_c01_w.nr_seq_conta_proc,
			r_c01_w.nr_seq_conta_mat) loop
    
		-- atualiza os valores da nota serviço com valor
		update ptu_nota_servico pts
		set pts.vl_procedimento		= coalesce(pts.vl_procedimento, 0) + coalesce(r_c02_w.vl_procedimento, 0),
		pts.vl_custo_operacional	= coalesce(pts.vl_custo_operacional, 0) + coalesce(r_c02_w.vl_custo_operacional, 0),
		pts.vl_filme			= coalesce(pts.vl_filme, 0) + coalesce(r_c02_w.vl_filme, 0),
		pts.vl_adic_procedimento	= coalesce(pts.vl_adic_procedimento, 0) + coalesce(r_c02_w.vl_adic_procedimento, 0),
		pts.vl_adic_co			= coalesce(pts.vl_adic_co, 0) + coalesce(r_c02_w.vl_adic_co, 0),
		pts.vl_adic_filme		= coalesce(pts.vl_adic_filme, 0) + coalesce(r_c02_w.vl_adic_filme, 0),
		pts.vl_pago_prest		= coalesce(pts.vl_pago_prest, 0) + coalesce(r_c02_w.vl_pago_prest, 0)
		where pts.rowid			= r_c01_w.rowid;

		-- apaga as informações das tabelas filhas da ptu_nota_serviço
		delete from ptu_nota_servico_item pnsi	where pnsi.nr_seq_nota_servico = r_c02_w.nr_sequencia;
		delete from ptu_nota_servico_mat pnsm 	where pnsm.nr_seq_nota_servico = r_c02_w.nr_sequencia;
		delete from ptu_nota_servico_proc pnsp	where pnsp.nr_seq_nota_servico = r_c02_w.nr_sequencia;

		delete from ptu_nota_servico pts2	where pts2.rowid = r_c02_w.rowid;

	end loop;

end loop;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE pls_atu_valor_servico ( nr_seq_fatura_p pls_fatura.nr_sequencia%type) FROM PUBLIC;

