-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE recist_inserir_localizacao ( ds_localizacao_p text, IE_MENSURAR_p text, NR_SEQ_REGISTRO_p bigint, nm_usuario_p text) AS $body$
BEGIN

insert into RECIST_LOCALIZACAO(
			 NR_SEQUENCIA,
			 DT_ATUALIZACAO,
			 NM_USUARIO,
			 DT_ATUALIZACAO_NREC,
			 NM_USUARIO_NREC,
			 NR_SEQ_REGISTRO,
			 DS_LOCALIZACAO,
			 IE_MENSURAR)
		values (
			 nextval('recist_localizacao_seq'),
			 clock_timestamp(),
			 nm_usuario_p,
			 clock_timestamp(),
			 nm_usuario_p,
			 NR_SEQ_REGISTRO_p,
			 ds_localizacao_p,
			 IE_MENSURAR_p);



commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE recist_inserir_localizacao ( ds_localizacao_p text, IE_MENSURAR_p text, NR_SEQ_REGISTRO_p bigint, nm_usuario_p text) FROM PUBLIC;

