-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE registar_avaliacao_medic_cih ( nr_prescricao_p bigint, nr_seq_prescricao_p bigint, ie_aval_antibiotico_p text, nm_usuario_p text, cd_estabelecimento_p bigint) AS $body$
BEGIN

if (nr_prescricao_p IS NOT NULL AND nr_prescricao_p::text <> '') then
	update	prescr_material
	set	IE_AVAL_ANTIBIOTICO	=	ie_aval_antibiotico_p
	where	nr_prescricao		=	nr_prescricao_p
	and 	nr_sequencia		=	nr_seq_prescricao_p;
end if;

commit;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE registar_avaliacao_medic_cih ( nr_prescricao_p bigint, nr_seq_prescricao_p bigint, ie_aval_antibiotico_p text, nm_usuario_p text, cd_estabelecimento_p bigint) FROM PUBLIC;

