-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE update_dt_geracao_acc_files ( nr_sequencia_p ACCOUNTING_FILES.NR_SEQUENCIA%type ) AS $body$
DECLARE

  dt_atual_s      CONSTANT ACCOUNTING_FILES.DT_GENERATION%type := clock_timestamp();

BEGIN

IF (nr_sequencia_p IS NOT NULL AND nr_sequencia_p::text <> '') THEN
	UPDATE  ACCOUNTING_FILES
	SET     DT_GENERATION = dt_atual_s
	WHERE   NR_SEQUENCIA = nr_sequencia_p;
END IF;

COMMIT;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE update_dt_geracao_acc_files ( nr_sequencia_p ACCOUNTING_FILES.NR_SEQUENCIA%type ) FROM PUBLIC;

