-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE PROCEDURE virada_saldo_import ( DT_MESANO_REFERENCIA_P timestamp, CD_ESTABELECIMENTO_P bigint, NM_USUARIO_P text) AS $body$
DECLARE


CD_ESTABELECIMENTO_W			smallint	:= 0;
CD_LOCAL_ESTOQUE_W 			smallint	:= 0;
CD_MATERIAL_W				integer	:= 0;
NM_USUARIO_W				varchar(15);
QT_ESTOQUE_W				double precision    := 0;
VL_ESTOQUE_W				double precision    := 0;
VL_CUSTO_MEDIO_W			double precision;
VL_PRECO_ULT_COMPRA_W		double precision;
DT_ULT_COMPRA_W			timestamp;
IE_ERRO_W				varchar(1);
cd_fornecedor_w			varchar(14);
nr_seq_lote_w				bigint;
ds_erro_w				varchar(255);
dt_mes_base_w				timestamp;
dt_novo_mes_w				timestamp;
qt_reg_base_w				bigint;
qt_reg_ant_w				bigint;
qt_reg_pos_w				bigint;


/*
ESTA PROCEDURE DEVE SER UTILIZADA SOMENTE PARA IMPORTAÇOES DE SALDO
BUSCA OS SALDOS DO MES E IDENTIFICA SE NAO EXISTE REGISTRO NO PROXIMO MES - SE NAO EXISTIR LEVA OS SALDOS.....
*/
c01 CURSOR FOR
SELECT	cd_estabelecimento,
	cd_local_estoque,
	cd_material,
	qt_estoque,
	vl_estoque,
	vl_custo_medio,
	vl_preco_ult_compra,
	dt_ult_compra
from	saldo_estoque a
where	dt_mesano_referencia = dt_mes_base_w
and	cd_estabelecimento = cd_estabelecimento_p
and	not exists (
	SELECT	1
	from	saldo_estoque b
	where	b.cd_estabelecimento	= a.cd_estabelecimento
	and	b.cd_local_estoque	= a.cd_local_estoque
	and	b.cd_material		= a.cd_material
	and	b.dt_mesano_referencia	= dt_novo_mes_w);



BEGIN

dt_mes_base_w				:= pkg_date_utils.start_of(pkg_date_utils.add_month(DT_MESANO_REFERENCIA_P,-1,0),'MONTH',0);
dt_novo_mes_w				:= pkg_date_utils.start_of(DT_MESANO_REFERENCIA_P,'MONTH',0);
OPEN C01;
LOOP
FETCH C01 into
	cd_estabelecimento_w,
	cd_local_estoque_w,
	cd_material_w,
	qt_estoque_w,
	vl_estoque_w,
	vl_custo_medio_w,
	vl_preco_ult_compra_w,
	dt_ult_compra_w;
EXIT WHEN NOT FOUND; /* apply on C01 */
	begin
	insert into saldo_estoque(
		cd_estabelecimento,
		cd_local_estoque,
		cd_material,
		dt_mesano_referencia,
		qt_estoque,
		vl_estoque,
		qt_reservada_requisicao,
		qt_reservada,
		dt_atualizacao,
		nm_usuario,
		vl_custo_medio,
		vl_preco_ult_compra,
		dt_ult_compra,
		ie_bloqueio_inventario)
	values (cd_estabelecimento_w,
		cd_local_estoque_w,
		cd_material_w,
		dt_novo_mes_w,
		qt_estoque_w,
		vl_estoque_w,
		0,
		0,
		clock_timestamp(),
		nm_usuario_p,
		vl_custo_medio_w,
		vl_preco_ult_compra_w,
		dt_ult_compra_w,
		'N');
	end;
END LOOP;
close C01;

commit;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE virada_saldo_import ( DT_MESANO_REFERENCIA_P timestamp, CD_ESTABELECIMENTO_P bigint, NM_USUARIO_P text) FROM PUBLIC;

