-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';




CREATE OR REPLACE PROCEDURE pls_entao_regra_preco_cta_pck.obter_valores_amb ( ie_destino_regra_p text, cd_edicao_amb_p pls_cp_cta_eproc.cd_edicao_amb%type, vl_tx_honorarios_p pls_cp_cta_eproc.vl_ch_honorarios%type, vl_tx_custo_oper_p pls_cp_cta_eproc.vl_ch_custo_oper%type, vl_filme_p pls_cp_cta_eproc.vl_filme%type, tx_ajuste_ch_honor_p pls_cp_cta_eproc.tx_ajuste_ch_honor%type, tx_ajuste_custo_oper_p pls_cp_cta_eproc.tx_ajuste_custo_oper%type, tx_ajuste_filme_p pls_cp_cta_eproc.tx_ajuste_filme%type, dt_proced_referencia_p pls_conta_proc.dt_procedimento_referencia%type, cd_procedimento_p pls_conta_proc.cd_procedimento%type, vl_moeda_filme_p pls_cp_cta_eproc.cd_moeda_filme%type, ie_ch_padrao_anest_p pls_cp_cta_eproc.ie_ch_padrao_anestesista%type, vl_moeda_anestesista_p pls_cp_cta_eproc.cd_moeda_anestesista%type, tx_ajuste_partic_p pls_cp_cta_eproc.tx_ajuste_partic%type, nr_seq_conta_proc_p pls_conta_proc.nr_sequencia%type, nm_usuario_p usuario.nm_usuario%type, vl_procedimento_p INOUT bigint, vl_custo_operacional_p INOUT bigint, vl_medico_p INOUT bigint, vl_anestesista_p INOUT bigint, vl_auxiliares_p INOUT bigint, vl_filme_amb_p INOUT bigint, nr_porte_anestesico_p INOUT preco_tuss.nr_porte_anest_amb%type, nr_auxiliares_p INOUT preco_amb.nr_auxiliares%type, qt_filme_p INOUT preco_amb.qt_filme%type) AS $body$
DECLARE


val_tab_amb_w	tipo_val_tab_amb := tipo_val_tab_amb(null, null, null, null, null, null, null, null, null);


BEGIN

-- obtem os valores AMB
val_tab_amb_w := pls_obter_val_tab_amb(	cd_edicao_amb_p, dt_proced_referencia_p, cd_procedimento_p,
					vl_filme_p);

CALL pls_entao_regra_preco_cta_pck.gerencia_log_proc(	'Valores obtidos na tabela de preços AMB.',
			nr_seq_conta_proc_p,
			val_tab_amb_w.vl_anestesista,
			val_tab_amb_w.vl_auxiliares_amb,
			val_tab_amb_w.vl_custo_operacional,
			val_tab_amb_w.vl_filme,
			val_tab_amb_w.vl_medico,
			val_tab_amb_w.vl_procedimento,
			ie_destino_regra_p,
			nm_usuario_p);

-- aplica as taxas/moedas pertinentes ao calculo AMB
SELECT * FROM pls_entao_regra_preco_cta_pck.aplica_taxas_amb(	vl_tx_custo_oper_p, vl_tx_honorarios_p, vl_moeda_filme_p, tx_ajuste_custo_oper_p, tx_ajuste_ch_honor_p, tx_ajuste_filme_p, val_tab_amb_w.vl_custo_operacional, val_tab_amb_w.vl_medico, val_tab_amb_w.vl_filme) INTO STRICT val_tab_amb_w.vl_custo_operacional, val_tab_amb_w.vl_medico, val_tab_amb_w.vl_filme;

CALL pls_entao_regra_preco_cta_pck.gerencia_log_proc(	'Valores após aplicar cotação de moeda e/ou taxas.',
			nr_seq_conta_proc_p,
			val_tab_amb_w.vl_anestesista,
			val_tab_amb_w.vl_auxiliares_amb,
			val_tab_amb_w.vl_custo_operacional,
			val_tab_amb_w.vl_filme,
			val_tab_amb_w.vl_medico,
			val_tab_amb_w.vl_procedimento,
			ie_destino_regra_p,
			nm_usuario_p);

-- obtém o valor correto do anestesista quando AMB
val_tab_amb_w.vl_anestesista := pls_entao_regra_preco_cta_pck.obter_valor_anest_amb(	cd_edicao_amb_p, val_tab_amb_w.nr_porte_anestesico,
							dt_proced_referencia_p, val_tab_amb_w.vl_anestesista,
							ie_ch_padrao_anest_p, vl_moeda_anestesista_p,
							tx_ajuste_partic_p, vl_tx_honorarios_p);

CALL pls_entao_regra_preco_cta_pck.gerencia_log_proc(	'Obtido valor do anestesista de acordo com o porte anestésico e aplicado as taxas pertinentes.',
			nr_seq_conta_proc_p,
			val_tab_amb_w.vl_anestesista,
			val_tab_amb_w.vl_auxiliares_amb,
			val_tab_amb_w.vl_custo_operacional,
			val_tab_amb_w.vl_filme,
			val_tab_amb_w.vl_medico,
			val_tab_amb_w.vl_procedimento,
			ie_destino_regra_p,
			nm_usuario_p);

-- faz o calculo do valor do procedimento, basicamente é somado todos os valores que compoem o mesmo
-- colocado em uma function própria para facilitar a manutenção da package
val_tab_amb_w.vl_procedimento := pls_entao_regra_preco_cta_pck.obter_valor_proced(	val_tab_amb_w.vl_custo_operacional, val_tab_amb_w.vl_anestesista,
							val_tab_amb_w.vl_medico, val_tab_amb_w.vl_filme,
							val_tab_amb_w.vl_auxiliares_amb);

CALL pls_entao_regra_preco_cta_pck.gerencia_log_proc(	'Realizado o cálculo do valor do procedimento.',
			nr_seq_conta_proc_p,
			val_tab_amb_w.vl_anestesista,
			val_tab_amb_w.vl_auxiliares_amb,
			val_tab_amb_w.vl_custo_operacional,
			val_tab_amb_w.vl_filme,
			val_tab_amb_w.vl_medico,
			val_tab_amb_w.vl_procedimento,
			ie_destino_regra_p,
			nm_usuario_p);

-- alimenta as variáveis out, feito desta maneira para facilitar a manutenção da rotina
vl_procedimento_p := val_tab_amb_w.vl_procedimento;
vl_custo_operacional_p := val_tab_amb_w.vl_custo_operacional;
vl_medico_p := val_tab_amb_w.vl_medico;
vl_anestesista_p := val_tab_amb_w.vl_anestesista;
vl_auxiliares_p := val_tab_amb_w.vl_auxiliares_amb;
nr_porte_anestesico_p := val_tab_amb_w.nr_porte_anestesico;
vl_filme_amb_p := val_tab_amb_w.vl_filme;
nr_auxiliares_p := val_tab_amb_w.nr_auxiliares;
qt_filme_p := val_tab_amb_w.qt_filme;

END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE pls_entao_regra_preco_cta_pck.obter_valores_amb ( ie_destino_regra_p text, cd_edicao_amb_p pls_cp_cta_eproc.cd_edicao_amb%type, vl_tx_honorarios_p pls_cp_cta_eproc.vl_ch_honorarios%type, vl_tx_custo_oper_p pls_cp_cta_eproc.vl_ch_custo_oper%type, vl_filme_p pls_cp_cta_eproc.vl_filme%type, tx_ajuste_ch_honor_p pls_cp_cta_eproc.tx_ajuste_ch_honor%type, tx_ajuste_custo_oper_p pls_cp_cta_eproc.tx_ajuste_custo_oper%type, tx_ajuste_filme_p pls_cp_cta_eproc.tx_ajuste_filme%type, dt_proced_referencia_p pls_conta_proc.dt_procedimento_referencia%type, cd_procedimento_p pls_conta_proc.cd_procedimento%type, vl_moeda_filme_p pls_cp_cta_eproc.cd_moeda_filme%type, ie_ch_padrao_anest_p pls_cp_cta_eproc.ie_ch_padrao_anestesista%type, vl_moeda_anestesista_p pls_cp_cta_eproc.cd_moeda_anestesista%type, tx_ajuste_partic_p pls_cp_cta_eproc.tx_ajuste_partic%type, nr_seq_conta_proc_p pls_conta_proc.nr_sequencia%type, nm_usuario_p usuario.nm_usuario%type, vl_procedimento_p INOUT bigint, vl_custo_operacional_p INOUT bigint, vl_medico_p INOUT bigint, vl_anestesista_p INOUT bigint, vl_auxiliares_p INOUT bigint, vl_filme_amb_p INOUT bigint, nr_porte_anestesico_p INOUT preco_tuss.nr_porte_anest_amb%type, nr_auxiliares_p INOUT preco_amb.nr_auxiliares%type, qt_filme_p INOUT preco_amb.qt_filme%type) FROM PUBLIC;
