-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';




CREATE OR REPLACE PROCEDURE plt_gerar_horarios_pck.plt_obter_horarios_hemoterap ( cd_estabelecimento_p bigint, cd_setor_usuario_p bigint, cd_perfil_p bigint, nm_usuario_p text, nr_atendimento_p bigint, dt_inicial_horarios_p timestamp, dt_final_horarios_p timestamp, dt_validade_limite_p timestamp, ie_prescr_usuario_p text, ie_edicao_p text, ie_estendidos_p bigint, dt_referencia_p timestamp, ie_exibir_hor_suspensos_p text, dt_plano_p text) AS $body$
DECLARE

						
	dt_horario_w		timestamp;
	dt_fim_w		timestamp;
	
	
	c01 REFCURSOR;
	c02 REFCURSOR;
		
	tb_datas_w	dbms_sql.date_table;
		
	
BEGIN
	dt_fim_w	:= dt_validade_limite_p + 5;
	
	if (nr_atendimento_p IS NOT NULL AND nr_atendimento_p::text <> '') then
		open	c01 for
		SELECT	trunc(t.dt_status,'mi')
		from	(SELECT	x.dt_status,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	prescr_procedimento x,
						prescr_medica a
				where	x.nr_prescricao = a.nr_prescricao
				and		a.nr_atendimento = nr_atendimento_p		
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w	
				and		coalesce(x.nr_seq_proc_interno::text, '') = ''
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and		plt_gerar_horarios_pck.obter_se_mostra_rep_inter(a.ie_motivo_prescricao) = 'S'
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		(x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '')
				and		coalesce(x.nr_seq_exame_sangue::text, '') = ''
				and		x.ie_status in ('P','N')
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM',
																								cd_estabelecimento_p, 
																								cd_setor_usuario_p, 
																								cd_perfil_p, 
																								null, 
																								x.cd_procedimento, 
																								x.ie_origem_proced, 
																								x.nr_seq_proc_interno,
																								a.cd_setor_Atendimento,
																								x.cd_setor_atendimento,
																								null,
																								x.nr_seq_exame) = 'S')))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_status,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,		'H') = 'S'
		group by
			t.dt_status
		
union all

		select	trunc(t.dt_status,'mi')
		from	(select	x.dt_status,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	proc_interno w,
						prescr_procedimento x,
						prescr_medica a
				where	w.nr_sequencia = x.nr_seq_proc_interno
				and		x.nr_prescricao = a.nr_prescricao
				and		a.nr_atendimento = nr_atendimento_p				
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w	
				and		w.ie_tipo <> 'G'
				and		coalesce(w.ie_ivc,'N') <> 'S'
				and		coalesce(w.ie_ctrl_glic,'NC') = 'NC'
				and		(x.nr_seq_proc_interno IS NOT NULL AND x.nr_seq_proc_interno::text <> '')
				and		coalesce(x.nr_seq_prot_glic::text, '') = ''
				and		PLT_Gerar_Horarios_PCK.OBTER_SE_MOSTRA_REP_INTER(a.ie_motivo_prescricao) = 'S'
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'PH') = 'S'))
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'AT') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BS') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'ST') = 'S'))
				and		x.ie_status in ('P','N')
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM', 
																								cd_estabelecimento_p, 
																								cd_setor_usuario_p, 
																								cd_perfil_p, 
																								null, 
																								x.cd_procedimento, 
																								x.ie_origem_proced, 
																								x.nr_seq_proc_interno,
																								a.cd_setor_Atendimento,
																								x.cd_setor_atendimento,
																								null,
																								x.nr_seq_exame) = 'S')))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_status,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,		'H') = 'S'
		group by
			t.dt_status;

			
		open	c02 for
		SELECT	t.dt_horario
		from	(SELECT	c.dt_horario,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	prescr_procedimento x,
						prescr_proc_hor c,
						prescr_medica a
				where	x.nr_prescricao = c.nr_prescricao
				and		x.nr_sequencia = c.nr_seq_procedimento
				and		x.nr_prescricao = a.nr_prescricao
				and		c.nr_prescricao = a.nr_prescricao
				and		a.nr_atendimento = nr_atendimento_p
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w	
				and		coalesce(x.nr_seq_proc_interno::text, '') = ''
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and 	coalesce(x.nr_Seq_origem::text, '') = ''
				and		plt_gerar_horarios_pck.obter_se_mostra_rep_inter(a.ie_motivo_prescricao) = 'S'
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		coalesce(c.ie_situacao,'A') = 'A'
				and		((coalesce(c.ie_horario_especial,'N') = 'N') or (c.dt_fim_horario IS NOT NULL AND c.dt_fim_horario::text <> ''))
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM',
																								cd_estabelecimento_p, 
																								cd_setor_usuario_p, 
																								cd_perfil_p, 
																								null, 
																								x.cd_procedimento, 
																								x.ie_origem_proced, 
																								x.nr_seq_proc_interno,
																								a.cd_setor_Atendimento,
																								x.cd_setor_atendimento,
																								null,
																								x.nr_seq_exame) = 'S')))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_horario,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,		'H') = 'S'
		group by
			t.dt_horario	 
		
union all

		select	t.dt_horario
		from	(select	c.dt_horario,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	proc_interno w,
						prescr_procedimento x,
						prescr_proc_hor c,
						prescr_medica a
				where	w.nr_sequencia = x.nr_seq_proc_interno
				and		w.nr_sequencia = c.nr_seq_proc_interno
				and		x.nr_prescricao = c.nr_prescricao
				and		x.nr_sequencia = c.nr_seq_procedimento
				and		x.nr_prescricao = a.nr_prescricao
				and		c.nr_prescricao = a.nr_prescricao
				and		a.nr_atendimento = nr_atendimento_p				
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w	
				and		w.ie_tipo <> 'G'
				and		coalesce(w.ie_ivc,'N') <> 'S'
				and		coalesce(w.ie_ctrl_glic,'NC') = 'NC'
				and		(x.nr_seq_proc_interno IS NOT NULL AND x.nr_seq_proc_interno::text <> '')
				and		coalesce(x.nr_seq_prot_glic::text, '') = ''
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		PLT_Gerar_Horarios_PCK.OBTER_SE_MOSTRA_REP_INTER(a.ie_motivo_prescricao) = 'S'
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'PH') = 'S'))
				and 	coalesce(x.nr_Seq_origem::text, '') = ''
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'AT') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BS') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'ST') = 'S'))
				and		coalesce(c.ie_situacao,'A') = 'A'
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM', 
																								cd_estabelecimento_p, 
																								cd_setor_usuario_p, 
																								cd_perfil_p, 
																								null, 
																								x.cd_procedimento, 
																								x.ie_origem_proced, 
																								x.nr_seq_proc_interno,
																								a.cd_setor_Atendimento,
																								x.cd_setor_atendimento,
																								null,
																								x.nr_seq_exame) = 'S')))
				and		((coalesce(c.ie_horario_especial,'N') = 'N') or (c.dt_fim_horario IS NOT NULL AND c.dt_fim_horario::text <> ''))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_horario,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,		'H') = 'S'
		group by
			t.dt_horario;	
	else
		open	c01 for
		SELECT	trunc(t.dt_status,'mi')
		from	(SELECT	x.dt_status,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	prescr_procedimento x,
						prescr_medica a
				where	x.nr_prescricao = a.nr_prescricao
				and		a.cd_pessoa_fisica = current_setting('plt_gerar_horarios_pck.cd_pessoa_fisica_w')::varchar(10)
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w	
				and		coalesce(x.nr_seq_proc_interno::text, '') = ''				
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		(x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '')
				and		coalesce(x.nr_seq_exame_sangue::text, '') = ''
				and		PLT_Gerar_Horarios_PCK.OBTER_SE_MOSTRA_REP_INTER(a.ie_motivo_prescricao) = 'S'
				and		x.ie_status in ('P','N')
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM',
																								cd_estabelecimento_p, 
																								cd_setor_usuario_p, 
																								cd_perfil_p, 
																								null, 
																								x.cd_procedimento, 
																								x.ie_origem_proced, 
																								x.nr_seq_proc_interno,
																								a.cd_setor_Atendimento,
																								x.cd_setor_atendimento,
																								null,
																								x.nr_seq_exame) = 'S')))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_status,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,		'H') = 'S'
		group by
			t.dt_status
		
union all

		select	trunc(t.dt_status,'mi')
		from	(select	x.dt_status,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	proc_interno w,
						prescr_procedimento x,
						prescr_medica a
				where	w.nr_sequencia = x.nr_seq_proc_interno
				and		x.nr_prescricao = a.nr_prescricao
				and		a.cd_pessoa_fisica = current_setting('plt_gerar_horarios_pck.cd_pessoa_fisica_w')::varchar(10)
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w	
				and		w.ie_tipo <> 'G'				
				and		coalesce(w.ie_ivc,'N') <> 'S'
				and		coalesce(w.ie_ctrl_glic,'NC') = 'NC'
				and		(x.nr_seq_proc_interno IS NOT NULL AND x.nr_seq_proc_interno::text <> '')
				and		coalesce(x.nr_seq_prot_glic::text, '') = ''
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		plt_gerar_horarios_pck.obter_se_mostra_rep_inter(a.ie_motivo_prescricao) = 'S'
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'PH') = 'S'))
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'AT') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BS') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'ST') = 'S'))
				and		x.ie_status in ('P','N')
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM', 
																							cd_estabelecimento_p, 
																							cd_setor_usuario_p, 
																							cd_perfil_p, 
																							null, 
																							x.cd_procedimento, 
																							x.ie_origem_proced, 
																							x.nr_seq_proc_interno,
																							a.cd_setor_Atendimento,
																							x.cd_setor_atendimento,
																							null,
																							x.nr_seq_exame) = 'S')))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_status,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,		'H') = 'S'
		group by
			t.dt_status;

			
		open	c02 for
		SELECT	t.dt_horario
		from	(SELECT	c.dt_horario,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	prescr_procedimento x,
						prescr_proc_hor c,
						prescr_medica a
				where	x.nr_prescricao = c.nr_prescricao
				and		x.nr_sequencia = c.nr_seq_procedimento
				and		x.nr_prescricao = a.nr_prescricao
				and		c.nr_prescricao = a.nr_prescricao
				and		a.cd_pessoa_fisica = current_setting('plt_gerar_horarios_pck.cd_pessoa_fisica_w')::varchar(10)
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w
				and		coalesce(x.nr_seq_proc_interno::text, '') = ''
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and 	coalesce(x.nr_Seq_origem::text, '') = ''
				and		plt_gerar_horarios_pck.obter_se_mostra_rep_inter(a.ie_motivo_prescricao) = 'S'
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S'))
				and		coalesce(c.ie_situacao,'A') = 'A'
				and		((coalesce(c.ie_horario_especial,'N') = 'N') or (c.dt_fim_horario IS NOT NULL AND c.dt_fim_horario::text <> ''))
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM',
																								cd_estabelecimento_p, 
																								cd_setor_usuario_p, 
																								cd_perfil_p, 
																								null, 
																								x.cd_procedimento, 
																								x.ie_origem_proced, 
																								x.nr_seq_proc_interno,
																								a.cd_setor_Atendimento,
																								x.cd_setor_atendimento,
																								null, 
																								x.nr_seq_exame) = 'S')))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_horario,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,	'H') = 'S'
		group by
			t.dt_horario	 
		
union all

		select	t.dt_horario
		from	(select	c.dt_horario,
						x.nr_sequencia,
						x.nr_prescricao,
						x.dt_suspensao
				from	proc_interno w,
						prescr_procedimento x,
						prescr_proc_hor c,
						prescr_medica a
				where	w.nr_sequencia = x.nr_seq_proc_interno
				and		w.nr_sequencia = c.nr_seq_proc_interno
				and		x.nr_prescricao = c.nr_prescricao
				and		x.nr_sequencia = c.nr_seq_procedimento
				and		x.nr_prescricao = a.nr_prescricao
				and		c.nr_prescricao = a.nr_prescricao				
				and		a.cd_pessoa_fisica = current_setting('plt_gerar_horarios_pck.cd_pessoa_fisica_w')::varchar(10)
				and		a.nr_prescricao	between current_setting('plt_gerar_horarios_pck.nr_prescr_inicial_w')::bigint	and current_setting('plt_gerar_horarios_pck.nr_prescr_final_w')::bigint
				and		a.dt_validade_prescr	between dt_validade_limite_p	and dt_fim_w	
				and		w.ie_tipo <> 'G'
				and		coalesce(w.ie_ivc,'N') <> 'S'
				and		coalesce(w.ie_ctrl_glic,'NC') = 'NC'
				and		(x.nr_seq_proc_interno IS NOT NULL AND x.nr_seq_proc_interno::text <> '')
				and		coalesce(x.nr_seq_prot_glic::text, '') = ''
				and		coalesce(x.nr_seq_exame::text, '') = ''
				and		PLT_Gerar_Horarios_PCK.OBTER_SE_MOSTRA_REP_INTER(a.ie_motivo_prescricao) = 'S'
				and		(x.nr_seq_solic_sangue IS NOT NULL AND x.nr_seq_solic_sangue::text <> '')
				and		((x.nr_seq_derivado IS NOT NULL AND x.nr_seq_derivado::text <> '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'PH') = 'S'))
				and 	coalesce(x.nr_Seq_origem::text, '') = ''
				and		((coalesce(x.nr_seq_exame_sangue::text, '') = '') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'AT') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BSST') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'BS') = 'S') or (Obter_se_exibe_proced(x.nr_prescricao,x.nr_sequencia,x.ie_tipo_proced,'ST') = 'S'))
				and		coalesce(c.ie_situacao,'A') = 'A'
				and		((coalesce(c.ie_horario_especial,'N') = 'N') or (c.dt_fim_horario IS NOT NULL AND c.dt_fim_horario::text <> ''))
				and		((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'S') or
						((current_setting('plt_gerar_horarios_pck.ie_regra_incl_hemoterapia_w')::char(1) = 'R') and (adep_obter_regra_inclusao(	'HM', 
																								cd_estabelecimento_p, 
																								cd_setor_usuario_p, 
																								cd_perfil_p, 
																								null, 
																								x.cd_procedimento, 
																								x.ie_origem_proced, 
																								x.nr_seq_proc_interno,
																								a.cd_setor_Atendimento,
																								x.cd_setor_atendimento,
																								null,
																								x.nr_seq_exame) = 'S')))) t
		where	plt_obter_se_item_periodo(	dt_validade_limite_p,		dt_fim_w,				get_ie_plano_por_setor,		dt_plano_p,			t.dt_horario,
											dt_inicial_horarios_p,		dt_final_horarios_p,	ie_prescr_usuario_p,		nm_usuario_p,		ie_estendidos_p,
											dt_referencia_p,			ie_edicao_p,			ie_exibir_hor_suspensos_p,	t.dt_suspensao,		'HM',
											t.nr_sequencia,				t.nr_prescricao,		'H') = 'S'
		group by
			t.dt_horario;
	end if;
	
	if (coalesce(get_ie_utiliza_hem_p_hor,'N') <> 'S') then
		loop
		fetch C01 bulk collect into tb_datas_w
		limit 100;
		exit when tb_datas_w.count = 0;
			begin
			forall i in tb_datas_w.first..tb_datas_w.last
				
				insert into w_rep_horarios_t(	nm_usuario,
												dt_horario)
											values (
												nm_usuario_p,
												tb_datas_w(i));
				commit;
			end;
		end loop;
		close c01;
	else
		loop
		fetch C02 bulk collect into tb_datas_w
		limit 100;
		exit when tb_datas_w.count = 0;
			begin
			forall i in tb_datas_w.first..tb_datas_w.last
				
				insert into w_rep_horarios_t(	nm_usuario,
												dt_horario)
											values (
												nm_usuario_p,
												tb_datas_w(i));
				commit;
			end;
		end loop;
		close c02;
	end if;
	END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE plt_gerar_horarios_pck.plt_obter_horarios_hemoterap ( cd_estabelecimento_p bigint, cd_setor_usuario_p bigint, cd_perfil_p bigint, nm_usuario_p text, nr_atendimento_p bigint, dt_inicial_horarios_p timestamp, dt_final_horarios_p timestamp, dt_validade_limite_p timestamp, ie_prescr_usuario_p text, ie_edicao_p text, ie_estendidos_p bigint, dt_referencia_p timestamp, ie_exibir_hor_suspensos_p text, dt_plano_p text) FROM PUBLIC;
