-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION bsc_obter_capacidade_prod (dt_inicial_p timestamp, dt_final_p timestamp) RETURNS bigint AS $body$
DECLARE



pr_capacidade_w		double precision;


BEGIN

SELECT 	round((SUM(media)/COUNT(*) * 100/528)::numeric,2) Perc_Capac_Produ
into STRICT	pr_capacidade_w
FROM
(SELECT nm_usuario_exec,
	   (qt_minuto / (obter_dias_uteis_periodo(TRUNC(dt_inicial_p,'mm'), dt_final_p,1))) media
FROM (SELECT b.nm_usuario_exec,
	        SUM(b.qt_minuto) qt_minuto
	 FROM   MAN_ORDEM_SERVICO a,
	        MAN_ORDEM_SERV_ATIV b,
            usuario c
     WHERE  a.nr_sequencia = b.nr_seq_ordem_serv
     AND	c.nm_usuario   = b.nm_usuario_exec
     AND	c.cd_setor_atendimento in (2,7)
     AND	b.dt_atividade BETWEEN TRUNC(dt_inicial_p,'mm') AND dt_final_p
     GROUP BY b.nm_usuario_exec) alias11) alias12;

return pr_capacidade_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION bsc_obter_capacidade_prod (dt_inicial_p timestamp, dt_final_p timestamp) FROM PUBLIC;

