-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION busca_exames_realizados (nr_atendimento_p bigint) RETURNS varchar AS $body$
DECLARE


ds_retorno_w varchar(255) := null;
qtd_rel_rx  bigint;
qtd_rel_rm  bigint;
qtd_rel_tc  bigint;
qtd_rel_us  bigint;

BEGIN
  select count(1)
    into STRICT qtd_rel_rx
    from prescr_medica pm
   inner join prescr_procedimento pp on pp.nr_prescricao = pm.nr_prescricao and pp.ie_status_execucao >= '20'
   inner join proc_interno pi on pi.nr_sequencia = pp.nr_seq_proc_interno
   inner join procedimento p on p.cd_procedimento = pi.cd_procedimento and
                                p.ie_origem_proced = pi.ie_origem_proced and
                                p.cd_tipo_procedimento in(1, 34, 97, 156, 104)
   where pm.nr_atendimento = nr_atendimento_p;

  if (qtd_rel_rx > 0) then
    ds_retorno_w := obter_desc_expressao(948352)|| '(' || qtd_rel_rx || ')';
  end if;

  select count(1)
    into STRICT qtd_rel_rm
    from prescr_medica pm
   inner join prescr_procedimento pp on pp.nr_prescricao = pm.nr_prescricao and pp.ie_status_execucao >= '20'
   inner join proc_interno pi on pi.nr_sequencia = pp.nr_seq_proc_interno
   inner join procedimento p on p.cd_procedimento = pi.cd_procedimento and 
                                p.ie_origem_proced = pi.ie_origem_proced and
                                p.cd_tipo_procedimento in(4)
   where pm.nr_atendimento = nr_atendimento_p;

  if (qtd_rel_rm > 0) then
    if (coalesce(ds_retorno_w::text, '') = '') then
      ds_retorno_w := obter_desc_expressao(948350)|| '(' || qtd_rel_rm || ')';
    else
      ds_retorno_w := ds_retorno_w || ' ' || obter_desc_expressao(948350)|| '(' || qtd_rel_rm || ')';
    end if;
  end if;
  
  select count(1)
    into STRICT qtd_rel_tc
    from prescr_medica pm
   inner join prescr_procedimento pp on pp.nr_prescricao = pm.nr_prescricao and pp.ie_status_execucao >= '20'
   inner join proc_interno pi on pi.nr_sequencia = pp.nr_seq_proc_interno
   inner join procedimento p on p.cd_procedimento = pi.cd_procedimento and 
                                p.ie_origem_proced = pi.ie_origem_proced and
                                p.cd_tipo_procedimento in(3)
   where pm.nr_atendimento = nr_atendimento_p;

  if (qtd_rel_tc > 0) then
    if (coalesce(ds_retorno_w::text, '') = '') then
      ds_retorno_w := obter_desc_expressao(948356)|| '(' || qtd_rel_tc || ')';
    else
      ds_retorno_w := ds_retorno_w || ' ' || obter_desc_expressao(948356)|| '(' || qtd_rel_tc || ')';
    end if;
  end if;

  select count(1)
    into STRICT qtd_rel_us
    from prescr_medica pm
   inner join prescr_procedimento pp on pp.nr_prescricao = pm.nr_prescricao and pp.ie_status_execucao >= '20'
   inner join proc_interno pi on pi.nr_sequencia = pp.nr_seq_proc_interno
   inner join procedimento p on p.cd_procedimento = pi.cd_procedimento and 
                                p.ie_origem_proced = pi.ie_origem_proced and
                                p.cd_tipo_procedimento in(25, 2, 121)
   where pm.nr_atendimento = nr_atendimento_p;

  if (qtd_rel_us > 0) then
    if (coalesce(ds_retorno_w::text, '') = '') then
      ds_retorno_w := obter_desc_expressao(948348)|| '(' || qtd_rel_us || ')';
    else
      ds_retorno_w := ds_retorno_w || ' ' || obter_desc_expressao(948348)|| '(' || qtd_rel_us || ')';
    end if;
  end if;

  return ds_retorno_w;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION busca_exames_realizados (nr_atendimento_p bigint) FROM PUBLIC;

