-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION current_or_inactive_contract (nr_seq_terceiro_p TERCEIRO.nr_sequencia%type, nr_repasse_terceiro_p REPASSE_TERCEIRO.nr_repasse_terceiro%type) RETURNS bigint AS $body$
DECLARE


dt_mesano_referencia_w  REPASSE_TERCEIRO.dt_mesano_referencia%type;
cd_estabelecimento_w    REPASSE_TERCEIRO.cd_estabelecimento%type;
cd_estab_contrato_w     CONTRATO.cd_estabelecimento%type;
dt_inicio_contrato_w    CONTRATO.dt_inicio%type;
dt_fim_contrato_w       CONTRATO.dt_fim%type;
cd_estab_adic_w         CONTRATO_ESTAB_ADIC.cd_estab_adic%type;
ie_situacao_w           CONTRATO.ie_situacao%type;
cd_cgc_w	        TERCEIRO.cd_cgc%type;
nr_sequencia_w          CONTRATO.nr_sequencia%type;
ie_valid                smallint;

c01 CURSOR FOR
        SELECT  a.ie_situacao,
                a.dt_inicio,
                a.dt_fim,
                a.nr_sequencia,
                a.cd_estabelecimento
        from CONTRATO a
        where     a.cd_cgc_contratado = cd_cgc_w;

c01_w c01%rowtype;


BEGIN
ie_valid := 0;
begin
select  cd_cgc
into STRICT    cd_cgc_w
from    TERCEIRO
where   nr_sequencia = nr_seq_terceiro_p;

select  cd_estabelecimento,
        dt_mesano_referencia
into STRICT    cd_estabelecimento_w,
        dt_mesano_referencia_w
from    REPASSE_TERCEIRO
where   nr_repasse_terceiro = nr_repasse_terceiro_p;
exception
                when no_data_found then
                        cd_estab_adic_w := 0;
                when too_many_rows then
                        cd_estab_adic_w := 0;
end;
for c01_w in c01 loop
        begin

        dt_inicio_contrato_w    := c01_w.dt_inicio;
        cd_estab_contrato_w     := c01_w.cd_estabelecimento;
        dt_fim_contrato_w       := c01_w.dt_fim;
        nr_sequencia_w          := c01_w.nr_sequencia;
        ie_situacao_w           := c01_w.ie_situacao;

        begin
        select a.CD_ESTAB_ADIC
        into STRICT cd_estab_adic_w
        from CONTRATO_ESTAB_ADIC a
        where a.nr_seq_contrato = nr_sequencia_w
        and a.cd_estab_adic = cd_estabelecimento_w;
        exception
                when no_data_found then
                        cd_estab_adic_w := 0;
                when too_many_rows then
                        cd_estab_adic_w := 0;
        end;
        /*o estabelecimento do repasse e o mesmo do contrato?*/

        if (cd_estabelecimento_w = cd_estab_contrato_w) or (cd_estab_adic_w <> 0) then
                /*o contrato esta ativo?*/

                if (ie_situacao_w = 'A') then
                        /*o contrato esta vigente de acordo com a data de referencia do repasse?*/

                        if (dt_mesano_referencia_w BETWEEN dt_inicio_contrato_w and dt_fim_contrato_w) then
                                ie_valid := 1;
                                exit;
                        end if;
                end if;
        end if;
        end;
end loop;
return ie_valid;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION current_or_inactive_contract (nr_seq_terceiro_p TERCEIRO.nr_sequencia%type, nr_repasse_terceiro_p REPASSE_TERCEIRO.nr_repasse_terceiro%type) FROM PUBLIC;

