-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION des_obter_se_cliente_cobra_rel ( nr_seq_cliente_p bigint, ie_opcao_p text default 'R') RETURNS varchar AS $body$
DECLARE


/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Finalidade: Verificar se o cliente possui regra para que não seja cobrado relatório do mesmo.
-------------------------------------------------------------------------------------------------------------------
Locais de chamada direta:
[ X ]  Objetos do dicionário [  ] Tasy (Delphi/Java) [  ] Portal [  ]  Relatórios [ ] Outros:
 ------------------------------------------------------------------------------------------------------------------
Pontos de atenção:
-------------------------------------------------------------------------------------------------------------------
Referências:
	DES_DEFINIR_COMPLEX_RELAT_OS
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
ie_cobra_rel_w			varchar(1) := 'S';


BEGIN
begin
select	ie
into STRICT	ie_cobra_rel_w
from (SELECT	'N' ie
	from	des_excl_cobranca_rel_os
	where	nr_seq_cliente	= nr_seq_cliente_p
	and	clock_timestamp() between coalesce(dt_inicio_vigencia,clock_timestamp()) and coalesce(dt_fim_vigencia,clock_timestamp())
	and	ie_opcao_p = 'R'
	and	ie_relatorio = 'S'
	
union all

	SELECT	'N' ie
	from	des_excl_cobranca_rel_os
	where	nr_seq_cliente	= nr_seq_cliente_p
	and	clock_timestamp() between coalesce(dt_inicio_vigencia,clock_timestamp()) and coalesce(dt_fim_vigencia,clock_timestamp()) 
	and	ie_opcao_p = 'C'
	and	ie_customizacao_produto = 'S' LIMIT 1) alias10;
exception
when others then
	ie_cobra_rel_w := 'S';
end;

return ie_cobra_rel_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION des_obter_se_cliente_cobra_rel ( nr_seq_cliente_p bigint, ie_opcao_p text default 'R') FROM PUBLIC;

