-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION hd_obter_local_sessao_pac (cd_pessoa_fisica_p text, ie_opcao_p text, dt_sessao_p timestamp default clock_timestamp()) RETURNS varchar AS $body$
DECLARE

/*
DS - Descricao setor
DP - Descricao ponto
CS - Codigo Setor
CP - Codigo Ponto
*/
nr_seq_ponto_w	hd_escala_dialise_dia.nr_seq_ponto%type;
ds_retorno_w	varchar(255) := '';

BEGIN
if (cd_pessoa_fisica_p IS NOT NULL AND cd_pessoa_fisica_p::text <> '') and (dt_sessao_p IS NOT NULL AND dt_sessao_p::text <> '') and (ie_opcao_p IS NOT NULL AND ie_opcao_p::text <> '') then

	select	max(a.nr_seq_ponto)
	into STRICT	nr_seq_ponto_w
	from	hd_escala_dialise_dia a,
			hd_escala_dialise b
	where	b.cd_pessoa_fisica = cd_pessoa_fisica_p
	and		b.nr_sequencia = a.nr_seq_escala
	AND 	dt_sessao_p BETWEEN b.dt_inicio AND coalesce(b.dt_fim, dt_sessao_p)
    AND 	dt_sessao_p BETWEEN a.dt_inicio_escala_dia AND coalesce(a.dt_fim_escala_dia, dt_sessao_p)
	AND 	a.ie_dia_semana = obter_cod_dia_semana(dt_sessao_p);

	if (coalesce(nr_seq_ponto_w::text, '') = '') then
		select	max(nr_seq_ponto_acesso)
		into STRICT	nr_seq_ponto_w
		from	hd_pac_renal_cronico
		where	cd_pessoa_fisica = cd_pessoa_fisica_p;
	end if;

	if (nr_seq_ponto_w IS NOT NULL AND nr_seq_ponto_w::text <> '') THEN
   	CASE ie_opcao_p
         WHEN 'DS' THEN 
            select	max(b.ds_setor_atendimento)
              into STRICT	ds_retorno_w
              from	hd_ponto_acesso a,
                     setor_atendimento b
             where	a.cd_setor_atendimento = b.cd_setor_atendimento
               AND	a.nr_sequencia = nr_seq_ponto_w;

    		WHEN 'DP'  THEN
            select	max(ds_ponto_acesso)
              into STRICT	ds_retorno_w
              from	hd_ponto_acesso
             where	nr_sequencia = nr_seq_ponto_w;

			WHEN 'CP'  THEN   
       		ds_retorno_w := nr_seq_ponto_w;
   
       	WHEN 'CS'  THEN
            select	max(a.cd_setor_atendimento )
              into STRICT	ds_retorno_w
              from	hd_ponto_acesso a
             WHERE	a.nr_sequencia = nr_seq_ponto_w;
		END CASE;
	end if;
end if;
return	ds_retorno_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION hd_obter_local_sessao_pac (cd_pessoa_fisica_p text, ie_opcao_p text, dt_sessao_p timestamp default clock_timestamp()) FROM PUBLIC;

