-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION hd_obter_se_motivo_atend (nr_seq_queixa_p bigint) RETURNS varchar AS $body$
DECLARE


ds_retorno_w	varchar(1);

BEGIN


if (nr_seq_queixa_p IS NOT NULL AND nr_seq_queixa_p::text <> '') then
	select	coalesce(ie_hemodialise,'N')
	into STRICT	ds_retorno_w
	from	queixa_paciente
	where	nr_sequencia = nr_seq_queixa_p
	and coalesce(cd_estabelecimento,wheb_usuario_pck.get_cd_estabelecimento) = wheb_usuario_pck.get_cd_estabelecimento;
end if;


return	ds_retorno_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION hd_obter_se_motivo_atend (nr_seq_queixa_p bigint) FROM PUBLIC;

