-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION mprev_obter_status_pac_ag ( ie_evento_p text, dt_referencia_p timestamp) RETURNS bigint AS $body$
DECLARE


nr_seq_status_paciente_w			bigint;

c01 CURSOR FOR
	SELECT	nr_seq_status_paciente
	from	mprev_regra_status_agenda
	where   ((dt_referencia_p between dt_inicio_vigencia and dt_fim_vigencia) or (dt_referencia_p > dt_inicio_vigencia))
	and (ie_evento = ie_evento_p);


BEGIN

open c01;
loop
fetch c01 into
	nr_seq_status_paciente_w;
EXIT WHEN NOT FOUND; /* apply on c01 */
	begin
	null;
	end;
end loop;
close c01;

return	nr_seq_status_paciente_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION mprev_obter_status_pac_ag ( ie_evento_p text, dt_referencia_p timestamp) FROM PUBLIC;

