-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_solicitacao_laudo_pep ( nr_prescricao_p bigint, nr_atendimento_p bigint ) RETURNS varchar AS $body$
DECLARE


  ds_solicitacao_w varchar(40);



BEGIN

  select CASE WHEN  coalesce(nr_prescricao_p::text, '') = '' THEN  ''  ELSE obter_solicitacao( ie_tipo_atendimento  ) END  as ds_solicitacao into STRICT ds_solicitacao_w
  from atendimento_paciente
  where nr_atendimento = nr_atendimento_p;

  Return   ds_solicitacao_w;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_solicitacao_laudo_pep ( nr_prescricao_p bigint, nr_atendimento_p bigint ) FROM PUBLIC;

