-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_codigo_relatorio (nr_seq_relatorio_p bigint) RETURNS bigint AS $body$
DECLARE

 
cd_relat_w	bigint;			
			 

BEGIN 
 
select	max(cd_relatorio) 
into STRICT	cd_relat_w 
from	relatorio 
where	nr_sequencia = nr_seq_relatorio_p;
 
return	cd_relat_w;
 
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_codigo_relatorio (nr_seq_relatorio_p bigint) FROM PUBLIC;

