-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_alert_proc_setor (nr_prescricao_p bigint) RETURNS varchar AS $body$
DECLARE

 
ds_retorno_w		varchar(2000);
feed_line_w		varchar(3) := chr(10)||chr(13);
cd_setor_prescr_w	bigint;
ds_procedimento_w	varchar(255);
cd_prescritor_w		varchar(255);
cd_procedimento_w 	bigint;
ie_origem_proced_w	bigint;
cont_w			bigint;
cd_setor_proced_w	bigint;

c01 CURSOR FOR 
SELECT	substr(obter_descricao_procedimento(a.cd_procedimento,a.ie_origem_proced),1,255) ds_procedimento, 
	a.cd_procedimento, 
	a.ie_origem_proced, 
	a.cd_setor_proced 
from	rep_regra_alerta a 
where	cd_setor_atendimento = cd_setor_prescr_w 
and	((coalesce(a.cd_medico::text, '') = '') or (cd_prescritor_w = a.cd_medico)) 
and	((coalesce(a.cd_especialidade::text, '') = '') or (obter_se_especialidade_medico(cd_prescritor_w, cd_especialidade) = 'S')) 
order by ds_procedimento;
				

BEGIN 
 
select 	cd_setor_atendimento, 
	cd_prescritor 
into STRICT	cd_setor_prescr_w, 
	cd_prescritor_w 
from 	prescr_medica 
where 	nr_prescricao = nr_prescricao_p;
 
open C01;
loop 
fetch C01 into	 
	ds_procedimento_w, 
	cd_procedimento_w, 
	ie_origem_proced_w, 
	cd_setor_proced_w;
EXIT WHEN NOT FOUND; /* apply on C01 */
	if (coalesce(ds_retorno_w::text, '') = '') then 
		select	count(*) 
		into STRICT	cont_w 
		from	prescr_procedimento x 
		where	nr_prescricao	= nr_prescricao_p 
		and	cd_procedimento	= cd_procedimento_w 
		and	ie_origem_proced = ie_origem_proced_w 
		and	((coalesce(cd_setor_proced_w::text, '') = '') or (x.cd_setor_atendimento = cd_setor_proced_w));
		 
		if (cont_w = 0) then 
			ds_retorno_w := obter_desc_expressao(347073);--'Para este setor é necessário prescrever os seguintes procedimentos: '; 
		end if;
	end if;
	ds_retorno_w := ds_retorno_w || feed_line_w || cd_procedimento_w || ' - ' || ds_procedimento_w;
end loop;
close C01;
 
return	ds_retorno_w;
 
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_alert_proc_setor (nr_prescricao_p bigint) FROM PUBLIC;

