-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_custo_medio_ano_material ( cd_estabelecimento_p bigint, dt_ano_referencia_p timestamp, cd_material_p bigint) RETURNS bigint AS $body$
DECLARE


vl_custo_medio_ano_w	double precision;
vl_total_custo_medio_w	double precision;
qt_meses_custo_medio_w	smallint;


BEGIN

select 	sum(obter_custo_medio_material(cd_estabelecimento_p,dt_mes,cd_material_p))
into STRICT	vl_total_custo_medio_w
from 	mes_v
where	dt_mes between dt_ano_referencia_p and pkg_date_utils.add_month(dt_ano_referencia_p,11, 0);

select 	count(*)
into STRICT	qt_meses_custo_medio_w
from 	mes_v
where 	obter_custo_medio_material(cd_estabelecimento_p,dt_mes,cd_material_p) <> 0
and	dt_mes between dt_ano_referencia_p and pkg_date_utils.add_month(dt_ano_referencia_p,11, 0);

select 	dividir(vl_total_custo_medio_w,qt_meses_custo_medio_w)
into STRICT	vl_custo_medio_ano_w
;

return	vl_custo_medio_ano_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_custo_medio_ano_material ( cd_estabelecimento_p bigint, dt_ano_referencia_p timestamp, cd_material_p bigint) FROM PUBLIC;

