-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_codigo_cbo_saude ( nr_seq_cbo_p bigint) RETURNS varchar AS $body$
DECLARE


cd_retorno_w			varchar(15);


BEGIN

select	coalesce(max(cd_cbo),'')
into STRICT	cd_retorno_w
from	cbo_saude
where	nr_sequencia	= nr_seq_cbo_p;

return cd_retorno_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_codigo_cbo_saude ( nr_seq_cbo_p bigint) FROM PUBLIC;

