-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_se_cot_disp_forn ( nr_cot_compra_p bigint, cd_cgc_p text) RETURNS varchar AS $body$
DECLARE


ie_valida_w		varchar(1);
qt_ordem_w		smallint;


BEGIN
ie_valida_w	:= 'S';

select	count(*)
into STRICT	qt_ordem_w
from	cot_compra_forn a
where	a.nr_cot_compra	= nr_cot_compra_p
and	coalesce(a.cd_cgc_fornecedor, a.cd_pessoa_fisica)	= cd_cgc_p
and	exists (
	SELECT	1
	from	cot_compra b
	where	a.nr_cot_compra = b.nr_cot_compra
	and	(b.dt_geracao_ordem_compra IS NOT NULL AND b.dt_geracao_ordem_compra::text <> ''));
if (qt_ordem_w > 0) then
	ie_valida_w	:= 'N';
end if;

RETURN ie_valida_w;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_se_cot_disp_forn ( nr_cot_compra_p bigint, cd_cgc_p text) FROM PUBLIC;

