-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_info_os_localizacao (dt_inicial_p timestamp, dt_final_p timestamp, nr_seq_localizacao_p bigint, ie_tipo_inf_p text, ie_tipo_valor_p text) RETURNS bigint AS $body$
DECLARE


/*
ie_tipo_inf_p

QTOSRE		- Quantidade de OS's recebidas na Philips no período
QTOSRESO	- Quantidade de OS'S recebidas na Philips classificadas como solicitação
QTOSREDU	- Quantidade de OS'S recebidas na Philips classificadas como Dúvida
QTOSREDE	- Quantidade de OS'S recebidas na Philips classificadas como Defeito
QTOSRESUP	- Quantidade de OS's recebidas no suporte
QTOSREDES	- Quantidade de OS's recebidas no desenvolvimento e tecnologia
QTOSRESOSU	- Quantidade de OS's recebidas classificadas como solicitação ou sugestão que passaram pelo suporte
QTOSREDUSU	- Quantidade de OS's recebidas classificadas como dúvida que passaram pelo suporte
QTOSREDESU	- Quantidade de OS's recebidas classificadas como defeito que passaram pelo suporte
QTOSRESODES	- Quantidade de OS's recebidas classificadas como solicitação ou sugestão que passaram pelo desenvolvimento ou tecnologia
QTOSREDUDES	- Quantidade de OS's recebidas classificadas como Dúvida e que passaram pelo desenvolvimento ou tecnologia
QTOSREDEDES	- Quantidade de OS's recebidas classificadas como defeito que passaram pelo desenvolvimento ou tecnologia
QTOSREORI	- Quantidade de OS's recebidas no desenvolvimento e tecnologia e que foram feitas apenas orientações. OS's de solicitação ou sugestão sem atividade de programação.
QTOSREDEPRODES	- Quantidade de OS's recebidas no desenvolvimento e tecnologia que foram documentadas como defeitos do produto
QTOSREDECLIDES	- Quantidade de OS's recebidas no desenvolvimento e tecnologia que foram documentadas como defeitos do cliente. Base do cliente ou configurações/parametrizações erradas.

QTHOTRA 	- Quantidade de horas trabalhadas para o cliente no período
QTHOTRASO	- Quantidade de horas trabalhadas pelo desenvolvimento e suporte em OS's classificadas como solicitação ou susgestão
QTHOTRADU	- Quantidade de horas trabalhadas pelo desenvolvimento e suporte em OS's classificadas como dúvida
QTHOTRADE	- Quantidade de horas trabalhadas pelo desenvolvimento e suporte em OS's classificadas como defeito
QTHOTRASUP	- Quantidade de horas trabalhadas para o cliente no período pelo time de suporte
QTHOTRADES	- Quantidade de horas trabalhadas para o cliente no período pelo time de desenvolvimento e tecnologia
QTHOTRASOSU	- Quantidade de horas trabalhadas no suporte em OS's com classificação Philips de solicitação
QTHOTRADUSU	- Quantidade de horas trabalhadas no suporte em OS's com classificação Philips de Dúvida
QTHOTRADESU	- Quantidade de horas trabalhadas no suporte em OS's com classificação Philips de Defeito
QTHOTRASODES	- Quantidade de horas trabalhadas no desenvolvimento ou tecnologia em OS's com classificação Philips de solicitação ou sugestão
QTHOTRADUDES	- Quantidade de horas trabalhadas no desenvolvimento ou tecnologia em OS's com classificação Philips de Dúvida
QTHOTRADEDES	- Quantidade de horas trabalhadas no desenvolvimento ou tecnologia em OS's com classificação Philips de Defeito
QTHOTRAORI	- Quantidade de horas trabalhadas no desenvolvimento ou tecnologia em OS's de orientação. OS's de solicitação ou sugestão sem atividade de programação.
QTHOTRADEPRODES	- Quantidade de horas trabalhadas no desenvolvimento e tecnologia que foram documentadas como defeitos do produto.
QTHOTRADECLIDES	- Quantidade de horas trabalhadas no desenvolvimento e tecnologia que foram documentadas como defeitos do cliente. Base do cliente ou configurações/parametrizações erradas.


*/
qt_total_w	double precision := 0;


BEGIN

if (ie_tipo_inf_p = 'QTOSRE')   then

	select	count(1)
	into STRICT	qt_total_w
	from	man_ordem_servico
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRA') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		man_ordem_servico a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,4,7,17,33,16)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSRESUP') then

	select	count(1)
	into STRICT	qt_total_w
	from	os_recebida_gerencia_sup_v
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRASUP') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		os_recebida_gerencia_sup_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (4,17)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDES') then

	select	count(1)
	into STRICT	qt_total_w
	from	os_recebida_gerencia_desenv_v
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRADES') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,7,33,16)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSRESODES') then

	select	count(1)
	into STRICT	qt_total_w
	from	man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia		= b.nr_sequencia
	and	b.ie_classificacao in ('S','T')
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDUDES') then

	select	count(1)
	into STRICT	qt_total_w
	from	man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia		= b.nr_sequencia
	and	b.ie_classificacao	= 'D'
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDEDES') then

	select	count(1)
	into STRICT	qt_total_w
	from	man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia		= b.nr_sequencia
	and	b.ie_classificacao	= 'E'
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRASODES') then

	select	coalesce(round(sum(c.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ c,
		man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia 		= b.nr_sequencia
	and	a.nr_sequencia 		= c.nr_seq_ordem_serv
	and	u.nm_usuario		= c.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,7,33,16)
	and	b.ie_classificacao in ('S','T')
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRADUDES') then

	select	coalesce(round(sum(c.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ c,
		man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia 		= b.nr_sequencia
	and	a.nr_sequencia 		= c.nr_seq_ordem_serv
	and	u.nm_usuario		= c.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,7,33,16)
	and	b.ie_classificacao	= 'D'
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRADEDES') then

	select	coalesce(round(sum(c.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ c,
		man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia 		= b.nr_sequencia
	and	a.nr_sequencia 		= c.nr_seq_ordem_serv
	and	u.nm_usuario		= c.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,7,33,16)
	and	b.ie_classificacao	= 'E'
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRASOSU') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		os_recebida_gerencia_sup_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (4,17)
	and	a.ie_classificacao in ('S','T')
	and	a.nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRADUSU') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		os_recebida_gerencia_sup_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (4,17)
	and	a.ie_classificacao	= 'D'
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRADESU') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		os_recebida_gerencia_sup_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (4,17)
	and	a.ie_classificacao	= 'E'
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSRESO') then

	select	count(1)
	into STRICT	qt_total_w
	from	man_ordem_servico
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	ie_classificacao	in ('S','T')
	and	nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDU') then

	select	count(1)
	into STRICT	qt_total_w
	from	man_ordem_servico
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	ie_classificacao	= 'D'
	and	nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDE') then

	select	count(1)
	into STRICT	qt_total_w
	from	man_ordem_servico
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	ie_classificacao	= 'E'
	and	nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRASO') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		man_ordem_servico a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	a.ie_classificacao in ('S','T')
	and	u.cd_setor_atendimento in (2,4,7,17,33,16)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRADU') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		man_ordem_servico a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia		= b.nr_seq_ordem_serv
	and	u.nm_usuario		= b.nm_usuario_exec
	and	a.ie_classificacao	= 'D'
	and	u.cd_setor_atendimento in (2,4,7,17,33,16)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTHOTRADE') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		man_ordem_servico a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia		= b.nr_seq_ordem_serv
	and	u.nm_usuario		= b.nm_usuario_exec
	and	a.ie_classificacao 	= 'E'
	and	u.cd_setor_atendimento in (2,4,7,17,33,16)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREORI') then

	select	count(1)
	into STRICT	qt_total_w
	from	man_estagio_processo c,
		man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia		= b.nr_sequencia
	and	b.nr_seq_estagio	= c.nr_sequencia
	and	coalesce(c.ie_desenv,'N') 	<> 'S'
	and	b.ie_classificacao in ('S','T')
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p
	and	not exists (	SELECT	1
	                	from	man_ordem_serv_ativ d
		                where	d.nr_seq_ordem_serv = a.nr_sequencia
		                and	d.nr_seq_funcao in (11,1288,193,551));

elsif (ie_tipo_inf_p = 'QTHOTRAORI') then

	select	coalesce(round(sum(d.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ d,
		man_estagio_processo c,
		man_ordem_servico b,
		os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia		= b.nr_sequencia
	and	b.nr_seq_estagio	= c.nr_sequencia
	and	a.nr_sequencia		= d.nr_seq_ordem_serv
	and	u.nm_usuario		= d.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,7,33,16)
	and	coalesce(c.ie_desenv,'N')	<> 'S'
	and	b.ie_classificacao	= 'S'
	and	a.nr_seq_localizacao	= nr_seq_localizacao_p
	and	not exists (	SELECT	1
				from	man_ordem_serv_ativ d
				where	d.nr_seq_ordem_serv = a.nr_sequencia
				and	d.nr_seq_funcao in (11,1288,193,551));

elsif (ie_tipo_inf_p = 'QTOSRESOSU') then

	select	count(1)
	into STRICT	qt_total_w
	from	os_recebida_gerencia_sup_v
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	ie_classificacao in ('S','T')
	and	nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDUSU') then

	select	count(1)
	into STRICT	qt_total_w
	from	os_recebida_gerencia_sup_v
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	ie_classificacao	= 'D'
	and	nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDESU') then

	select	count(1)
	into STRICT	qt_total_w
	from	os_recebida_gerencia_sup_v
	where	dt_ordem_servico between dt_inicial_p and dt_final_p
	and	ie_classificacao	= 'E'
	and	nr_seq_localizacao	= nr_seq_localizacao_p;

elsif (ie_tipo_inf_p = 'QTOSREDEPRODES') then

	select	count(1)
	into STRICT	qt_total_w
	from	os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_seq_localizacao = nr_seq_localizacao_p
	and exists (	SELECT	1
			from	man_doc_erro b
			where	a.nr_sequencia	= b.nr_seq_ordem
			and	coalesce(b.ie_origem_erro,'KK') = 'W');

elsif (ie_tipo_inf_p = 'QTOSREDECLIDES') then

	select	count(1)
	into STRICT	qt_total_w
	from	os_recebida_gerencia_desenv_v a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_seq_localizacao = nr_seq_localizacao_p
	and exists (	SELECT	1
			from	man_doc_erro b
			where	a.nr_sequencia	= b.nr_seq_ordem
			and	coalesce(b.ie_origem_erro,'KK') <> 'W');

elsif (ie_tipo_inf_p = 'QTHOTRADEPRODES') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		man_ordem_servico a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,7,33,16)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p
	and exists (	SELECT	1
			from	man_doc_erro c
			where	a.nr_sequencia	= c.nr_seq_ordem
			and	coalesce(c.ie_origem_erro,'KK') = 'W');

elsif (ie_tipo_inf_p = 'QTHOTRADECLIDES') then

	select	coalesce(round(sum(b.qt_minuto)/60),0)
	into STRICT	qt_total_w
	from	usuario u,
		man_ordem_serv_ativ b,
		man_ordem_servico a
	where	a.dt_ordem_servico between dt_inicial_p and dt_final_p
	and	a.nr_sequencia	= b.nr_seq_ordem_serv
	and	u.nm_usuario	= b.nm_usuario_exec
	and	u.cd_setor_atendimento in (2,7,33,16)
	and	a.nr_seq_localizacao = nr_seq_localizacao_p
	and exists (	SELECT	1
			from	man_doc_erro c
			where	a.nr_sequencia	= c.nr_seq_ordem
			and	coalesce(c.ie_origem_erro,'KK') <> 'W');

end if;

return qt_total_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_info_os_localizacao (dt_inicial_p timestamp, dt_final_p timestamp, nr_seq_localizacao_p bigint, ie_tipo_inf_p text, ie_tipo_valor_p text) FROM PUBLIC;

