-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_desc_indicacao_ageint ( nr_sequencia_p bigint, ie_agenda_p text) RETURNS varchar AS $body$
DECLARE


ds_indicacao_w		varchar(4000) := '';


BEGIN

	if (coalesce(nr_sequencia_p,0) > 0 and (ie_agenda_p IS NOT NULL AND ie_agenda_p::text <> ''))then
		if (ie_agenda_p  = 'C')then
			select 	coalesce(ds_indicacao,'')
			into STRICT   	ds_indicacao_w
			from    	agenda_integrada b,
			                agenda_integrada_item c
		                where   	c.nr_seq_agenda_int   = b.nr_sequencia
                		and     	c.nr_seq_agenda_cons  = nr_sequencia_p;
		elsif (ie_agenda_p  = 'P')then
			select 	coalesce(ds_indicacao,'')
			into STRICT   	ds_indicacao_w
			from    	agenda_integrada b,
                        			agenda_integrada_item c
                		where   	c.nr_seq_agenda_int   = b.nr_sequencia
                		and     	c.nr_seq_agenda_exame  = nr_sequencia_p;
		end if;
	end if;

	return	ds_indicacao_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_desc_indicacao_ageint ( nr_sequencia_p bigint, ie_agenda_p text) FROM PUBLIC;

