-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_obs_prev_alta (nr_atendimento_p bigint) RETURNS varchar AS $body$
DECLARE


ds_observacao_w	varchar(255);



BEGIN

select	max(ds_observacao)
into STRICT	ds_observacao_w
from	atend_previsao_alta
where	nr_sequencia = (SELECT	max(nr_sequencia)
			from	atend_previsao_alta
			where	nr_atendimento = nr_atendimento_p
			and	(dt_liberacao IS NOT NULL AND dt_liberacao::text <> ''));

if (coalesce(ds_observacao_w::text, '') = '') then
	select	max(ds_obs_prev_alta)
	into STRICT	ds_observacao_w
	from	atendimento_paciente
	where	nr_atendimento = nr_atendimento_p;
end if;

return	ds_observacao_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_obs_prev_alta (nr_atendimento_p bigint) FROM PUBLIC;

