-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_vl_desc_item_relatorio ( nr_seq_propaci_p bigint, nr_seq_matpaci_p bigint, nr_interno_conta_p bigint, ie_imposto_p text) RETURNS bigint AS $body$
DECLARE

/* FUNCTION CRIADA PARA A VIEW  HSJ_RESUMO_CONTA_V */

/*ie_com_imposto_p
	'S'   considera imposto
	'N'  nao considera imposto
*/
vl_desc_item_w		double precision := 0;
qt_imposto_w		bigint := 0;
vl_original_w		double precision := 0;
qt_material_w		material_atend_paciente.qt_material%type   := 0;
qt_procedimento_w	procedimento_paciente.qt_procedimento%type := 0;
vl_material_w		material_atend_paciente.vl_material%type   := 0;
ie_conta_deducao_w	varchar(2);
vl_procedimento_w	procedimento_paciente.vl_procedimento%type := 0;


BEGIN

if (coalesce(nr_seq_propaci_p,0) > 0) then
	select 	CASE WHEN count(1)=0 THEN 'N'  ELSE 'S' END
	into STRICT	ie_conta_deducao_w
	from 	conta_pac_ded_conv_item z
	where 	z.nr_seq_propaci_dest = nr_seq_propaci_p;

	if (ie_conta_deducao_w = 'S') then
		return vl_desc_item_w;
	end if;

	select 	count(1)
	into STRICT    qt_imposto_w
	from 	propaci_imposto
	where 	nr_seq_propaci = nr_seq_propaci_p
	and 	pr_imposto > 0;

	if (ie_imposto_p  = 'N' and qt_imposto_w > 0) or (ie_imposto_p  = 'S' and qt_imposto_w = 0) then
		return vl_desc_item_w;
	end if;

	vl_original_w := coalesce(obter_vl_item_conta_original( nr_seq_propaci_p,null),0);

	if ( vl_original_w <> 0) then
		select  qt_procedimento,
			coalesce(vl_procedimento,0)
		into STRICT	qt_procedimento_w,
			vl_procedimento_w --trocar
		from  	procedimento_paciente
		where 	nr_sequencia = nr_seq_propaci_p;

		vl_desc_item_w	:= 	(vl_original_w * qt_procedimento_w)
					- vl_procedimento_w
					- obter_valor_deducao_conv(nr_interno_conta_p,nr_seq_propaci_p,null,null,null);
	end if;

elsif (coalesce(nr_seq_matpaci_p,0) > 0) then

	select 	CASE WHEN count(1)=0 THEN 'N'  ELSE 'S' END
	into STRICT	ie_conta_deducao_w
	from 	conta_pac_ded_conv_item z
	where 	z.nr_seq_matpaci_dest = nr_seq_matpaci_p;

	if (ie_conta_deducao_w = 'S') then
		return vl_desc_item_w;
	end if;

	select 	count(1)
	into STRICT    qt_imposto_w
	from 	matpaci_imposto
	where 	nr_seq_matpaci = nr_seq_matpaci_p
	and 	pr_imposto > 0;

	if (ie_imposto_p  = 'N' and qt_imposto_w > 0) or (ie_imposto_p  = 'S' and qt_imposto_w = 0) then
		return vl_desc_item_w;
	end if;

	vl_original_w := coalesce(obter_vl_item_conta_original(null,nr_seq_matpaci_p),0);

	if ( vl_original_w <> 0) then
		select  qt_material,
			coalesce(vl_material,0)
		into STRICT	qt_material_w,
			vl_material_w
		from  	material_atend_paciente
		where 	nr_sequencia = nr_seq_matpaci_p;

		vl_desc_item_w	:= 	(vl_original_w * qt_material_w)
					- vl_material_w
					- obter_valor_deducao_conv(nr_interno_conta_p,null,nr_seq_matpaci_p,null,null);
	end if;

end if;

return	vl_desc_item_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_vl_desc_item_relatorio ( nr_seq_propaci_p bigint, nr_seq_matpaci_p bigint, nr_interno_conta_p bigint, ie_imposto_p text) FROM PUBLIC;

