-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_cor_triagem_mapa ( nr_atendimento_p bigint, ie_tipo_cor_p text) RETURNS varchar AS $body$
DECLARE

 
nr_seq_classif_w	integer;
ds_cor_w		varchar(15)	:=	'';

 

BEGIN 
 
 
select	max(NR_SEQ_CLASSIF) 
into STRICT	nr_seq_classif_w 
from	TRIAGEM_PRONTO_ATEND 
where	nr_atendimento	=	nr_atendimento_p;
 
if (nr_seq_classif_w > 0) then 
	begin	 
		 
		 
	if (upper(ie_tipo_cor_p) = 'FONTE') then 
 
		select	max(DS_COR_FONTE) 
		into STRICT	ds_cor_w 
		from	TRIAGEM_CLASSIF_RISCO 
		where	nr_sequencia = nr_seq_classif_w;	
	 
	 
	elsif (uppeR(ie_tipo_cor_p) = 'FUNDO') then 
	 
		select	max(DS_COR) 
		into STRICT	ds_cor_w 
		from	TRIAGEM_CLASSIF_RISCO 
		where	nr_sequencia = nr_seq_classif_w;	
	end if;
	 
	end;
end if;
 
 
return	ds_cor_w;
 
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_cor_triagem_mapa ( nr_atendimento_p bigint, ie_tipo_cor_p text) FROM PUBLIC;

