-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_se_exibe_intervalo ( nr_prescricao_p bigint, cd_intervalo_p text, cd_setor_exec_p bigint) RETURNS varchar AS $body$
DECLARE


ie_exibe_w					varchar(1) := 'S';
cd_setor_atendimento_w		integer;
cd_prescritor_w				varchar(10);
cd_perfil_ativo_w			bigint;
cd_estab_w					bigint;

c01 CURSOR FOR
SELECT	coalesce(ie_exibir,'N')
from	setor_intervalo
where	(((coalesce(ie_setor,'P') = 'P') and (cd_setor_atendimento = cd_setor_atendimento_w)) or
		 ((coalesce(ie_setor,'P') = 'E') and
		  ((coalesce(cd_setor_exec_p,0) = 0) or (cd_setor_atendimento	= cd_setor_exec_p))) or (coalesce(cd_setor_atendimento::text, '') = ''))
and		((cd_prescritor_w = cd_pessoa_fisica) or (coalesce(cd_pessoa_fisica::text, '') = ''))
and		((cd_perfil_ativo_w = cd_perfil) or (coalesce(cd_perfil::text, '') = ''))
and		((coalesce(cd_estab::text, '') = '') or (cd_estab = cd_estab_w))
and		cd_intervalo		= cd_intervalo_p
order by
		cd_pessoa_fisica desc,
		cd_setor_atendimento desc,
		cd_perfil  desc;


BEGIN

if (nr_prescricao_p > 0) then

	select	coalesce(max('N'),'S')
	into STRICT	ie_exibe_w
	from	setor_intervalo
	where	cd_intervalo = cd_intervalo_p;

	if (ie_exibe_w = 'N') then

		select	coalesce(max(cd_setor_atendimento),0),
				max(cd_prescritor),
				max(cd_estabelecimento)
		into STRICT	cd_setor_atendimento_w,
				cd_prescritor_w,
				cd_estab_w
		from	prescr_medica
		where	nr_prescricao = nr_prescricao_p;

		cd_perfil_ativo_w	:= obter_perfil_ativo;

		ie_exibe_w := 'S';

		open C01;
		loop
		fetch C01 into
			ie_exibe_w;
		EXIT WHEN NOT FOUND; /* apply on C01 */
			begin
			ie_exibe_w	:= ie_exibe_w;
			end;
		end loop;
		close C01;

	end if;
end if;

return ie_exibe_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_se_exibe_intervalo ( nr_prescricao_p bigint, cd_intervalo_p text, cd_setor_exec_p bigint) FROM PUBLIC;

