-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_comp_regra_solic (cd_material_p bigint, nr_solic_compra_p bigint, nr_item_solic_compra_p bigint) RETURNS varchar AS $body$
DECLARE

 
nm_guerra_w			comprador.nm_guerra%type;


BEGIN 
 
select	sup_obter_nome_comprador(b.cd_estabelecimento, 
				obter_comprador_material(a.cd_material,obter_se_solic_compra_urgente(b.nr_solic_compra),b.cd_estabelecimento)) 
into STRICT	nm_guerra_w 
from	solic_compra_item a, 
	solic_compra b 
where	a.cd_material = cd_material_p 
and	a.nr_solic_compra = nr_solic_compra_p 
and	a.nr_solic_compra = b.nr_solic_compra 
and	a.nr_item_solic_compra = nr_item_solic_compra_p;
 
return	nm_guerra_w;
 
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_comp_regra_solic (cd_material_p bigint, nr_solic_compra_p bigint, nr_item_solic_compra_p bigint) FROM PUBLIC;

