-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION obter_dados_lote ( nr_seq_lote_p bigint, ie_tipo_dados_p text) RETURNS varchar AS $body$
DECLARE



ds_retorno_w		varchar(255);


BEGIN
/*
I - Data Inicial
D - Data Final
F - Data de Finalização
T - tipo do lote
S - Descrição do lote

*/
if ( ie_tipo_dados_p = 'I')	then
select	dt_inicial
into STRICT	ds_retorno_w
from	fis_lote
where	nr_sequencia	= nr_seq_lote_p;
end if;


if ( ie_tipo_dados_p = 'D')	then
select	dt_final
into STRICT	ds_retorno_w
from	fis_lote
where	nr_sequencia	= nr_seq_lote_p;
end if;

if ( ie_tipo_dados_p = 'F')	then
select	dt_finalizacao
into STRICT	ds_retorno_w
from	fis_lote
where	nr_sequencia	= nr_seq_lote_p;
end if;

if ( ie_tipo_dados_p = 'T')	then
select	ie_tipo_lote
into STRICT	ds_retorno_w
from	fis_lote
where	nr_sequencia	= nr_seq_lote_p;
end if;

if (ie_tipo_dados_p =  'S')	then
select	ds_lote
into STRICT	ds_retorno_w
from	fis_lote
where	nr_sequencia = nr_seq_lote_p;
end if;

if (ie_tipo_dados_p = 'C')		then
select	max(c.ds_cor)
into STRICT	ds_retorno_w
from	ap_lote l,
		classif_lote_disp_far c
where	l.nr_sequencia = nr_seq_lote_p
and		l.nr_seq_classif = c.nr_sequencia;
end if;

return	ds_retorno_w;


end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION obter_dados_lote ( nr_seq_lote_p bigint, ie_tipo_dados_p text) FROM PUBLIC;

