-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION pls_analise_obter_status_fat ( ie_status_item_p text, qt_original_p bigint, qt_liberada_p bigint, vl_original_p bigint, vl_liberado_p bigint) RETURNS varchar AS $body$
DECLARE


/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Finalidade: Obter o status de faturamento (ícone) da análise de pós-estabelecido
-------------------------------------------------------------------------------------------------------------------
Locais de chamada direta:
[  X]  Objetos do dicionário [ ] Tasy (Delphi/Java) [  ] Portal [  ]  Relatórios [ ] Outros:
 ------------------------------------------------------------------------------------------------------------------
Pontos de atenção:

U               Usuário (Aguardando Ação)
P               Permitido faturamento
L               Liberado para faturamento
D               Pendente de análise
N               Não permite faturamento
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
ie_faturamento_w	varchar(3)	:= null;


BEGIN

if (coalesce(vl_original_p,0) = 0) and (coalesce(vl_liberado_p,0) = 0) then
	ie_faturamento_w	:= 'G';
elsif (coalesce(vl_liberado_p,0) > 0) and
	((coalesce(vl_liberado_p,0) >= coalesce(vl_original_p,0)) or (coalesce(vl_original_p,0) = 0)) then
	ie_faturamento_w	:= 'L'; --Liberado
elsif (coalesce(vl_liberado_p,0) > 0) then
	ie_faturamento_w	:= 'P'; --Parcial
elsif (coalesce(vl_liberado_p,0) = 0) then
	ie_faturamento_w	:= 'G'; --Glosado
end if;

return	ie_faturamento_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION pls_analise_obter_status_fat ( ie_status_item_p text, qt_original_p bigint, qt_liberada_p bigint, vl_original_p bigint, vl_liberado_p bigint) FROM PUBLIC;

