-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION pls_obter_posivel_criar_conta ( nr_seq_protocolo_p bigint ) RETURNS bigint AS $body$
DECLARE



ds_retorno_w		bigint;
qt_contas_informadas_w	bigint;
qt_contas_w		bigint;


BEGIN

select	count(nr_sequencia)
into STRICT	qt_contas_w
from	pls_conta
where	nr_seq_protocolo = nr_seq_protocolo_p;

select	qt_contas_informadas
into STRICT	qt_contas_informadas_w
from	pls_protocolo_conta
where	nr_sequencia = nr_seq_protocolo_p;

	if	(qt_contas_w >= qt_contas_informadas_w AND qt_contas_informadas_w IS NOT NULL AND qt_contas_informadas_w::text <> '') then
		ds_retorno_w	:= 1;
	else
		ds_retorno_w	:= 0;
	end if;


return ds_retorno_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION pls_obter_posivel_criar_conta ( nr_seq_protocolo_p bigint ) FROM PUBLIC;

