-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION sup_obter_regra_planej_compra ( cd_estabelecimento_p bigint, cd_material_p bigint, ie_opcao_p text) RETURNS bigint AS $body$
DECLARE


/*ie_opcao_p
Q - Quantidade máxima entrega*/
qt_retorno_w				double precision;
qt_maximo_entrega_w			bigint;
cd_grupo_material_w			smallint;
cd_subgrupo_material_w			smallint;
cd_classe_material_w			integer;

c01 CURSOR FOR
SELECT	qt_maximo_entrega
from	regra_planej_entrega
where	coalesce(cd_grupo_material, cd_grupo_material_w)		= cd_grupo_material_w
and	coalesce(cd_subgrupo_material, cd_subgrupo_material_w)	= cd_subgrupo_material_w
and	coalesce(cd_classe_material, cd_classe_material_w)		= cd_classe_material_w
and (coalesce(cd_material, cd_material_p) 			= cd_material_p or cd_material_p = 0)
and (coalesce(cd_estabelecimento, cd_estabelecimento_p)		= cd_estabelecimento_p or cd_estabelecimento_p = 0)
and	qt_maximo_entrega > 0
order by	coalesce(cd_material, 0),
	coalesce(cd_classe_material, 0),
	coalesce(cd_subgrupo_material, 0),
	coalesce(cd_grupo_material, 0),
	coalesce(cd_estabelecimento, 0);


BEGIN

select	cd_grupo_material,
	cd_subgrupo_material,
	cd_classe_material
into STRICT	cd_grupo_material_w,
	cd_subgrupo_material_w,
	cd_classe_material_w
from	estrutura_material_v
where	cd_material = cd_material_p;

open C01;
loop
fetch C01 into
	qt_maximo_entrega_w;
EXIT WHEN NOT FOUND; /* apply on C01 */
	begin
	if (ie_opcao_p = 'Q') then
		qt_retorno_w := qt_maximo_entrega_w;
	end if;
	end;
end loop;
close C01;

return	qt_retorno_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION sup_obter_regra_planej_compra ( cd_estabelecimento_p bigint, cd_material_p bigint, ie_opcao_p text) FROM PUBLIC;

