-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';





CREATE OR REPLACE FUNCTION tiss_obter_codigo_estado (sg_estado_p text) RETURNS bigint AS $body$
DECLARE

		
		
/*
Esta function é utilizada também nos relatórios do TISS e projetos XML
*/
		

cd_estado_w	bigint;
sg_estado_w	varchar(10);
		

BEGIN

--Tratamento para o valor IN - Outros (Internacional), do domínio 50 Estados Brasileiros, pois para o TISS a sigla é EX
if (sg_estado_p = 'IN') then
	sg_estado_w	:= 'EX';
else	
	sg_estado_w 	:= sg_estado_p;
end if;

select	max(cd_estado)
into STRICT	cd_estado_w
from	tiss_unidade_federativa
where	sg_estado	= upper(sg_estado_w);

return	cd_estado_w;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
 STABLE;
-- REVOKE ALL ON FUNCTION tiss_obter_codigo_estado (sg_estado_p text) FROM PUBLIC;

