-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';

DROP TRIGGER IF EXISTS material_conversao_tp ON material_conversao CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_material_conversao_tp() RETURNS trigger AS $BODY$
DECLARE nr_seq_w bigint;ds_s_w   varchar(1);ds_c_w   varchar(1);ds_w	   varchar(1);ie_log_w varchar(1);BEGIN BEGIN ds_s_w := to_char(OLD.NR_SEQUENCIA);  ds_c_w:=null;SELECT * FROM gravar_log_alteracao(substr(OLD.STRENGTH,1,4000), substr(NEW.STRENGTH,1,4000), NEW.nm_usuario, nr_seq_w, 'STRENGTH', ie_log_w, ds_w, 'MATERIAL_CONVERSAO', ds_s_w, ds_c_w) INTO STRICT nr_seq_w, ie_log_w; SELECT * FROM gravar_log_alteracao(substr(OLD.GFC_CODE,1,4000), substr(NEW.GFC_CODE,1,4000), NEW.nm_usuario, nr_seq_w, 'GFC_CODE', ie_log_w, ds_w, 'MATERIAL_CONVERSAO', ds_s_w, ds_c_w) INTO STRICT nr_seq_w, ie_log_w; SELECT * FROM gravar_log_alteracao(substr(OLD.GCR_CODE,1,4000), substr(NEW.GCR_CODE,1,4000), NEW.nm_usuario, nr_seq_w, 'GCR_CODE', ie_log_w, ds_w, 'MATERIAL_CONVERSAO', ds_s_w, ds_c_w) INTO STRICT nr_seq_w, ie_log_w; SELECT * FROM gravar_log_alteracao(substr(OLD.DS_FORM,1,4000), substr(NEW.DS_FORM,1,4000), NEW.nm_usuario, nr_seq_w, 'DS_FORM', ie_log_w, ds_w, 'MATERIAL_CONVERSAO', ds_s_w, ds_c_w) INTO STRICT nr_seq_w, ie_log_w;   exception when others then ds_w:= '1'; end;   END;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_material_conversao_tp() FROM PUBLIC;

CREATE TRIGGER material_conversao_tp
	AFTER UPDATE ON material_conversao FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_material_conversao_tp();

