-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';

DROP TRIGGER IF EXISTS smart_sae_saps_aftinsert ON pe_prescricao CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_smart_sae_saps_aftinsert() RETURNS trigger AS $BODY$
declare

reg_integracao_w		gerar_int_padrao.reg_integracao;
gera_sae_w	varchar(1);

BEGIN
	reg_integracao_w.cd_estab_documento := OBTER_ESTABELECIMENTO_ATIVO;

	if (NEW.ie_tipo = 'SAE') then
	
		select coalesce(max('S'),'N')
		into STRICT  gera_sae_w
		from  PE_PRESCR_PROC
		where nr_seq_prescr = NEW.nr_sequencia
		and   obter_se_gera_sae_sis_ter(NR_SEQ_PROC,'I') = 'S'
		and	  Smart_obter_se_sae(NR_SEQ_PROC, reg_integracao_w.cd_estab_documento, '303','PE',wheb_usuario_pck.get_nm_usuario) = 'S';
		
	end if;

	if (NEW.ie_tipo = 'SAPS') then
		select coalesce(max('S'),'N')
		into STRICT gera_sae_w
		from pe_prescr_item_result
		where nr_seq_prescr = NEW.nr_sequencia
		and obter_se_gera_sae_sis_ter(NR_SEQ_ITEM,'A') = 'S';
	end if;

	if (OLD.DT_LIBERACAO is null) and (NEW.DT_LIBERACAO is not null) and (gera_sae_w = 'S') then
		BEGIN		
			if (NEW.ie_tipo = 'SAE') then
				reg_integracao_w := gerar_int_padrao.gravar_integracao('303', NEW.NR_SEQUENCIA, NEW.nm_usuario, reg_integracao_w, 'DS_OPERACAO_P=CREATE');
			elsif (NEW.ie_tipo = 'SAPS') then
				reg_integracao_w := gerar_int_padrao.gravar_integracao('307', NEW.NR_SEQUENCIA, NEW.nm_usuario, reg_integracao_w, 'DS_OPERACAO_P=CREATE');
			end if;
		END;	
	elsif (OLD.DT_INATIVACAO is null) and (NEW.DT_INATIVACAO is not null) then
		BEGIN	
			if (NEW.ie_tipo = 'SAE') then
				reg_integracao_w := gerar_int_padrao.gravar_integracao('303', NEW.NR_SEQUENCIA, NEW.nm_usuario, reg_integracao_w, 'DS_OPERACAO_P=DELETE');
			elsif (NEW.ie_tipo = 'SAPS') then
				reg_integracao_w := gerar_int_padrao.gravar_integracao('307', NEW.NR_SEQUENCIA, NEW.nm_usuario, reg_integracao_w, 'DS_OPERACAO_P=DELETE');
			end if;
		END;	
	end if;
	
RETURN NEW;
end;
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_smart_sae_saps_aftinsert() FROM PUBLIC;

CREATE TRIGGER smart_sae_saps_aftinsert
	AFTER INSERT OR UPDATE ON pe_prescricao FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_smart_sae_saps_aftinsert();

