-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.1
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=srv-dbora-03.whebdc.com.br;service_name=DEV_1815;port=1521

SET client_encoding TO 'UTF8';




CREATE OR REPLACE PROCEDURE wheb_inconsistencia.do_execute_config_script (nm_tabela_p text, nm_objeto_p text, ie_tipo_objeto_in_p text) AS $body$
DECLARE

    TYPE TABLEOF_TASY_AJUSTE_BASE IS TABLE OF TASY_AJUSTE_BASE%rowtype;
    count_w     bigint;
    registro_w  TASY_AJUSTE_BASE%rowtype;
    registros_w TABLEOF_TASY_AJUSTE_BASE;
    script_w    varchar(4000);
    sql_w       varchar(1000);

BEGIN
    count_w := 0;
    sql_w   := wheb_inconsistencia.getsql_config_script(nm_tabela_p, nm_objeto_p, ie_tipo_objeto_in_p);

    IF coalesce(sql_w::text, '') = '' THEN
      RETURN;
    END IF;
    CALL WHEB_INCONSISTENCIA_LOG.LOG_COMMAND(sql_w);
    EXECUTE 'SELECT COUNT(1)' || sql_w INTO STRICT count_w;

    IF count_w <= 0 THEN
      RETURN;
    END IF;

    EXECUTE ' SELECT *' || sql_w || ' ORDER BY CD_AJUSTE_BASE' BULK COLLECT INTO STRICT registros_w;

    FOR I IN registros_w.FIRST..registros_w.LAST
    LOOP
      registro_w := registros_w(I);
      script_w := trim(both registro_w.DS_SCRIPT);
      CALL WHEB_INCONSISTENCIA_LOG.LOG_COMMAND(script_w);

      script_w := REPLACE(script_w, Chr(10), ' ');
      script_w := REPLACE(script_w, Chr(13), ' ');

      IF current_setting('wheb_inconsistencia.canchangedatabase')::boolean THEN
	CALL WHEB_INCONSISTENCIA_LOG.LOG_COMMAND(script_w);
        CALL executa_bloco_plsql(script_w);

      END IF;
    END LOOP;
  END;


$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE wheb_inconsistencia.do_execute_config_script (nm_tabela_p text, nm_objeto_p text, ie_tipo_objeto_in_p text) FROM PUBLIC;
